/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ActionsSummary6 type.
 */
public class ActionsSummary6 {
    private Integer id;
    private Boolean canAct;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ActionsSummary6() {
    }

    /**
     * Initialization constructor.
     * @param  id  Integer value for id.
     * @param  canAct  Boolean value for canAct.
     */
    public ActionsSummary6(
            Integer id,
            Boolean canAct) {
        this.id = id;
        this.canAct = canAct;
    }

    /**
     * Getter for Id.
     * @return Returns the Integer
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for Integer
     */
    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for CanAct.
     * @return Returns the Boolean
     */
    @JsonGetter("can_act")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getCanAct() {
        return canAct;
    }

    /**
     * Setter for CanAct.
     * @param canAct Value for Boolean
     */
    @JsonSetter("can_act")
    public void setCanAct(Boolean canAct) {
        this.canAct = canAct;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ActionsSummary6 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ActionsSummary6 [" + "id=" + id + ", canAct=" + canAct + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ActionsSummary6.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ActionsSummary6.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .canAct(getCanAct());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ActionsSummary6}.
     */
    public static class Builder {
        private Integer id;
        private Boolean canAct;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for id.
         * @param  id  Integer value for id.
         * @return Builder
         */
        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for canAct.
         * @param  canAct  Boolean value for canAct.
         * @return Builder
         */
        public Builder canAct(Boolean canAct) {
            this.canAct = canAct;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ActionsSummary6} object using the set fields.
         * @return {@link ActionsSummary6}
         */
        public ActionsSummary6 build() {
            ActionsSummary6 model =
                    new ActionsSummary6(id, canAct);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
