/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AdminUsersSilenceJsonResponse type.
 */
public class AdminUsersSilenceJsonResponse {
    private Silence silence;

    /**
     * Default constructor.
     */
    public AdminUsersSilenceJsonResponse() {
    }

    /**
     * Initialization constructor.
     * @param  silence  Silence value for silence.
     */
    public AdminUsersSilenceJsonResponse(
            Silence silence) {
        this.silence = silence;
    }

    /**
     * Getter for Silence.
     * @return Returns the Silence
     */
    @JsonGetter("silence")
    public Silence getSilence() {
        return silence;
    }

    /**
     * Setter for Silence.
     * @param silence Value for Silence
     */
    @JsonSetter("silence")
    public void setSilence(Silence silence) {
        this.silence = silence;
    }

    /**
     * Converts this AdminUsersSilenceJsonResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdminUsersSilenceJsonResponse [" + "silence=" + silence + "]";
    }

    /**
     * Builds a new {@link AdminUsersSilenceJsonResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AdminUsersSilenceJsonResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(silence);
        return builder;
    }

    /**
     * Class to build instances of {@link AdminUsersSilenceJsonResponse}.
     */
    public static class Builder {
        private Silence silence;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  silence  Silence value for silence.
         */
        public Builder(Silence silence) {
            this.silence = silence;
        }

        /**
         * Setter for silence.
         * @param  silence  Silence value for silence.
         * @return Builder
         */
        public Builder silence(Silence silence) {
            this.silence = silence;
            return this;
        }

        /**
         * Builds a new {@link AdminUsersSilenceJsonResponse} object using the set fields.
         * @return {@link AdminUsersSilenceJsonResponse}
         */
        public AdminUsersSilenceJsonResponse build() {
            return new AdminUsersSilenceJsonResponse(silence);
        }
    }
}
