/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AdminUsersJsonRequest type.
 */
public class AdminUsersJsonRequest {
    private Boolean deletePosts;
    private Boolean blockEmail;
    private Boolean blockUrls;
    private Boolean blockIp;

    /**
     * Default constructor.
     */
    public AdminUsersJsonRequest() {
    }

    /**
     * Initialization constructor.
     * @param  deletePosts  Boolean value for deletePosts.
     * @param  blockEmail  Boolean value for blockEmail.
     * @param  blockUrls  Boolean value for blockUrls.
     * @param  blockIp  Boolean value for blockIp.
     */
    public AdminUsersJsonRequest(
            Boolean deletePosts,
            Boolean blockEmail,
            Boolean blockUrls,
            Boolean blockIp) {
        this.deletePosts = deletePosts;
        this.blockEmail = blockEmail;
        this.blockUrls = blockUrls;
        this.blockIp = blockIp;
    }

    /**
     * Getter for DeletePosts.
     * @return Returns the Boolean
     */
    @JsonGetter("delete_posts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getDeletePosts() {
        return deletePosts;
    }

    /**
     * Setter for DeletePosts.
     * @param deletePosts Value for Boolean
     */
    @JsonSetter("delete_posts")
    public void setDeletePosts(Boolean deletePosts) {
        this.deletePosts = deletePosts;
    }

    /**
     * Getter for BlockEmail.
     * @return Returns the Boolean
     */
    @JsonGetter("block_email")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getBlockEmail() {
        return blockEmail;
    }

    /**
     * Setter for BlockEmail.
     * @param blockEmail Value for Boolean
     */
    @JsonSetter("block_email")
    public void setBlockEmail(Boolean blockEmail) {
        this.blockEmail = blockEmail;
    }

    /**
     * Getter for BlockUrls.
     * @return Returns the Boolean
     */
    @JsonGetter("block_urls")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getBlockUrls() {
        return blockUrls;
    }

    /**
     * Setter for BlockUrls.
     * @param blockUrls Value for Boolean
     */
    @JsonSetter("block_urls")
    public void setBlockUrls(Boolean blockUrls) {
        this.blockUrls = blockUrls;
    }

    /**
     * Getter for BlockIp.
     * @return Returns the Boolean
     */
    @JsonGetter("block_ip")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getBlockIp() {
        return blockIp;
    }

    /**
     * Setter for BlockIp.
     * @param blockIp Value for Boolean
     */
    @JsonSetter("block_ip")
    public void setBlockIp(Boolean blockIp) {
        this.blockIp = blockIp;
    }

    /**
     * Converts this AdminUsersJsonRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdminUsersJsonRequest [" + "deletePosts=" + deletePosts + ", blockEmail="
                + blockEmail + ", blockUrls=" + blockUrls + ", blockIp=" + blockIp + "]";
    }

    /**
     * Builds a new {@link AdminUsersJsonRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AdminUsersJsonRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .deletePosts(getDeletePosts())
                .blockEmail(getBlockEmail())
                .blockUrls(getBlockUrls())
                .blockIp(getBlockIp());
        return builder;
    }

    /**
     * Class to build instances of {@link AdminUsersJsonRequest}.
     */
    public static class Builder {
        private Boolean deletePosts;
        private Boolean blockEmail;
        private Boolean blockUrls;
        private Boolean blockIp;



        /**
         * Setter for deletePosts.
         * @param  deletePosts  Boolean value for deletePosts.
         * @return Builder
         */
        public Builder deletePosts(Boolean deletePosts) {
            this.deletePosts = deletePosts;
            return this;
        }

        /**
         * Setter for blockEmail.
         * @param  blockEmail  Boolean value for blockEmail.
         * @return Builder
         */
        public Builder blockEmail(Boolean blockEmail) {
            this.blockEmail = blockEmail;
            return this;
        }

        /**
         * Setter for blockUrls.
         * @param  blockUrls  Boolean value for blockUrls.
         * @return Builder
         */
        public Builder blockUrls(Boolean blockUrls) {
            this.blockUrls = blockUrls;
            return this;
        }

        /**
         * Setter for blockIp.
         * @param  blockIp  Boolean value for blockIp.
         * @return Builder
         */
        public Builder blockIp(Boolean blockIp) {
            this.blockIp = blockIp;
            return this;
        }

        /**
         * Builds a new {@link AdminUsersJsonRequest} object using the set fields.
         * @return {@link AdminUsersJsonRequest}
         */
        public AdminUsersJsonRequest build() {
            return new AdminUsersJsonRequest(deletePosts, blockEmail, blockUrls, blockIp);
        }
    }
}
