/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AdminUsersAnonymizeJsonResponse type.
 */
public class AdminUsersAnonymizeJsonResponse {
    private String success;
    private String username;

    /**
     * Default constructor.
     */
    public AdminUsersAnonymizeJsonResponse() {
    }

    /**
     * Initialization constructor.
     * @param  success  String value for success.
     * @param  username  String value for username.
     */
    public AdminUsersAnonymizeJsonResponse(
            String success,
            String username) {
        this.success = success;
        this.username = username;
    }

    /**
     * Getter for Success.
     * @return Returns the String
     */
    @JsonGetter("success")
    public String getSuccess() {
        return success;
    }

    /**
     * Setter for Success.
     * @param success Value for String
     */
    @JsonSetter("success")
    public void setSuccess(String success) {
        this.success = success;
    }

    /**
     * Getter for Username.
     * @return Returns the String
     */
    @JsonGetter("username")
    public String getUsername() {
        return username;
    }

    /**
     * Setter for Username.
     * @param username Value for String
     */
    @JsonSetter("username")
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Converts this AdminUsersAnonymizeJsonResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdminUsersAnonymizeJsonResponse [" + "success=" + success + ", username=" + username
                + "]";
    }

    /**
     * Builds a new {@link AdminUsersAnonymizeJsonResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AdminUsersAnonymizeJsonResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(success, username);
        return builder;
    }

    /**
     * Class to build instances of {@link AdminUsersAnonymizeJsonResponse}.
     */
    public static class Builder {
        private String success;
        private String username;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  success  String value for success.
         * @param  username  String value for username.
         */
        public Builder(String success, String username) {
            this.success = success;
            this.username = username;
        }

        /**
         * Setter for success.
         * @param  success  String value for success.
         * @return Builder
         */
        public Builder success(String success) {
            this.success = success;
            return this;
        }

        /**
         * Setter for username.
         * @param  username  String value for username.
         * @return Builder
         */
        public Builder username(String username) {
            this.username = username;
            return this;
        }

        /**
         * Builds a new {@link AdminUsersAnonymizeJsonResponse} object using the set fields.
         * @return {@link AdminUsersAnonymizeJsonResponse}
         */
        public AdminUsersAnonymizeJsonResponse build() {
            return new AdminUsersAnonymizeJsonResponse(success, username);
        }
    }
}
