/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AdminUsersSuspendJsonRequest type.
 */
public class AdminUsersSuspendJsonRequest {
    private String suspendUntil;
    private String reason;
    private String message;
    private String postAction;

    /**
     * Default constructor.
     */
    public AdminUsersSuspendJsonRequest() {
    }

    /**
     * Initialization constructor.
     * @param  suspendUntil  String value for suspendUntil.
     * @param  reason  String value for reason.
     * @param  message  String value for message.
     * @param  postAction  String value for postAction.
     */
    public AdminUsersSuspendJsonRequest(
            String suspendUntil,
            String reason,
            String message,
            String postAction) {
        this.suspendUntil = suspendUntil;
        this.reason = reason;
        this.message = message;
        this.postAction = postAction;
    }

    /**
     * Getter for SuspendUntil.
     * @return Returns the String
     */
    @JsonGetter("suspend_until")
    public String getSuspendUntil() {
        return suspendUntil;
    }

    /**
     * Setter for SuspendUntil.
     * @param suspendUntil Value for String
     */
    @JsonSetter("suspend_until")
    public void setSuspendUntil(String suspendUntil) {
        this.suspendUntil = suspendUntil;
    }

    /**
     * Getter for Reason.
     * @return Returns the String
     */
    @JsonGetter("reason")
    public String getReason() {
        return reason;
    }

    /**
     * Setter for Reason.
     * @param reason Value for String
     */
    @JsonSetter("reason")
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Getter for Message.
     * Will send an email with this message when present
     * @return Returns the String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * Will send an email with this message when present
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for PostAction.
     * @return Returns the String
     */
    @JsonGetter("post_action")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPostAction() {
        return postAction;
    }

    /**
     * Setter for PostAction.
     * @param postAction Value for String
     */
    @JsonSetter("post_action")
    public void setPostAction(String postAction) {
        this.postAction = postAction;
    }

    /**
     * Converts this AdminUsersSuspendJsonRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdminUsersSuspendJsonRequest [" + "suspendUntil=" + suspendUntil + ", reason="
                + reason + ", message=" + message + ", postAction=" + postAction + "]";
    }

    /**
     * Builds a new {@link AdminUsersSuspendJsonRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AdminUsersSuspendJsonRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(suspendUntil, reason)
                .message(getMessage())
                .postAction(getPostAction());
        return builder;
    }

    /**
     * Class to build instances of {@link AdminUsersSuspendJsonRequest}.
     */
    public static class Builder {
        private String suspendUntil;
        private String reason;
        private String message;
        private String postAction;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  suspendUntil  String value for suspendUntil.
         * @param  reason  String value for reason.
         */
        public Builder(String suspendUntil, String reason) {
            this.suspendUntil = suspendUntil;
            this.reason = reason;
        }

        /**
         * Setter for suspendUntil.
         * @param  suspendUntil  String value for suspendUntil.
         * @return Builder
         */
        public Builder suspendUntil(String suspendUntil) {
            this.suspendUntil = suspendUntil;
            return this;
        }

        /**
         * Setter for reason.
         * @param  reason  String value for reason.
         * @return Builder
         */
        public Builder reason(String reason) {
            this.reason = reason;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for postAction.
         * @param  postAction  String value for postAction.
         * @return Builder
         */
        public Builder postAction(String postAction) {
            this.postAction = postAction;
            return this;
        }

        /**
         * Builds a new {@link AdminUsersSuspendJsonRequest} object using the set fields.
         * @return {@link AdminUsersSuspendJsonRequest}
         */
        public AdminUsersSuspendJsonRequest build() {
            return new AdminUsersSuspendJsonRequest(suspendUntil, reason, message, postAction);
        }
    }
}
