/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for CategoryList type.
 */
public class CategoryList {
    private boolean canCreateCategory;
    private boolean canCreateTopic;
    private List<Category1> categories;

    /**
     * Default constructor.
     */
    public CategoryList() {
    }

    /**
     * Initialization constructor.
     * @param  canCreateCategory  boolean value for canCreateCategory.
     * @param  canCreateTopic  boolean value for canCreateTopic.
     * @param  categories  List of Category1 value for categories.
     */
    public CategoryList(
            boolean canCreateCategory,
            boolean canCreateTopic,
            List<Category1> categories) {
        this.canCreateCategory = canCreateCategory;
        this.canCreateTopic = canCreateTopic;
        this.categories = categories;
    }

    /**
     * Getter for CanCreateCategory.
     * @return Returns the boolean
     */
    @JsonGetter("can_create_category")
    public boolean getCanCreateCategory() {
        return canCreateCategory;
    }

    /**
     * Setter for CanCreateCategory.
     * @param canCreateCategory Value for boolean
     */
    @JsonSetter("can_create_category")
    public void setCanCreateCategory(boolean canCreateCategory) {
        this.canCreateCategory = canCreateCategory;
    }

    /**
     * Getter for CanCreateTopic.
     * @return Returns the boolean
     */
    @JsonGetter("can_create_topic")
    public boolean getCanCreateTopic() {
        return canCreateTopic;
    }

    /**
     * Setter for CanCreateTopic.
     * @param canCreateTopic Value for boolean
     */
    @JsonSetter("can_create_topic")
    public void setCanCreateTopic(boolean canCreateTopic) {
        this.canCreateTopic = canCreateTopic;
    }

    /**
     * Getter for Categories.
     * @return Returns the List of Category1
     */
    @JsonGetter("categories")
    public List<Category1> getCategories() {
        return categories;
    }

    /**
     * Setter for Categories.
     * @param categories Value for List of Category1
     */
    @JsonSetter("categories")
    public void setCategories(List<Category1> categories) {
        this.categories = categories;
    }

    /**
     * Converts this CategoryList into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CategoryList [" + "canCreateCategory=" + canCreateCategory + ", canCreateTopic="
                + canCreateTopic + ", categories=" + categories + "]";
    }

    /**
     * Builds a new {@link CategoryList.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CategoryList.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(canCreateCategory, canCreateTopic, categories);
        return builder;
    }

    /**
     * Class to build instances of {@link CategoryList}.
     */
    public static class Builder {
        private boolean canCreateCategory;
        private boolean canCreateTopic;
        private List<Category1> categories;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  canCreateCategory  boolean value for canCreateCategory.
         * @param  canCreateTopic  boolean value for canCreateTopic.
         * @param  categories  List of Category1 value for categories.
         */
        public Builder(boolean canCreateCategory, boolean canCreateTopic,
                List<Category1> categories) {
            this.canCreateCategory = canCreateCategory;
            this.canCreateTopic = canCreateTopic;
            this.categories = categories;
        }

        /**
         * Setter for canCreateCategory.
         * @param  canCreateCategory  boolean value for canCreateCategory.
         * @return Builder
         */
        public Builder canCreateCategory(boolean canCreateCategory) {
            this.canCreateCategory = canCreateCategory;
            return this;
        }

        /**
         * Setter for canCreateTopic.
         * @param  canCreateTopic  boolean value for canCreateTopic.
         * @return Builder
         */
        public Builder canCreateTopic(boolean canCreateTopic) {
            this.canCreateTopic = canCreateTopic;
            return this;
        }

        /**
         * Setter for categories.
         * @param  categories  List of Category1 value for categories.
         * @return Builder
         */
        public Builder categories(List<Category1> categories) {
            this.categories = categories;
            return this;
        }

        /**
         * Builds a new {@link CategoryList} object using the set fields.
         * @return {@link CategoryList}
         */
        public CategoryList build() {
            return new CategoryList(canCreateCategory, canCreateTopic, categories);
        }
    }
}
