/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CategoryType type.
 */
public class CategoryType {
    private String id;
    private String name;
    private String title;
    private String description;
    private String icon;
    private boolean available;
    private boolean visible;
    private Object configurationSchema;

    /**
     * Default constructor.
     */
    public CategoryType() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  name  String value for name.
     * @param  title  String value for title.
     * @param  description  String value for description.
     * @param  icon  String value for icon.
     * @param  available  boolean value for available.
     * @param  visible  boolean value for visible.
     * @param  configurationSchema  Object value for configurationSchema.
     */
    public CategoryType(
            String id,
            String name,
            String title,
            String description,
            String icon,
            boolean available,
            boolean visible,
            Object configurationSchema) {
        this.id = id;
        this.name = name;
        this.title = title;
        this.description = description;
        this.icon = icon;
        this.available = available;
        this.visible = visible;
        this.configurationSchema = configurationSchema;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Icon.
     * @return Returns the String
     */
    @JsonGetter("icon")
    public String getIcon() {
        return icon;
    }

    /**
     * Setter for Icon.
     * @param icon Value for String
     */
    @JsonSetter("icon")
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * Getter for Available.
     * @return Returns the boolean
     */
    @JsonGetter("available")
    public boolean getAvailable() {
        return available;
    }

    /**
     * Setter for Available.
     * @param available Value for boolean
     */
    @JsonSetter("available")
    public void setAvailable(boolean available) {
        this.available = available;
    }

    /**
     * Getter for Visible.
     * @return Returns the boolean
     */
    @JsonGetter("visible")
    public boolean getVisible() {
        return visible;
    }

    /**
     * Setter for Visible.
     * @param visible Value for boolean
     */
    @JsonSetter("visible")
    public void setVisible(boolean visible) {
        this.visible = visible;
    }

    /**
     * Getter for ConfigurationSchema.
     * @return Returns the Object
     */
    @JsonGetter("configuration_schema")
    public Object getConfigurationSchema() {
        return configurationSchema;
    }

    /**
     * Setter for ConfigurationSchema.
     * @param configurationSchema Value for Object
     */
    @JsonSetter("configuration_schema")
    public void setConfigurationSchema(Object configurationSchema) {
        this.configurationSchema = configurationSchema;
    }

    /**
     * Converts this CategoryType into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CategoryType [" + "id=" + id + ", name=" + name + ", title=" + title
                + ", description=" + description + ", icon=" + icon + ", available=" + available
                + ", visible=" + visible + ", configurationSchema=" + configurationSchema + "]";
    }

    /**
     * Builds a new {@link CategoryType.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CategoryType.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, name, title, description, icon, available, visible,
                configurationSchema);
        return builder;
    }

    /**
     * Class to build instances of {@link CategoryType}.
     */
    public static class Builder {
        private String id;
        private String name;
        private String title;
        private String description;
        private String icon;
        private boolean available;
        private boolean visible;
        private Object configurationSchema;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  name  String value for name.
         * @param  title  String value for title.
         * @param  description  String value for description.
         * @param  icon  String value for icon.
         * @param  available  boolean value for available.
         * @param  visible  boolean value for visible.
         * @param  configurationSchema  Object value for configurationSchema.
         */
        public Builder(String id, String name, String title, String description, String icon,
                boolean available, boolean visible, Object configurationSchema) {
            this.id = id;
            this.name = name;
            this.title = title;
            this.description = description;
            this.icon = icon;
            this.available = available;
            this.visible = visible;
            this.configurationSchema = configurationSchema;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for icon.
         * @param  icon  String value for icon.
         * @return Builder
         */
        public Builder icon(String icon) {
            this.icon = icon;
            return this;
        }

        /**
         * Setter for available.
         * @param  available  boolean value for available.
         * @return Builder
         */
        public Builder available(boolean available) {
            this.available = available;
            return this;
        }

        /**
         * Setter for visible.
         * @param  visible  boolean value for visible.
         * @return Builder
         */
        public Builder visible(boolean visible) {
            this.visible = visible;
            return this;
        }

        /**
         * Setter for configurationSchema.
         * @param  configurationSchema  Object value for configurationSchema.
         * @return Builder
         */
        public Builder configurationSchema(Object configurationSchema) {
            this.configurationSchema = configurationSchema;
            return this;
        }

        /**
         * Builds a new {@link CategoryType} object using the set fields.
         * @return {@link CategoryType}
         */
        public CategoryType build() {
            return new CategoryType(id, name, title, description, icon, available, visible,
                    configurationSchema);
        }
    }
}
