/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Details type.
 */
public class Details {
    private boolean canEdit;
    private int notificationLevel;
    private boolean canMovePosts;
    private boolean canDelete;
    private boolean canRemoveAllowedUsers;
    private boolean canCreatePost;
    private boolean canReplyAsNewTopic;
    private Boolean canInviteTo;
    private Boolean canInviteViaEmail;
    private Boolean canFlagTopic;
    private boolean canConvertTopic;
    private boolean canReviewTopic;
    private boolean canCloseTopic;
    private boolean canArchiveTopic;
    private boolean canSplitMergeTopic;
    private boolean canEditStaffNotes;
    private boolean canToggleTopicVisibility;
    private boolean canPinUnpinTopic;
    private Boolean canBannerTopic;
    private boolean canModerateCategory;
    private int canRemoveSelfId;
    private List<Participant1> participants;
    private CreatedBy createdBy;
    private LastPoster lastPoster;

    /**
     * Default constructor.
     */
    public Details() {
    }

    /**
     * Initialization constructor.
     * @param  canEdit  boolean value for canEdit.
     * @param  notificationLevel  int value for notificationLevel.
     * @param  canMovePosts  boolean value for canMovePosts.
     * @param  canDelete  boolean value for canDelete.
     * @param  canRemoveAllowedUsers  boolean value for canRemoveAllowedUsers.
     * @param  canCreatePost  boolean value for canCreatePost.
     * @param  canReplyAsNewTopic  boolean value for canReplyAsNewTopic.
     * @param  canConvertTopic  boolean value for canConvertTopic.
     * @param  canReviewTopic  boolean value for canReviewTopic.
     * @param  canCloseTopic  boolean value for canCloseTopic.
     * @param  canArchiveTopic  boolean value for canArchiveTopic.
     * @param  canSplitMergeTopic  boolean value for canSplitMergeTopic.
     * @param  canEditStaffNotes  boolean value for canEditStaffNotes.
     * @param  canToggleTopicVisibility  boolean value for canToggleTopicVisibility.
     * @param  canPinUnpinTopic  boolean value for canPinUnpinTopic.
     * @param  canModerateCategory  boolean value for canModerateCategory.
     * @param  canRemoveSelfId  int value for canRemoveSelfId.
     * @param  createdBy  CreatedBy value for createdBy.
     * @param  lastPoster  LastPoster value for lastPoster.
     * @param  canInviteTo  Boolean value for canInviteTo.
     * @param  canInviteViaEmail  Boolean value for canInviteViaEmail.
     * @param  canFlagTopic  Boolean value for canFlagTopic.
     * @param  canBannerTopic  Boolean value for canBannerTopic.
     * @param  participants  List of Participant1 value for participants.
     */
    public Details(
            boolean canEdit,
            int notificationLevel,
            boolean canMovePosts,
            boolean canDelete,
            boolean canRemoveAllowedUsers,
            boolean canCreatePost,
            boolean canReplyAsNewTopic,
            boolean canConvertTopic,
            boolean canReviewTopic,
            boolean canCloseTopic,
            boolean canArchiveTopic,
            boolean canSplitMergeTopic,
            boolean canEditStaffNotes,
            boolean canToggleTopicVisibility,
            boolean canPinUnpinTopic,
            boolean canModerateCategory,
            int canRemoveSelfId,
            CreatedBy createdBy,
            LastPoster lastPoster,
            Boolean canInviteTo,
            Boolean canInviteViaEmail,
            Boolean canFlagTopic,
            Boolean canBannerTopic,
            List<Participant1> participants) {
        this.canEdit = canEdit;
        this.notificationLevel = notificationLevel;
        this.canMovePosts = canMovePosts;
        this.canDelete = canDelete;
        this.canRemoveAllowedUsers = canRemoveAllowedUsers;
        this.canCreatePost = canCreatePost;
        this.canReplyAsNewTopic = canReplyAsNewTopic;
        this.canInviteTo = canInviteTo;
        this.canInviteViaEmail = canInviteViaEmail;
        this.canFlagTopic = canFlagTopic;
        this.canConvertTopic = canConvertTopic;
        this.canReviewTopic = canReviewTopic;
        this.canCloseTopic = canCloseTopic;
        this.canArchiveTopic = canArchiveTopic;
        this.canSplitMergeTopic = canSplitMergeTopic;
        this.canEditStaffNotes = canEditStaffNotes;
        this.canToggleTopicVisibility = canToggleTopicVisibility;
        this.canPinUnpinTopic = canPinUnpinTopic;
        this.canBannerTopic = canBannerTopic;
        this.canModerateCategory = canModerateCategory;
        this.canRemoveSelfId = canRemoveSelfId;
        this.participants = participants;
        this.createdBy = createdBy;
        this.lastPoster = lastPoster;
    }

    /**
     * Getter for CanEdit.
     * @return Returns the boolean
     */
    @JsonGetter("can_edit")
    public boolean getCanEdit() {
        return canEdit;
    }

    /**
     * Setter for CanEdit.
     * @param canEdit Value for boolean
     */
    @JsonSetter("can_edit")
    public void setCanEdit(boolean canEdit) {
        this.canEdit = canEdit;
    }

    /**
     * Getter for NotificationLevel.
     * @return Returns the int
     */
    @JsonGetter("notification_level")
    public int getNotificationLevel() {
        return notificationLevel;
    }

    /**
     * Setter for NotificationLevel.
     * @param notificationLevel Value for int
     */
    @JsonSetter("notification_level")
    public void setNotificationLevel(int notificationLevel) {
        this.notificationLevel = notificationLevel;
    }

    /**
     * Getter for CanMovePosts.
     * @return Returns the boolean
     */
    @JsonGetter("can_move_posts")
    public boolean getCanMovePosts() {
        return canMovePosts;
    }

    /**
     * Setter for CanMovePosts.
     * @param canMovePosts Value for boolean
     */
    @JsonSetter("can_move_posts")
    public void setCanMovePosts(boolean canMovePosts) {
        this.canMovePosts = canMovePosts;
    }

    /**
     * Getter for CanDelete.
     * @return Returns the boolean
     */
    @JsonGetter("can_delete")
    public boolean getCanDelete() {
        return canDelete;
    }

    /**
     * Setter for CanDelete.
     * @param canDelete Value for boolean
     */
    @JsonSetter("can_delete")
    public void setCanDelete(boolean canDelete) {
        this.canDelete = canDelete;
    }

    /**
     * Getter for CanRemoveAllowedUsers.
     * @return Returns the boolean
     */
    @JsonGetter("can_remove_allowed_users")
    public boolean getCanRemoveAllowedUsers() {
        return canRemoveAllowedUsers;
    }

    /**
     * Setter for CanRemoveAllowedUsers.
     * @param canRemoveAllowedUsers Value for boolean
     */
    @JsonSetter("can_remove_allowed_users")
    public void setCanRemoveAllowedUsers(boolean canRemoveAllowedUsers) {
        this.canRemoveAllowedUsers = canRemoveAllowedUsers;
    }

    /**
     * Getter for CanCreatePost.
     * @return Returns the boolean
     */
    @JsonGetter("can_create_post")
    public boolean getCanCreatePost() {
        return canCreatePost;
    }

    /**
     * Setter for CanCreatePost.
     * @param canCreatePost Value for boolean
     */
    @JsonSetter("can_create_post")
    public void setCanCreatePost(boolean canCreatePost) {
        this.canCreatePost = canCreatePost;
    }

    /**
     * Getter for CanReplyAsNewTopic.
     * @return Returns the boolean
     */
    @JsonGetter("can_reply_as_new_topic")
    public boolean getCanReplyAsNewTopic() {
        return canReplyAsNewTopic;
    }

    /**
     * Setter for CanReplyAsNewTopic.
     * @param canReplyAsNewTopic Value for boolean
     */
    @JsonSetter("can_reply_as_new_topic")
    public void setCanReplyAsNewTopic(boolean canReplyAsNewTopic) {
        this.canReplyAsNewTopic = canReplyAsNewTopic;
    }

    /**
     * Getter for CanInviteTo.
     * @return Returns the Boolean
     */
    @JsonGetter("can_invite_to")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getCanInviteTo() {
        return canInviteTo;
    }

    /**
     * Setter for CanInviteTo.
     * @param canInviteTo Value for Boolean
     */
    @JsonSetter("can_invite_to")
    public void setCanInviteTo(Boolean canInviteTo) {
        this.canInviteTo = canInviteTo;
    }

    /**
     * Getter for CanInviteViaEmail.
     * @return Returns the Boolean
     */
    @JsonGetter("can_invite_via_email")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getCanInviteViaEmail() {
        return canInviteViaEmail;
    }

    /**
     * Setter for CanInviteViaEmail.
     * @param canInviteViaEmail Value for Boolean
     */
    @JsonSetter("can_invite_via_email")
    public void setCanInviteViaEmail(Boolean canInviteViaEmail) {
        this.canInviteViaEmail = canInviteViaEmail;
    }

    /**
     * Getter for CanFlagTopic.
     * @return Returns the Boolean
     */
    @JsonGetter("can_flag_topic")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getCanFlagTopic() {
        return canFlagTopic;
    }

    /**
     * Setter for CanFlagTopic.
     * @param canFlagTopic Value for Boolean
     */
    @JsonSetter("can_flag_topic")
    public void setCanFlagTopic(Boolean canFlagTopic) {
        this.canFlagTopic = canFlagTopic;
    }

    /**
     * Getter for CanConvertTopic.
     * @return Returns the boolean
     */
    @JsonGetter("can_convert_topic")
    public boolean getCanConvertTopic() {
        return canConvertTopic;
    }

    /**
     * Setter for CanConvertTopic.
     * @param canConvertTopic Value for boolean
     */
    @JsonSetter("can_convert_topic")
    public void setCanConvertTopic(boolean canConvertTopic) {
        this.canConvertTopic = canConvertTopic;
    }

    /**
     * Getter for CanReviewTopic.
     * @return Returns the boolean
     */
    @JsonGetter("can_review_topic")
    public boolean getCanReviewTopic() {
        return canReviewTopic;
    }

    /**
     * Setter for CanReviewTopic.
     * @param canReviewTopic Value for boolean
     */
    @JsonSetter("can_review_topic")
    public void setCanReviewTopic(boolean canReviewTopic) {
        this.canReviewTopic = canReviewTopic;
    }

    /**
     * Getter for CanCloseTopic.
     * @return Returns the boolean
     */
    @JsonGetter("can_close_topic")
    public boolean getCanCloseTopic() {
        return canCloseTopic;
    }

    /**
     * Setter for CanCloseTopic.
     * @param canCloseTopic Value for boolean
     */
    @JsonSetter("can_close_topic")
    public void setCanCloseTopic(boolean canCloseTopic) {
        this.canCloseTopic = canCloseTopic;
    }

    /**
     * Getter for CanArchiveTopic.
     * @return Returns the boolean
     */
    @JsonGetter("can_archive_topic")
    public boolean getCanArchiveTopic() {
        return canArchiveTopic;
    }

    /**
     * Setter for CanArchiveTopic.
     * @param canArchiveTopic Value for boolean
     */
    @JsonSetter("can_archive_topic")
    public void setCanArchiveTopic(boolean canArchiveTopic) {
        this.canArchiveTopic = canArchiveTopic;
    }

    /**
     * Getter for CanSplitMergeTopic.
     * @return Returns the boolean
     */
    @JsonGetter("can_split_merge_topic")
    public boolean getCanSplitMergeTopic() {
        return canSplitMergeTopic;
    }

    /**
     * Setter for CanSplitMergeTopic.
     * @param canSplitMergeTopic Value for boolean
     */
    @JsonSetter("can_split_merge_topic")
    public void setCanSplitMergeTopic(boolean canSplitMergeTopic) {
        this.canSplitMergeTopic = canSplitMergeTopic;
    }

    /**
     * Getter for CanEditStaffNotes.
     * @return Returns the boolean
     */
    @JsonGetter("can_edit_staff_notes")
    public boolean getCanEditStaffNotes() {
        return canEditStaffNotes;
    }

    /**
     * Setter for CanEditStaffNotes.
     * @param canEditStaffNotes Value for boolean
     */
    @JsonSetter("can_edit_staff_notes")
    public void setCanEditStaffNotes(boolean canEditStaffNotes) {
        this.canEditStaffNotes = canEditStaffNotes;
    }

    /**
     * Getter for CanToggleTopicVisibility.
     * @return Returns the boolean
     */
    @JsonGetter("can_toggle_topic_visibility")
    public boolean getCanToggleTopicVisibility() {
        return canToggleTopicVisibility;
    }

    /**
     * Setter for CanToggleTopicVisibility.
     * @param canToggleTopicVisibility Value for boolean
     */
    @JsonSetter("can_toggle_topic_visibility")
    public void setCanToggleTopicVisibility(boolean canToggleTopicVisibility) {
        this.canToggleTopicVisibility = canToggleTopicVisibility;
    }

    /**
     * Getter for CanPinUnpinTopic.
     * @return Returns the boolean
     */
    @JsonGetter("can_pin_unpin_topic")
    public boolean getCanPinUnpinTopic() {
        return canPinUnpinTopic;
    }

    /**
     * Setter for CanPinUnpinTopic.
     * @param canPinUnpinTopic Value for boolean
     */
    @JsonSetter("can_pin_unpin_topic")
    public void setCanPinUnpinTopic(boolean canPinUnpinTopic) {
        this.canPinUnpinTopic = canPinUnpinTopic;
    }

    /**
     * Getter for CanBannerTopic.
     * @return Returns the Boolean
     */
    @JsonGetter("can_banner_topic")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getCanBannerTopic() {
        return canBannerTopic;
    }

    /**
     * Setter for CanBannerTopic.
     * @param canBannerTopic Value for Boolean
     */
    @JsonSetter("can_banner_topic")
    public void setCanBannerTopic(Boolean canBannerTopic) {
        this.canBannerTopic = canBannerTopic;
    }

    /**
     * Getter for CanModerateCategory.
     * @return Returns the boolean
     */
    @JsonGetter("can_moderate_category")
    public boolean getCanModerateCategory() {
        return canModerateCategory;
    }

    /**
     * Setter for CanModerateCategory.
     * @param canModerateCategory Value for boolean
     */
    @JsonSetter("can_moderate_category")
    public void setCanModerateCategory(boolean canModerateCategory) {
        this.canModerateCategory = canModerateCategory;
    }

    /**
     * Getter for CanRemoveSelfId.
     * @return Returns the int
     */
    @JsonGetter("can_remove_self_id")
    public int getCanRemoveSelfId() {
        return canRemoveSelfId;
    }

    /**
     * Setter for CanRemoveSelfId.
     * @param canRemoveSelfId Value for int
     */
    @JsonSetter("can_remove_self_id")
    public void setCanRemoveSelfId(int canRemoveSelfId) {
        this.canRemoveSelfId = canRemoveSelfId;
    }

    /**
     * Getter for Participants.
     * @return Returns the List of Participant1
     */
    @JsonGetter("participants")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Participant1> getParticipants() {
        return participants;
    }

    /**
     * Setter for Participants.
     * @param participants Value for List of Participant1
     */
    @JsonSetter("participants")
    public void setParticipants(List<Participant1> participants) {
        this.participants = participants;
    }

    /**
     * Getter for CreatedBy.
     * @return Returns the CreatedBy
     */
    @JsonGetter("created_by")
    public CreatedBy getCreatedBy() {
        return createdBy;
    }

    /**
     * Setter for CreatedBy.
     * @param createdBy Value for CreatedBy
     */
    @JsonSetter("created_by")
    public void setCreatedBy(CreatedBy createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for LastPoster.
     * @return Returns the LastPoster
     */
    @JsonGetter("last_poster")
    public LastPoster getLastPoster() {
        return lastPoster;
    }

    /**
     * Setter for LastPoster.
     * @param lastPoster Value for LastPoster
     */
    @JsonSetter("last_poster")
    public void setLastPoster(LastPoster lastPoster) {
        this.lastPoster = lastPoster;
    }

    /**
     * Converts this Details into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Details [" + "canEdit=" + canEdit + ", notificationLevel=" + notificationLevel
                + ", canMovePosts=" + canMovePosts + ", canDelete=" + canDelete
                + ", canRemoveAllowedUsers=" + canRemoveAllowedUsers + ", canCreatePost="
                + canCreatePost + ", canReplyAsNewTopic=" + canReplyAsNewTopic
                + ", canConvertTopic=" + canConvertTopic + ", canReviewTopic=" + canReviewTopic
                + ", canCloseTopic=" + canCloseTopic + ", canArchiveTopic=" + canArchiveTopic
                + ", canSplitMergeTopic=" + canSplitMergeTopic + ", canEditStaffNotes="
                + canEditStaffNotes + ", canToggleTopicVisibility=" + canToggleTopicVisibility
                + ", canPinUnpinTopic=" + canPinUnpinTopic + ", canModerateCategory="
                + canModerateCategory + ", canRemoveSelfId=" + canRemoveSelfId + ", createdBy="
                + createdBy + ", lastPoster=" + lastPoster + ", canInviteTo=" + canInviteTo
                + ", canInviteViaEmail=" + canInviteViaEmail + ", canFlagTopic=" + canFlagTopic
                + ", canBannerTopic=" + canBannerTopic + ", participants=" + participants + "]";
    }

    /**
     * Builds a new {@link Details.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Details.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(canEdit, notificationLevel, canMovePosts, canDelete,
                canRemoveAllowedUsers, canCreatePost, canReplyAsNewTopic, canConvertTopic,
                canReviewTopic, canCloseTopic, canArchiveTopic, canSplitMergeTopic,
                canEditStaffNotes, canToggleTopicVisibility, canPinUnpinTopic, canModerateCategory,
                canRemoveSelfId, createdBy, lastPoster)
                .canInviteTo(getCanInviteTo())
                .canInviteViaEmail(getCanInviteViaEmail())
                .canFlagTopic(getCanFlagTopic())
                .canBannerTopic(getCanBannerTopic())
                .participants(getParticipants());
        return builder;
    }

    /**
     * Class to build instances of {@link Details}.
     */
    public static class Builder {
        private boolean canEdit;
        private int notificationLevel;
        private boolean canMovePosts;
        private boolean canDelete;
        private boolean canRemoveAllowedUsers;
        private boolean canCreatePost;
        private boolean canReplyAsNewTopic;
        private boolean canConvertTopic;
        private boolean canReviewTopic;
        private boolean canCloseTopic;
        private boolean canArchiveTopic;
        private boolean canSplitMergeTopic;
        private boolean canEditStaffNotes;
        private boolean canToggleTopicVisibility;
        private boolean canPinUnpinTopic;
        private boolean canModerateCategory;
        private int canRemoveSelfId;
        private CreatedBy createdBy;
        private LastPoster lastPoster;
        private Boolean canInviteTo;
        private Boolean canInviteViaEmail;
        private Boolean canFlagTopic;
        private Boolean canBannerTopic;
        private List<Participant1> participants;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  canEdit  boolean value for canEdit.
         * @param  notificationLevel  int value for notificationLevel.
         * @param  canMovePosts  boolean value for canMovePosts.
         * @param  canDelete  boolean value for canDelete.
         * @param  canRemoveAllowedUsers  boolean value for canRemoveAllowedUsers.
         * @param  canCreatePost  boolean value for canCreatePost.
         * @param  canReplyAsNewTopic  boolean value for canReplyAsNewTopic.
         * @param  canConvertTopic  boolean value for canConvertTopic.
         * @param  canReviewTopic  boolean value for canReviewTopic.
         * @param  canCloseTopic  boolean value for canCloseTopic.
         * @param  canArchiveTopic  boolean value for canArchiveTopic.
         * @param  canSplitMergeTopic  boolean value for canSplitMergeTopic.
         * @param  canEditStaffNotes  boolean value for canEditStaffNotes.
         * @param  canToggleTopicVisibility  boolean value for canToggleTopicVisibility.
         * @param  canPinUnpinTopic  boolean value for canPinUnpinTopic.
         * @param  canModerateCategory  boolean value for canModerateCategory.
         * @param  canRemoveSelfId  int value for canRemoveSelfId.
         * @param  createdBy  CreatedBy value for createdBy.
         * @param  lastPoster  LastPoster value for lastPoster.
         */
        public Builder(boolean canEdit, int notificationLevel, boolean canMovePosts,
                boolean canDelete, boolean canRemoveAllowedUsers, boolean canCreatePost,
                boolean canReplyAsNewTopic, boolean canConvertTopic, boolean canReviewTopic,
                boolean canCloseTopic, boolean canArchiveTopic, boolean canSplitMergeTopic,
                boolean canEditStaffNotes, boolean canToggleTopicVisibility,
                boolean canPinUnpinTopic, boolean canModerateCategory, int canRemoveSelfId,
                CreatedBy createdBy, LastPoster lastPoster) {
            this.canEdit = canEdit;
            this.notificationLevel = notificationLevel;
            this.canMovePosts = canMovePosts;
            this.canDelete = canDelete;
            this.canRemoveAllowedUsers = canRemoveAllowedUsers;
            this.canCreatePost = canCreatePost;
            this.canReplyAsNewTopic = canReplyAsNewTopic;
            this.canConvertTopic = canConvertTopic;
            this.canReviewTopic = canReviewTopic;
            this.canCloseTopic = canCloseTopic;
            this.canArchiveTopic = canArchiveTopic;
            this.canSplitMergeTopic = canSplitMergeTopic;
            this.canEditStaffNotes = canEditStaffNotes;
            this.canToggleTopicVisibility = canToggleTopicVisibility;
            this.canPinUnpinTopic = canPinUnpinTopic;
            this.canModerateCategory = canModerateCategory;
            this.canRemoveSelfId = canRemoveSelfId;
            this.createdBy = createdBy;
            this.lastPoster = lastPoster;
        }

        /**
         * Setter for canEdit.
         * @param  canEdit  boolean value for canEdit.
         * @return Builder
         */
        public Builder canEdit(boolean canEdit) {
            this.canEdit = canEdit;
            return this;
        }

        /**
         * Setter for notificationLevel.
         * @param  notificationLevel  int value for notificationLevel.
         * @return Builder
         */
        public Builder notificationLevel(int notificationLevel) {
            this.notificationLevel = notificationLevel;
            return this;
        }

        /**
         * Setter for canMovePosts.
         * @param  canMovePosts  boolean value for canMovePosts.
         * @return Builder
         */
        public Builder canMovePosts(boolean canMovePosts) {
            this.canMovePosts = canMovePosts;
            return this;
        }

        /**
         * Setter for canDelete.
         * @param  canDelete  boolean value for canDelete.
         * @return Builder
         */
        public Builder canDelete(boolean canDelete) {
            this.canDelete = canDelete;
            return this;
        }

        /**
         * Setter for canRemoveAllowedUsers.
         * @param  canRemoveAllowedUsers  boolean value for canRemoveAllowedUsers.
         * @return Builder
         */
        public Builder canRemoveAllowedUsers(boolean canRemoveAllowedUsers) {
            this.canRemoveAllowedUsers = canRemoveAllowedUsers;
            return this;
        }

        /**
         * Setter for canCreatePost.
         * @param  canCreatePost  boolean value for canCreatePost.
         * @return Builder
         */
        public Builder canCreatePost(boolean canCreatePost) {
            this.canCreatePost = canCreatePost;
            return this;
        }

        /**
         * Setter for canReplyAsNewTopic.
         * @param  canReplyAsNewTopic  boolean value for canReplyAsNewTopic.
         * @return Builder
         */
        public Builder canReplyAsNewTopic(boolean canReplyAsNewTopic) {
            this.canReplyAsNewTopic = canReplyAsNewTopic;
            return this;
        }

        /**
         * Setter for canConvertTopic.
         * @param  canConvertTopic  boolean value for canConvertTopic.
         * @return Builder
         */
        public Builder canConvertTopic(boolean canConvertTopic) {
            this.canConvertTopic = canConvertTopic;
            return this;
        }

        /**
         * Setter for canReviewTopic.
         * @param  canReviewTopic  boolean value for canReviewTopic.
         * @return Builder
         */
        public Builder canReviewTopic(boolean canReviewTopic) {
            this.canReviewTopic = canReviewTopic;
            return this;
        }

        /**
         * Setter for canCloseTopic.
         * @param  canCloseTopic  boolean value for canCloseTopic.
         * @return Builder
         */
        public Builder canCloseTopic(boolean canCloseTopic) {
            this.canCloseTopic = canCloseTopic;
            return this;
        }

        /**
         * Setter for canArchiveTopic.
         * @param  canArchiveTopic  boolean value for canArchiveTopic.
         * @return Builder
         */
        public Builder canArchiveTopic(boolean canArchiveTopic) {
            this.canArchiveTopic = canArchiveTopic;
            return this;
        }

        /**
         * Setter for canSplitMergeTopic.
         * @param  canSplitMergeTopic  boolean value for canSplitMergeTopic.
         * @return Builder
         */
        public Builder canSplitMergeTopic(boolean canSplitMergeTopic) {
            this.canSplitMergeTopic = canSplitMergeTopic;
            return this;
        }

        /**
         * Setter for canEditStaffNotes.
         * @param  canEditStaffNotes  boolean value for canEditStaffNotes.
         * @return Builder
         */
        public Builder canEditStaffNotes(boolean canEditStaffNotes) {
            this.canEditStaffNotes = canEditStaffNotes;
            return this;
        }

        /**
         * Setter for canToggleTopicVisibility.
         * @param  canToggleTopicVisibility  boolean value for canToggleTopicVisibility.
         * @return Builder
         */
        public Builder canToggleTopicVisibility(boolean canToggleTopicVisibility) {
            this.canToggleTopicVisibility = canToggleTopicVisibility;
            return this;
        }

        /**
         * Setter for canPinUnpinTopic.
         * @param  canPinUnpinTopic  boolean value for canPinUnpinTopic.
         * @return Builder
         */
        public Builder canPinUnpinTopic(boolean canPinUnpinTopic) {
            this.canPinUnpinTopic = canPinUnpinTopic;
            return this;
        }

        /**
         * Setter for canModerateCategory.
         * @param  canModerateCategory  boolean value for canModerateCategory.
         * @return Builder
         */
        public Builder canModerateCategory(boolean canModerateCategory) {
            this.canModerateCategory = canModerateCategory;
            return this;
        }

        /**
         * Setter for canRemoveSelfId.
         * @param  canRemoveSelfId  int value for canRemoveSelfId.
         * @return Builder
         */
        public Builder canRemoveSelfId(int canRemoveSelfId) {
            this.canRemoveSelfId = canRemoveSelfId;
            return this;
        }

        /**
         * Setter for createdBy.
         * @param  createdBy  CreatedBy value for createdBy.
         * @return Builder
         */
        public Builder createdBy(CreatedBy createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        /**
         * Setter for lastPoster.
         * @param  lastPoster  LastPoster value for lastPoster.
         * @return Builder
         */
        public Builder lastPoster(LastPoster lastPoster) {
            this.lastPoster = lastPoster;
            return this;
        }

        /**
         * Setter for canInviteTo.
         * @param  canInviteTo  Boolean value for canInviteTo.
         * @return Builder
         */
        public Builder canInviteTo(Boolean canInviteTo) {
            this.canInviteTo = canInviteTo;
            return this;
        }

        /**
         * Setter for canInviteViaEmail.
         * @param  canInviteViaEmail  Boolean value for canInviteViaEmail.
         * @return Builder
         */
        public Builder canInviteViaEmail(Boolean canInviteViaEmail) {
            this.canInviteViaEmail = canInviteViaEmail;
            return this;
        }

        /**
         * Setter for canFlagTopic.
         * @param  canFlagTopic  Boolean value for canFlagTopic.
         * @return Builder
         */
        public Builder canFlagTopic(Boolean canFlagTopic) {
            this.canFlagTopic = canFlagTopic;
            return this;
        }

        /**
         * Setter for canBannerTopic.
         * @param  canBannerTopic  Boolean value for canBannerTopic.
         * @return Builder
         */
        public Builder canBannerTopic(Boolean canBannerTopic) {
            this.canBannerTopic = canBannerTopic;
            return this;
        }

        /**
         * Setter for participants.
         * @param  participants  List of Participant1 value for participants.
         * @return Builder
         */
        public Builder participants(List<Participant1> participants) {
            this.participants = participants;
            return this;
        }

        /**
         * Builds a new {@link Details} object using the set fields.
         * @return {@link Details}
         */
        public Details build() {
            return new Details(canEdit, notificationLevel, canMovePosts, canDelete,
                    canRemoveAllowedUsers, canCreatePost, canReplyAsNewTopic, canConvertTopic,
                    canReviewTopic, canCloseTopic, canArchiveTopic, canSplitMergeTopic,
                    canEditStaffNotes, canToggleTopicVisibility, canPinUnpinTopic,
                    canModerateCategory, canRemoveSelfId, createdBy, lastPoster, canInviteTo,
                    canInviteViaEmail, canFlagTopic, canBannerTopic, participants);
        }
    }
}
