/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Extras2 type.
 */
public class Extras2 {
    private List<Object> typeFilters;

    /**
     * Default constructor.
     */
    public Extras2() {
    }

    /**
     * Initialization constructor.
     * @param  typeFilters  List of Object value for typeFilters.
     */
    public Extras2(
            List<Object> typeFilters) {
        this.typeFilters = typeFilters;
    }

    /**
     * Getter for TypeFilters.
     * @return Returns the List of Object
     */
    @JsonGetter("type_filters")
    public List<Object> getTypeFilters() {
        return typeFilters;
    }

    /**
     * Setter for TypeFilters.
     * @param typeFilters Value for List of Object
     */
    @JsonSetter("type_filters")
    public void setTypeFilters(List<Object> typeFilters) {
        this.typeFilters = typeFilters;
    }

    /**
     * Converts this Extras2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Extras2 [" + "typeFilters=" + typeFilters + "]";
    }

    /**
     * Builds a new {@link Extras2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Extras2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(typeFilters);
        return builder;
    }

    /**
     * Class to build instances of {@link Extras2}.
     */
    public static class Builder {
        private List<Object> typeFilters;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  typeFilters  List of Object value for typeFilters.
         */
        public Builder(List<Object> typeFilters) {
            this.typeFilters = typeFilters;
        }

        /**
         * Setter for typeFilters.
         * @param  typeFilters  List of Object value for typeFilters.
         * @return Builder
         */
        public Builder typeFilters(List<Object> typeFilters) {
            this.typeFilters = typeFilters;
            return this;
        }

        /**
         * Builds a new {@link Extras2} object using the set fields.
         * @return {@link Extras2}
         */
        public Extras2 build() {
            return new Extras2(typeFilters);
        }
    }
}
