/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for FeaturedTopic type.
 */
public class FeaturedTopic {
    private int id;
    private String title;
    private String fancyTitle;
    private String slug;
    private int postsCount;

    /**
     * Default constructor.
     */
    public FeaturedTopic() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  title  String value for title.
     * @param  fancyTitle  String value for fancyTitle.
     * @param  slug  String value for slug.
     * @param  postsCount  int value for postsCount.
     */
    public FeaturedTopic(
            int id,
            String title,
            String fancyTitle,
            String slug,
            int postsCount) {
        this.id = id;
        this.title = title;
        this.fancyTitle = fancyTitle;
        this.slug = slug;
        this.postsCount = postsCount;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for FancyTitle.
     * @return Returns the String
     */
    @JsonGetter("fancy_title")
    public String getFancyTitle() {
        return fancyTitle;
    }

    /**
     * Setter for FancyTitle.
     * @param fancyTitle Value for String
     */
    @JsonSetter("fancy_title")
    public void setFancyTitle(String fancyTitle) {
        this.fancyTitle = fancyTitle;
    }

    /**
     * Getter for Slug.
     * @return Returns the String
     */
    @JsonGetter("slug")
    public String getSlug() {
        return slug;
    }

    /**
     * Setter for Slug.
     * @param slug Value for String
     */
    @JsonSetter("slug")
    public void setSlug(String slug) {
        this.slug = slug;
    }

    /**
     * Getter for PostsCount.
     * @return Returns the int
     */
    @JsonGetter("posts_count")
    public int getPostsCount() {
        return postsCount;
    }

    /**
     * Setter for PostsCount.
     * @param postsCount Value for int
     */
    @JsonSetter("posts_count")
    public void setPostsCount(int postsCount) {
        this.postsCount = postsCount;
    }

    /**
     * Converts this FeaturedTopic into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FeaturedTopic [" + "id=" + id + ", title=" + title + ", fancyTitle=" + fancyTitle
                + ", slug=" + slug + ", postsCount=" + postsCount + "]";
    }

    /**
     * Builds a new {@link FeaturedTopic.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FeaturedTopic.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, title, fancyTitle, slug, postsCount);
        return builder;
    }

    /**
     * Class to build instances of {@link FeaturedTopic}.
     */
    public static class Builder {
        private int id;
        private String title;
        private String fancyTitle;
        private String slug;
        private int postsCount;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  title  String value for title.
         * @param  fancyTitle  String value for fancyTitle.
         * @param  slug  String value for slug.
         * @param  postsCount  int value for postsCount.
         */
        public Builder(int id, String title, String fancyTitle, String slug, int postsCount) {
            this.id = id;
            this.title = title;
            this.fancyTitle = fancyTitle;
            this.slug = slug;
            this.postsCount = postsCount;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for fancyTitle.
         * @param  fancyTitle  String value for fancyTitle.
         * @return Builder
         */
        public Builder fancyTitle(String fancyTitle) {
            this.fancyTitle = fancyTitle;
            return this;
        }

        /**
         * Setter for slug.
         * @param  slug  String value for slug.
         * @return Builder
         */
        public Builder slug(String slug) {
            this.slug = slug;
            return this;
        }

        /**
         * Setter for postsCount.
         * @param  postsCount  int value for postsCount.
         * @return Builder
         */
        public Builder postsCount(int postsCount) {
            this.postsCount = postsCount;
            return this;
        }

        /**
         * Builds a new {@link FeaturedTopic} object using the set fields.
         * @return {@link FeaturedTopic}
         */
        public FeaturedTopic build() {
            return new FeaturedTopic(id, title, fancyTitle, slug, postsCount);
        }
    }
}
