/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for Group10 type.
 */
public class Group10 {
    private int id;
    private boolean automatic;
    private String name;
    private String displayName;
    private int userCount;
    private int mentionableLevel;
    private int messageableLevel;
    private int visibilityLevel;
    private boolean primaryGroup;
    private String title;
    private String grantTrustLevel;
    private String incomingEmail;
    private boolean hasMessages;
    private String flairUrl;
    private String flairBgColor;
    private String flairColor;
    private OptionalNullable<Integer> flairGroupId;
    private String bioRaw;
    private String bioCooked;
    private String bioExcerpt;
    private boolean publicAdmission;
    private boolean publicExit;
    private boolean allowMembershipRequests;
    private String fullName;
    private int defaultNotificationLevel;
    private String membershipRequestTemplate;
    private int membersVisibilityLevel;
    private boolean canSeeMembers;
    private boolean canAdminGroup;
    private boolean publishReadState;

    /**
     * Default constructor.
     */
    public Group10() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  automatic  boolean value for automatic.
     * @param  name  String value for name.
     * @param  displayName  String value for displayName.
     * @param  userCount  int value for userCount.
     * @param  mentionableLevel  int value for mentionableLevel.
     * @param  messageableLevel  int value for messageableLevel.
     * @param  visibilityLevel  int value for visibilityLevel.
     * @param  primaryGroup  boolean value for primaryGroup.
     * @param  title  String value for title.
     * @param  grantTrustLevel  String value for grantTrustLevel.
     * @param  incomingEmail  String value for incomingEmail.
     * @param  hasMessages  boolean value for hasMessages.
     * @param  flairUrl  String value for flairUrl.
     * @param  flairBgColor  String value for flairBgColor.
     * @param  flairColor  String value for flairColor.
     * @param  bioRaw  String value for bioRaw.
     * @param  bioCooked  String value for bioCooked.
     * @param  bioExcerpt  String value for bioExcerpt.
     * @param  publicAdmission  boolean value for publicAdmission.
     * @param  publicExit  boolean value for publicExit.
     * @param  allowMembershipRequests  boolean value for allowMembershipRequests.
     * @param  fullName  String value for fullName.
     * @param  defaultNotificationLevel  int value for defaultNotificationLevel.
     * @param  membershipRequestTemplate  String value for membershipRequestTemplate.
     * @param  membersVisibilityLevel  int value for membersVisibilityLevel.
     * @param  canSeeMembers  boolean value for canSeeMembers.
     * @param  canAdminGroup  boolean value for canAdminGroup.
     * @param  publishReadState  boolean value for publishReadState.
     * @param  flairGroupId  Integer value for flairGroupId.
     */
    public Group10(
            int id,
            boolean automatic,
            String name,
            String displayName,
            int userCount,
            int mentionableLevel,
            int messageableLevel,
            int visibilityLevel,
            boolean primaryGroup,
            String title,
            String grantTrustLevel,
            String incomingEmail,
            boolean hasMessages,
            String flairUrl,
            String flairBgColor,
            String flairColor,
            String bioRaw,
            String bioCooked,
            String bioExcerpt,
            boolean publicAdmission,
            boolean publicExit,
            boolean allowMembershipRequests,
            String fullName,
            int defaultNotificationLevel,
            String membershipRequestTemplate,
            int membersVisibilityLevel,
            boolean canSeeMembers,
            boolean canAdminGroup,
            boolean publishReadState,
            Integer flairGroupId) {
        this.id = id;
        this.automatic = automatic;
        this.name = name;
        this.displayName = displayName;
        this.userCount = userCount;
        this.mentionableLevel = mentionableLevel;
        this.messageableLevel = messageableLevel;
        this.visibilityLevel = visibilityLevel;
        this.primaryGroup = primaryGroup;
        this.title = title;
        this.grantTrustLevel = grantTrustLevel;
        this.incomingEmail = incomingEmail;
        this.hasMessages = hasMessages;
        this.flairUrl = flairUrl;
        this.flairBgColor = flairBgColor;
        this.flairColor = flairColor;
        this.flairGroupId = OptionalNullable.of(flairGroupId);
        this.bioRaw = bioRaw;
        this.bioCooked = bioCooked;
        this.bioExcerpt = bioExcerpt;
        this.publicAdmission = publicAdmission;
        this.publicExit = publicExit;
        this.allowMembershipRequests = allowMembershipRequests;
        this.fullName = fullName;
        this.defaultNotificationLevel = defaultNotificationLevel;
        this.membershipRequestTemplate = membershipRequestTemplate;
        this.membersVisibilityLevel = membersVisibilityLevel;
        this.canSeeMembers = canSeeMembers;
        this.canAdminGroup = canAdminGroup;
        this.publishReadState = publishReadState;
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  automatic  boolean value for automatic.
     * @param  name  String value for name.
     * @param  displayName  String value for displayName.
     * @param  userCount  int value for userCount.
     * @param  mentionableLevel  int value for mentionableLevel.
     * @param  messageableLevel  int value for messageableLevel.
     * @param  visibilityLevel  int value for visibilityLevel.
     * @param  primaryGroup  boolean value for primaryGroup.
     * @param  title  String value for title.
     * @param  grantTrustLevel  String value for grantTrustLevel.
     * @param  incomingEmail  String value for incomingEmail.
     * @param  hasMessages  boolean value for hasMessages.
     * @param  flairUrl  String value for flairUrl.
     * @param  flairBgColor  String value for flairBgColor.
     * @param  flairColor  String value for flairColor.
     * @param  bioRaw  String value for bioRaw.
     * @param  bioCooked  String value for bioCooked.
     * @param  bioExcerpt  String value for bioExcerpt.
     * @param  publicAdmission  boolean value for publicAdmission.
     * @param  publicExit  boolean value for publicExit.
     * @param  allowMembershipRequests  boolean value for allowMembershipRequests.
     * @param  fullName  String value for fullName.
     * @param  defaultNotificationLevel  int value for defaultNotificationLevel.
     * @param  membershipRequestTemplate  String value for membershipRequestTemplate.
     * @param  membersVisibilityLevel  int value for membersVisibilityLevel.
     * @param  canSeeMembers  boolean value for canSeeMembers.
     * @param  canAdminGroup  boolean value for canAdminGroup.
     * @param  publishReadState  boolean value for publishReadState.
     * @param  flairGroupId  Integer value for flairGroupId.
     */

    protected Group10(int id, boolean automatic, String name, String displayName, int userCount,
            int mentionableLevel, int messageableLevel, int visibilityLevel, boolean primaryGroup,
            String title, String grantTrustLevel, String incomingEmail, boolean hasMessages,
            String flairUrl, String flairBgColor, String flairColor, String bioRaw,
            String bioCooked, String bioExcerpt, boolean publicAdmission, boolean publicExit,
            boolean allowMembershipRequests, String fullName, int defaultNotificationLevel,
            String membershipRequestTemplate, int membersVisibilityLevel, boolean canSeeMembers,
            boolean canAdminGroup, boolean publishReadState,
            OptionalNullable<Integer> flairGroupId) {
        this.id = id;
        this.automatic = automatic;
        this.name = name;
        this.displayName = displayName;
        this.userCount = userCount;
        this.mentionableLevel = mentionableLevel;
        this.messageableLevel = messageableLevel;
        this.visibilityLevel = visibilityLevel;
        this.primaryGroup = primaryGroup;
        this.title = title;
        this.grantTrustLevel = grantTrustLevel;
        this.incomingEmail = incomingEmail;
        this.hasMessages = hasMessages;
        this.flairUrl = flairUrl;
        this.flairBgColor = flairBgColor;
        this.flairColor = flairColor;
        this.flairGroupId = flairGroupId;
        this.bioRaw = bioRaw;
        this.bioCooked = bioCooked;
        this.bioExcerpt = bioExcerpt;
        this.publicAdmission = publicAdmission;
        this.publicExit = publicExit;
        this.allowMembershipRequests = allowMembershipRequests;
        this.fullName = fullName;
        this.defaultNotificationLevel = defaultNotificationLevel;
        this.membershipRequestTemplate = membershipRequestTemplate;
        this.membersVisibilityLevel = membersVisibilityLevel;
        this.canSeeMembers = canSeeMembers;
        this.canAdminGroup = canAdminGroup;
        this.publishReadState = publishReadState;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for Automatic.
     * @return Returns the boolean
     */
    @JsonGetter("automatic")
    public boolean getAutomatic() {
        return automatic;
    }

    /**
     * Setter for Automatic.
     * @param automatic Value for boolean
     */
    @JsonSetter("automatic")
    public void setAutomatic(boolean automatic) {
        this.automatic = automatic;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for DisplayName.
     * @return Returns the String
     */
    @JsonGetter("display_name")
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Setter for DisplayName.
     * @param displayName Value for String
     */
    @JsonSetter("display_name")
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Getter for UserCount.
     * @return Returns the int
     */
    @JsonGetter("user_count")
    public int getUserCount() {
        return userCount;
    }

    /**
     * Setter for UserCount.
     * @param userCount Value for int
     */
    @JsonSetter("user_count")
    public void setUserCount(int userCount) {
        this.userCount = userCount;
    }

    /**
     * Getter for MentionableLevel.
     * @return Returns the int
     */
    @JsonGetter("mentionable_level")
    public int getMentionableLevel() {
        return mentionableLevel;
    }

    /**
     * Setter for MentionableLevel.
     * @param mentionableLevel Value for int
     */
    @JsonSetter("mentionable_level")
    public void setMentionableLevel(int mentionableLevel) {
        this.mentionableLevel = mentionableLevel;
    }

    /**
     * Getter for MessageableLevel.
     * @return Returns the int
     */
    @JsonGetter("messageable_level")
    public int getMessageableLevel() {
        return messageableLevel;
    }

    /**
     * Setter for MessageableLevel.
     * @param messageableLevel Value for int
     */
    @JsonSetter("messageable_level")
    public void setMessageableLevel(int messageableLevel) {
        this.messageableLevel = messageableLevel;
    }

    /**
     * Getter for VisibilityLevel.
     * @return Returns the int
     */
    @JsonGetter("visibility_level")
    public int getVisibilityLevel() {
        return visibilityLevel;
    }

    /**
     * Setter for VisibilityLevel.
     * @param visibilityLevel Value for int
     */
    @JsonSetter("visibility_level")
    public void setVisibilityLevel(int visibilityLevel) {
        this.visibilityLevel = visibilityLevel;
    }

    /**
     * Getter for PrimaryGroup.
     * @return Returns the boolean
     */
    @JsonGetter("primary_group")
    public boolean getPrimaryGroup() {
        return primaryGroup;
    }

    /**
     * Setter for PrimaryGroup.
     * @param primaryGroup Value for boolean
     */
    @JsonSetter("primary_group")
    public void setPrimaryGroup(boolean primaryGroup) {
        this.primaryGroup = primaryGroup;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for GrantTrustLevel.
     * @return Returns the String
     */
    @JsonGetter("grant_trust_level")
    public String getGrantTrustLevel() {
        return grantTrustLevel;
    }

    /**
     * Setter for GrantTrustLevel.
     * @param grantTrustLevel Value for String
     */
    @JsonSetter("grant_trust_level")
    public void setGrantTrustLevel(String grantTrustLevel) {
        this.grantTrustLevel = grantTrustLevel;
    }

    /**
     * Getter for IncomingEmail.
     * @return Returns the String
     */
    @JsonGetter("incoming_email")
    public String getIncomingEmail() {
        return incomingEmail;
    }

    /**
     * Setter for IncomingEmail.
     * @param incomingEmail Value for String
     */
    @JsonSetter("incoming_email")
    public void setIncomingEmail(String incomingEmail) {
        this.incomingEmail = incomingEmail;
    }

    /**
     * Getter for HasMessages.
     * @return Returns the boolean
     */
    @JsonGetter("has_messages")
    public boolean getHasMessages() {
        return hasMessages;
    }

    /**
     * Setter for HasMessages.
     * @param hasMessages Value for boolean
     */
    @JsonSetter("has_messages")
    public void setHasMessages(boolean hasMessages) {
        this.hasMessages = hasMessages;
    }

    /**
     * Getter for FlairUrl.
     * @return Returns the String
     */
    @JsonGetter("flair_url")
    public String getFlairUrl() {
        return flairUrl;
    }

    /**
     * Setter for FlairUrl.
     * @param flairUrl Value for String
     */
    @JsonSetter("flair_url")
    public void setFlairUrl(String flairUrl) {
        this.flairUrl = flairUrl;
    }

    /**
     * Getter for FlairBgColor.
     * @return Returns the String
     */
    @JsonGetter("flair_bg_color")
    public String getFlairBgColor() {
        return flairBgColor;
    }

    /**
     * Setter for FlairBgColor.
     * @param flairBgColor Value for String
     */
    @JsonSetter("flair_bg_color")
    public void setFlairBgColor(String flairBgColor) {
        this.flairBgColor = flairBgColor;
    }

    /**
     * Getter for FlairColor.
     * @return Returns the String
     */
    @JsonGetter("flair_color")
    public String getFlairColor() {
        return flairColor;
    }

    /**
     * Setter for FlairColor.
     * @param flairColor Value for String
     */
    @JsonSetter("flair_color")
    public void setFlairColor(String flairColor) {
        this.flairColor = flairColor;
    }

    /**
     * Internal Getter for FlairGroupId.
     * @return Returns the Internal Integer
     */
    @JsonGetter("flair_group_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetFlairGroupId() {
        return this.flairGroupId;
    }

    /**
     * Getter for FlairGroupId.
     * @return Returns the Integer
     */
    public Integer getFlairGroupId() {
        return OptionalNullable.getFrom(flairGroupId);
    }

    /**
     * Setter for FlairGroupId.
     * @param flairGroupId Value for Integer
     */
    @JsonSetter("flair_group_id")
    public void setFlairGroupId(Integer flairGroupId) {
        this.flairGroupId = OptionalNullable.of(flairGroupId);
    }

    /**
     * UnSetter for FlairGroupId.
     */
    public void unsetFlairGroupId() {
        flairGroupId = null;
    }

    /**
     * Getter for BioRaw.
     * @return Returns the String
     */
    @JsonGetter("bio_raw")
    public String getBioRaw() {
        return bioRaw;
    }

    /**
     * Setter for BioRaw.
     * @param bioRaw Value for String
     */
    @JsonSetter("bio_raw")
    public void setBioRaw(String bioRaw) {
        this.bioRaw = bioRaw;
    }

    /**
     * Getter for BioCooked.
     * @return Returns the String
     */
    @JsonGetter("bio_cooked")
    public String getBioCooked() {
        return bioCooked;
    }

    /**
     * Setter for BioCooked.
     * @param bioCooked Value for String
     */
    @JsonSetter("bio_cooked")
    public void setBioCooked(String bioCooked) {
        this.bioCooked = bioCooked;
    }

    /**
     * Getter for BioExcerpt.
     * @return Returns the String
     */
    @JsonGetter("bio_excerpt")
    public String getBioExcerpt() {
        return bioExcerpt;
    }

    /**
     * Setter for BioExcerpt.
     * @param bioExcerpt Value for String
     */
    @JsonSetter("bio_excerpt")
    public void setBioExcerpt(String bioExcerpt) {
        this.bioExcerpt = bioExcerpt;
    }

    /**
     * Getter for PublicAdmission.
     * @return Returns the boolean
     */
    @JsonGetter("public_admission")
    public boolean getPublicAdmission() {
        return publicAdmission;
    }

    /**
     * Setter for PublicAdmission.
     * @param publicAdmission Value for boolean
     */
    @JsonSetter("public_admission")
    public void setPublicAdmission(boolean publicAdmission) {
        this.publicAdmission = publicAdmission;
    }

    /**
     * Getter for PublicExit.
     * @return Returns the boolean
     */
    @JsonGetter("public_exit")
    public boolean getPublicExit() {
        return publicExit;
    }

    /**
     * Setter for PublicExit.
     * @param publicExit Value for boolean
     */
    @JsonSetter("public_exit")
    public void setPublicExit(boolean publicExit) {
        this.publicExit = publicExit;
    }

    /**
     * Getter for AllowMembershipRequests.
     * @return Returns the boolean
     */
    @JsonGetter("allow_membership_requests")
    public boolean getAllowMembershipRequests() {
        return allowMembershipRequests;
    }

    /**
     * Setter for AllowMembershipRequests.
     * @param allowMembershipRequests Value for boolean
     */
    @JsonSetter("allow_membership_requests")
    public void setAllowMembershipRequests(boolean allowMembershipRequests) {
        this.allowMembershipRequests = allowMembershipRequests;
    }

    /**
     * Getter for FullName.
     * @return Returns the String
     */
    @JsonGetter("full_name")
    public String getFullName() {
        return fullName;
    }

    /**
     * Setter for FullName.
     * @param fullName Value for String
     */
    @JsonSetter("full_name")
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for DefaultNotificationLevel.
     * @return Returns the int
     */
    @JsonGetter("default_notification_level")
    public int getDefaultNotificationLevel() {
        return defaultNotificationLevel;
    }

    /**
     * Setter for DefaultNotificationLevel.
     * @param defaultNotificationLevel Value for int
     */
    @JsonSetter("default_notification_level")
    public void setDefaultNotificationLevel(int defaultNotificationLevel) {
        this.defaultNotificationLevel = defaultNotificationLevel;
    }

    /**
     * Getter for MembershipRequestTemplate.
     * @return Returns the String
     */
    @JsonGetter("membership_request_template")
    public String getMembershipRequestTemplate() {
        return membershipRequestTemplate;
    }

    /**
     * Setter for MembershipRequestTemplate.
     * @param membershipRequestTemplate Value for String
     */
    @JsonSetter("membership_request_template")
    public void setMembershipRequestTemplate(String membershipRequestTemplate) {
        this.membershipRequestTemplate = membershipRequestTemplate;
    }

    /**
     * Getter for MembersVisibilityLevel.
     * @return Returns the int
     */
    @JsonGetter("members_visibility_level")
    public int getMembersVisibilityLevel() {
        return membersVisibilityLevel;
    }

    /**
     * Setter for MembersVisibilityLevel.
     * @param membersVisibilityLevel Value for int
     */
    @JsonSetter("members_visibility_level")
    public void setMembersVisibilityLevel(int membersVisibilityLevel) {
        this.membersVisibilityLevel = membersVisibilityLevel;
    }

    /**
     * Getter for CanSeeMembers.
     * @return Returns the boolean
     */
    @JsonGetter("can_see_members")
    public boolean getCanSeeMembers() {
        return canSeeMembers;
    }

    /**
     * Setter for CanSeeMembers.
     * @param canSeeMembers Value for boolean
     */
    @JsonSetter("can_see_members")
    public void setCanSeeMembers(boolean canSeeMembers) {
        this.canSeeMembers = canSeeMembers;
    }

    /**
     * Getter for CanAdminGroup.
     * @return Returns the boolean
     */
    @JsonGetter("can_admin_group")
    public boolean getCanAdminGroup() {
        return canAdminGroup;
    }

    /**
     * Setter for CanAdminGroup.
     * @param canAdminGroup Value for boolean
     */
    @JsonSetter("can_admin_group")
    public void setCanAdminGroup(boolean canAdminGroup) {
        this.canAdminGroup = canAdminGroup;
    }

    /**
     * Getter for PublishReadState.
     * @return Returns the boolean
     */
    @JsonGetter("publish_read_state")
    public boolean getPublishReadState() {
        return publishReadState;
    }

    /**
     * Setter for PublishReadState.
     * @param publishReadState Value for boolean
     */
    @JsonSetter("publish_read_state")
    public void setPublishReadState(boolean publishReadState) {
        this.publishReadState = publishReadState;
    }

    /**
     * Converts this Group10 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Group10 [" + "id=" + id + ", automatic=" + automatic + ", name=" + name
                + ", displayName=" + displayName + ", userCount=" + userCount
                + ", mentionableLevel=" + mentionableLevel + ", messageableLevel="
                + messageableLevel + ", visibilityLevel=" + visibilityLevel + ", primaryGroup="
                + primaryGroup + ", title=" + title + ", grantTrustLevel=" + grantTrustLevel
                + ", incomingEmail=" + incomingEmail + ", hasMessages=" + hasMessages
                + ", flairUrl=" + flairUrl + ", flairBgColor=" + flairBgColor + ", flairColor="
                + flairColor + ", bioRaw=" + bioRaw + ", bioCooked=" + bioCooked + ", bioExcerpt="
                + bioExcerpt + ", publicAdmission=" + publicAdmission + ", publicExit=" + publicExit
                + ", allowMembershipRequests=" + allowMembershipRequests + ", fullName=" + fullName
                + ", defaultNotificationLevel=" + defaultNotificationLevel
                + ", membershipRequestTemplate=" + membershipRequestTemplate
                + ", membersVisibilityLevel=" + membersVisibilityLevel + ", canSeeMembers="
                + canSeeMembers + ", canAdminGroup=" + canAdminGroup + ", publishReadState="
                + publishReadState + ", flairGroupId=" + flairGroupId + "]";
    }

    /**
     * Builds a new {@link Group10.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Group10.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, automatic, name, displayName, userCount, mentionableLevel,
                messageableLevel, visibilityLevel, primaryGroup, title, grantTrustLevel,
                incomingEmail, hasMessages, flairUrl, flairBgColor, flairColor, bioRaw, bioCooked,
                bioExcerpt, publicAdmission, publicExit, allowMembershipRequests, fullName,
                defaultNotificationLevel, membershipRequestTemplate, membersVisibilityLevel,
                canSeeMembers, canAdminGroup, publishReadState);
        builder.flairGroupId = internalGetFlairGroupId();
        return builder;
    }

    /**
     * Class to build instances of {@link Group10}.
     */
    public static class Builder {
        private int id;
        private boolean automatic;
        private String name;
        private String displayName;
        private int userCount;
        private int mentionableLevel;
        private int messageableLevel;
        private int visibilityLevel;
        private boolean primaryGroup;
        private String title;
        private String grantTrustLevel;
        private String incomingEmail;
        private boolean hasMessages;
        private String flairUrl;
        private String flairBgColor;
        private String flairColor;
        private String bioRaw;
        private String bioCooked;
        private String bioExcerpt;
        private boolean publicAdmission;
        private boolean publicExit;
        private boolean allowMembershipRequests;
        private String fullName;
        private int defaultNotificationLevel;
        private String membershipRequestTemplate;
        private int membersVisibilityLevel;
        private boolean canSeeMembers;
        private boolean canAdminGroup;
        private boolean publishReadState;
        private OptionalNullable<Integer> flairGroupId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  automatic  boolean value for automatic.
         * @param  name  String value for name.
         * @param  displayName  String value for displayName.
         * @param  userCount  int value for userCount.
         * @param  mentionableLevel  int value for mentionableLevel.
         * @param  messageableLevel  int value for messageableLevel.
         * @param  visibilityLevel  int value for visibilityLevel.
         * @param  primaryGroup  boolean value for primaryGroup.
         * @param  title  String value for title.
         * @param  grantTrustLevel  String value for grantTrustLevel.
         * @param  incomingEmail  String value for incomingEmail.
         * @param  hasMessages  boolean value for hasMessages.
         * @param  flairUrl  String value for flairUrl.
         * @param  flairBgColor  String value for flairBgColor.
         * @param  flairColor  String value for flairColor.
         * @param  bioRaw  String value for bioRaw.
         * @param  bioCooked  String value for bioCooked.
         * @param  bioExcerpt  String value for bioExcerpt.
         * @param  publicAdmission  boolean value for publicAdmission.
         * @param  publicExit  boolean value for publicExit.
         * @param  allowMembershipRequests  boolean value for allowMembershipRequests.
         * @param  fullName  String value for fullName.
         * @param  defaultNotificationLevel  int value for defaultNotificationLevel.
         * @param  membershipRequestTemplate  String value for membershipRequestTemplate.
         * @param  membersVisibilityLevel  int value for membersVisibilityLevel.
         * @param  canSeeMembers  boolean value for canSeeMembers.
         * @param  canAdminGroup  boolean value for canAdminGroup.
         * @param  publishReadState  boolean value for publishReadState.
         */
        public Builder(int id, boolean automatic, String name, String displayName, int userCount,
                int mentionableLevel, int messageableLevel, int visibilityLevel,
                boolean primaryGroup, String title, String grantTrustLevel, String incomingEmail,
                boolean hasMessages, String flairUrl, String flairBgColor, String flairColor,
                String bioRaw, String bioCooked, String bioExcerpt, boolean publicAdmission,
                boolean publicExit, boolean allowMembershipRequests, String fullName,
                int defaultNotificationLevel, String membershipRequestTemplate,
                int membersVisibilityLevel, boolean canSeeMembers, boolean canAdminGroup,
                boolean publishReadState) {
            this.id = id;
            this.automatic = automatic;
            this.name = name;
            this.displayName = displayName;
            this.userCount = userCount;
            this.mentionableLevel = mentionableLevel;
            this.messageableLevel = messageableLevel;
            this.visibilityLevel = visibilityLevel;
            this.primaryGroup = primaryGroup;
            this.title = title;
            this.grantTrustLevel = grantTrustLevel;
            this.incomingEmail = incomingEmail;
            this.hasMessages = hasMessages;
            this.flairUrl = flairUrl;
            this.flairBgColor = flairBgColor;
            this.flairColor = flairColor;
            this.bioRaw = bioRaw;
            this.bioCooked = bioCooked;
            this.bioExcerpt = bioExcerpt;
            this.publicAdmission = publicAdmission;
            this.publicExit = publicExit;
            this.allowMembershipRequests = allowMembershipRequests;
            this.fullName = fullName;
            this.defaultNotificationLevel = defaultNotificationLevel;
            this.membershipRequestTemplate = membershipRequestTemplate;
            this.membersVisibilityLevel = membersVisibilityLevel;
            this.canSeeMembers = canSeeMembers;
            this.canAdminGroup = canAdminGroup;
            this.publishReadState = publishReadState;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for automatic.
         * @param  automatic  boolean value for automatic.
         * @return Builder
         */
        public Builder automatic(boolean automatic) {
            this.automatic = automatic;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for displayName.
         * @param  displayName  String value for displayName.
         * @return Builder
         */
        public Builder displayName(String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Setter for userCount.
         * @param  userCount  int value for userCount.
         * @return Builder
         */
        public Builder userCount(int userCount) {
            this.userCount = userCount;
            return this;
        }

        /**
         * Setter for mentionableLevel.
         * @param  mentionableLevel  int value for mentionableLevel.
         * @return Builder
         */
        public Builder mentionableLevel(int mentionableLevel) {
            this.mentionableLevel = mentionableLevel;
            return this;
        }

        /**
         * Setter for messageableLevel.
         * @param  messageableLevel  int value for messageableLevel.
         * @return Builder
         */
        public Builder messageableLevel(int messageableLevel) {
            this.messageableLevel = messageableLevel;
            return this;
        }

        /**
         * Setter for visibilityLevel.
         * @param  visibilityLevel  int value for visibilityLevel.
         * @return Builder
         */
        public Builder visibilityLevel(int visibilityLevel) {
            this.visibilityLevel = visibilityLevel;
            return this;
        }

        /**
         * Setter for primaryGroup.
         * @param  primaryGroup  boolean value for primaryGroup.
         * @return Builder
         */
        public Builder primaryGroup(boolean primaryGroup) {
            this.primaryGroup = primaryGroup;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for grantTrustLevel.
         * @param  grantTrustLevel  String value for grantTrustLevel.
         * @return Builder
         */
        public Builder grantTrustLevel(String grantTrustLevel) {
            this.grantTrustLevel = grantTrustLevel;
            return this;
        }

        /**
         * Setter for incomingEmail.
         * @param  incomingEmail  String value for incomingEmail.
         * @return Builder
         */
        public Builder incomingEmail(String incomingEmail) {
            this.incomingEmail = incomingEmail;
            return this;
        }

        /**
         * Setter for hasMessages.
         * @param  hasMessages  boolean value for hasMessages.
         * @return Builder
         */
        public Builder hasMessages(boolean hasMessages) {
            this.hasMessages = hasMessages;
            return this;
        }

        /**
         * Setter for flairUrl.
         * @param  flairUrl  String value for flairUrl.
         * @return Builder
         */
        public Builder flairUrl(String flairUrl) {
            this.flairUrl = flairUrl;
            return this;
        }

        /**
         * Setter for flairBgColor.
         * @param  flairBgColor  String value for flairBgColor.
         * @return Builder
         */
        public Builder flairBgColor(String flairBgColor) {
            this.flairBgColor = flairBgColor;
            return this;
        }

        /**
         * Setter for flairColor.
         * @param  flairColor  String value for flairColor.
         * @return Builder
         */
        public Builder flairColor(String flairColor) {
            this.flairColor = flairColor;
            return this;
        }

        /**
         * Setter for bioRaw.
         * @param  bioRaw  String value for bioRaw.
         * @return Builder
         */
        public Builder bioRaw(String bioRaw) {
            this.bioRaw = bioRaw;
            return this;
        }

        /**
         * Setter for bioCooked.
         * @param  bioCooked  String value for bioCooked.
         * @return Builder
         */
        public Builder bioCooked(String bioCooked) {
            this.bioCooked = bioCooked;
            return this;
        }

        /**
         * Setter for bioExcerpt.
         * @param  bioExcerpt  String value for bioExcerpt.
         * @return Builder
         */
        public Builder bioExcerpt(String bioExcerpt) {
            this.bioExcerpt = bioExcerpt;
            return this;
        }

        /**
         * Setter for publicAdmission.
         * @param  publicAdmission  boolean value for publicAdmission.
         * @return Builder
         */
        public Builder publicAdmission(boolean publicAdmission) {
            this.publicAdmission = publicAdmission;
            return this;
        }

        /**
         * Setter for publicExit.
         * @param  publicExit  boolean value for publicExit.
         * @return Builder
         */
        public Builder publicExit(boolean publicExit) {
            this.publicExit = publicExit;
            return this;
        }

        /**
         * Setter for allowMembershipRequests.
         * @param  allowMembershipRequests  boolean value for allowMembershipRequests.
         * @return Builder
         */
        public Builder allowMembershipRequests(boolean allowMembershipRequests) {
            this.allowMembershipRequests = allowMembershipRequests;
            return this;
        }

        /**
         * Setter for fullName.
         * @param  fullName  String value for fullName.
         * @return Builder
         */
        public Builder fullName(String fullName) {
            this.fullName = fullName;
            return this;
        }

        /**
         * Setter for defaultNotificationLevel.
         * @param  defaultNotificationLevel  int value for defaultNotificationLevel.
         * @return Builder
         */
        public Builder defaultNotificationLevel(int defaultNotificationLevel) {
            this.defaultNotificationLevel = defaultNotificationLevel;
            return this;
        }

        /**
         * Setter for membershipRequestTemplate.
         * @param  membershipRequestTemplate  String value for membershipRequestTemplate.
         * @return Builder
         */
        public Builder membershipRequestTemplate(String membershipRequestTemplate) {
            this.membershipRequestTemplate = membershipRequestTemplate;
            return this;
        }

        /**
         * Setter for membersVisibilityLevel.
         * @param  membersVisibilityLevel  int value for membersVisibilityLevel.
         * @return Builder
         */
        public Builder membersVisibilityLevel(int membersVisibilityLevel) {
            this.membersVisibilityLevel = membersVisibilityLevel;
            return this;
        }

        /**
         * Setter for canSeeMembers.
         * @param  canSeeMembers  boolean value for canSeeMembers.
         * @return Builder
         */
        public Builder canSeeMembers(boolean canSeeMembers) {
            this.canSeeMembers = canSeeMembers;
            return this;
        }

        /**
         * Setter for canAdminGroup.
         * @param  canAdminGroup  boolean value for canAdminGroup.
         * @return Builder
         */
        public Builder canAdminGroup(boolean canAdminGroup) {
            this.canAdminGroup = canAdminGroup;
            return this;
        }

        /**
         * Setter for publishReadState.
         * @param  publishReadState  boolean value for publishReadState.
         * @return Builder
         */
        public Builder publishReadState(boolean publishReadState) {
            this.publishReadState = publishReadState;
            return this;
        }

        /**
         * Setter for flairGroupId.
         * @param  flairGroupId  Integer value for flairGroupId.
         * @return Builder
         */
        public Builder flairGroupId(Integer flairGroupId) {
            this.flairGroupId = OptionalNullable.of(flairGroupId);
            return this;
        }

        /**
         * UnSetter for flairGroupId.
         * @return Builder
         */
        public Builder unsetFlairGroupId() {
            flairGroupId = null;
            return this;
        }

        /**
         * Builds a new {@link Group10} object using the set fields.
         * @return {@link Group10}
         */
        public Group10 build() {
            return new Group10(id, automatic, name, displayName, userCount, mentionableLevel,
                    messageableLevel, visibilityLevel, primaryGroup, title, grantTrustLevel,
                    incomingEmail, hasMessages, flairUrl, flairBgColor, flairColor, bioRaw,
                    bioCooked, bioExcerpt, publicAdmission, publicExit, allowMembershipRequests,
                    fullName, defaultNotificationLevel, membershipRequestTemplate,
                    membersVisibilityLevel, canSeeMembers, canAdminGroup, publishReadState,
                    flairGroupId);
        }
    }
}
