/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GroupPermission type.
 */
public class GroupPermission {
    private int permissionType;
    private String groupName;
    private int groupId;

    /**
     * Default constructor.
     */
    public GroupPermission() {
    }

    /**
     * Initialization constructor.
     * @param  permissionType  int value for permissionType.
     * @param  groupName  String value for groupName.
     * @param  groupId  int value for groupId.
     */
    public GroupPermission(
            int permissionType,
            String groupName,
            int groupId) {
        this.permissionType = permissionType;
        this.groupName = groupName;
        this.groupId = groupId;
    }

    /**
     * Getter for PermissionType.
     * @return Returns the int
     */
    @JsonGetter("permission_type")
    public int getPermissionType() {
        return permissionType;
    }

    /**
     * Setter for PermissionType.
     * @param permissionType Value for int
     */
    @JsonSetter("permission_type")
    public void setPermissionType(int permissionType) {
        this.permissionType = permissionType;
    }

    /**
     * Getter for GroupName.
     * @return Returns the String
     */
    @JsonGetter("group_name")
    public String getGroupName() {
        return groupName;
    }

    /**
     * Setter for GroupName.
     * @param groupName Value for String
     */
    @JsonSetter("group_name")
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * Getter for GroupId.
     * @return Returns the int
     */
    @JsonGetter("group_id")
    public int getGroupId() {
        return groupId;
    }

    /**
     * Setter for GroupId.
     * @param groupId Value for int
     */
    @JsonSetter("group_id")
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    /**
     * Converts this GroupPermission into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GroupPermission [" + "permissionType=" + permissionType + ", groupName=" + groupName
                + ", groupId=" + groupId + "]";
    }

    /**
     * Builds a new {@link GroupPermission.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GroupPermission.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(permissionType, groupName, groupId);
        return builder;
    }

    /**
     * Class to build instances of {@link GroupPermission}.
     */
    public static class Builder {
        private int permissionType;
        private String groupName;
        private int groupId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  permissionType  int value for permissionType.
         * @param  groupName  String value for groupName.
         * @param  groupId  int value for groupId.
         */
        public Builder(int permissionType, String groupName, int groupId) {
            this.permissionType = permissionType;
            this.groupName = groupName;
            this.groupId = groupId;
        }

        /**
         * Setter for permissionType.
         * @param  permissionType  int value for permissionType.
         * @return Builder
         */
        public Builder permissionType(int permissionType) {
            this.permissionType = permissionType;
            return this;
        }

        /**
         * Setter for groupName.
         * @param  groupName  String value for groupName.
         * @return Builder
         */
        public Builder groupName(String groupName) {
            this.groupName = groupName;
            return this;
        }

        /**
         * Setter for groupId.
         * @param  groupId  int value for groupId.
         * @return Builder
         */
        public Builder groupId(int groupId) {
            this.groupId = groupId;
            return this;
        }

        /**
         * Builds a new {@link GroupPermission} object using the set fields.
         * @return {@link GroupPermission}
         */
        public GroupPermission build() {
            return new GroupPermission(permissionType, groupName, groupId);
        }
    }
}
