/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Group type.
 */
public class Group {
    private String name;
    private String fullName;
    private String bioRaw;
    private String usernames;
    private String ownerUsernames;
    private String automaticMembershipEmailDomains;
    private Integer visibilityLevel;
    private Boolean primaryGroup;
    private String flairIcon;
    private Integer flairUploadId;
    private String flairBgColor;
    private Boolean publicAdmission;
    private Boolean publicExit;
    private Integer defaultNotificationLevel;
    private List<Integer> mutedCategoryIds;
    private List<Integer> regularCategoryIds;
    private List<Integer> watchingCategoryIds;
    private List<Integer> trackingCategoryIds;
    private List<Integer> watchingFirstPostCategoryIds;

    /**
     * Default constructor.
     */
    public Group() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  fullName  String value for fullName.
     * @param  bioRaw  String value for bioRaw.
     * @param  usernames  String value for usernames.
     * @param  ownerUsernames  String value for ownerUsernames.
     * @param  automaticMembershipEmailDomains  String value for automaticMembershipEmailDomains.
     * @param  visibilityLevel  Integer value for visibilityLevel.
     * @param  primaryGroup  Boolean value for primaryGroup.
     * @param  flairIcon  String value for flairIcon.
     * @param  flairUploadId  Integer value for flairUploadId.
     * @param  flairBgColor  String value for flairBgColor.
     * @param  publicAdmission  Boolean value for publicAdmission.
     * @param  publicExit  Boolean value for publicExit.
     * @param  defaultNotificationLevel  Integer value for defaultNotificationLevel.
     * @param  mutedCategoryIds  List of Integer value for mutedCategoryIds.
     * @param  regularCategoryIds  List of Integer value for regularCategoryIds.
     * @param  watchingCategoryIds  List of Integer value for watchingCategoryIds.
     * @param  trackingCategoryIds  List of Integer value for trackingCategoryIds.
     * @param  watchingFirstPostCategoryIds  List of Integer value for watchingFirstPostCategoryIds.
     */
    public Group(
            String name,
            String fullName,
            String bioRaw,
            String usernames,
            String ownerUsernames,
            String automaticMembershipEmailDomains,
            Integer visibilityLevel,
            Boolean primaryGroup,
            String flairIcon,
            Integer flairUploadId,
            String flairBgColor,
            Boolean publicAdmission,
            Boolean publicExit,
            Integer defaultNotificationLevel,
            List<Integer> mutedCategoryIds,
            List<Integer> regularCategoryIds,
            List<Integer> watchingCategoryIds,
            List<Integer> trackingCategoryIds,
            List<Integer> watchingFirstPostCategoryIds) {
        this.name = name;
        this.fullName = fullName;
        this.bioRaw = bioRaw;
        this.usernames = usernames;
        this.ownerUsernames = ownerUsernames;
        this.automaticMembershipEmailDomains = automaticMembershipEmailDomains;
        this.visibilityLevel = visibilityLevel;
        this.primaryGroup = primaryGroup;
        this.flairIcon = flairIcon;
        this.flairUploadId = flairUploadId;
        this.flairBgColor = flairBgColor;
        this.publicAdmission = publicAdmission;
        this.publicExit = publicExit;
        this.defaultNotificationLevel = defaultNotificationLevel;
        this.mutedCategoryIds = mutedCategoryIds;
        this.regularCategoryIds = regularCategoryIds;
        this.watchingCategoryIds = watchingCategoryIds;
        this.trackingCategoryIds = trackingCategoryIds;
        this.watchingFirstPostCategoryIds = watchingFirstPostCategoryIds;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for FullName.
     * @return Returns the String
     */
    @JsonGetter("full_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFullName() {
        return fullName;
    }

    /**
     * Setter for FullName.
     * @param fullName Value for String
     */
    @JsonSetter("full_name")
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for BioRaw.
     * About Group
     * @return Returns the String
     */
    @JsonGetter("bio_raw")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBioRaw() {
        return bioRaw;
    }

    /**
     * Setter for BioRaw.
     * About Group
     * @param bioRaw Value for String
     */
    @JsonSetter("bio_raw")
    public void setBioRaw(String bioRaw) {
        this.bioRaw = bioRaw;
    }

    /**
     * Getter for Usernames.
     * comma,separated
     * @return Returns the String
     */
    @JsonGetter("usernames")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUsernames() {
        return usernames;
    }

    /**
     * Setter for Usernames.
     * comma,separated
     * @param usernames Value for String
     */
    @JsonSetter("usernames")
    public void setUsernames(String usernames) {
        this.usernames = usernames;
    }

    /**
     * Getter for OwnerUsernames.
     * comma,separated
     * @return Returns the String
     */
    @JsonGetter("owner_usernames")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOwnerUsernames() {
        return ownerUsernames;
    }

    /**
     * Setter for OwnerUsernames.
     * comma,separated
     * @param ownerUsernames Value for String
     */
    @JsonSetter("owner_usernames")
    public void setOwnerUsernames(String ownerUsernames) {
        this.ownerUsernames = ownerUsernames;
    }

    /**
     * Getter for AutomaticMembershipEmailDomains.
     * pipe|separated
     * @return Returns the String
     */
    @JsonGetter("automatic_membership_email_domains")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAutomaticMembershipEmailDomains() {
        return automaticMembershipEmailDomains;
    }

    /**
     * Setter for AutomaticMembershipEmailDomains.
     * pipe|separated
     * @param automaticMembershipEmailDomains Value for String
     */
    @JsonSetter("automatic_membership_email_domains")
    public void setAutomaticMembershipEmailDomains(String automaticMembershipEmailDomains) {
        this.automaticMembershipEmailDomains = automaticMembershipEmailDomains;
    }

    /**
     * Getter for VisibilityLevel.
     * @return Returns the Integer
     */
    @JsonGetter("visibility_level")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getVisibilityLevel() {
        return visibilityLevel;
    }

    /**
     * Setter for VisibilityLevel.
     * @param visibilityLevel Value for Integer
     */
    @JsonSetter("visibility_level")
    public void setVisibilityLevel(Integer visibilityLevel) {
        this.visibilityLevel = visibilityLevel;
    }

    /**
     * Getter for PrimaryGroup.
     * @return Returns the Boolean
     */
    @JsonGetter("primary_group")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getPrimaryGroup() {
        return primaryGroup;
    }

    /**
     * Setter for PrimaryGroup.
     * @param primaryGroup Value for Boolean
     */
    @JsonSetter("primary_group")
    public void setPrimaryGroup(Boolean primaryGroup) {
        this.primaryGroup = primaryGroup;
    }

    /**
     * Getter for FlairIcon.
     * @return Returns the String
     */
    @JsonGetter("flair_icon")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFlairIcon() {
        return flairIcon;
    }

    /**
     * Setter for FlairIcon.
     * @param flairIcon Value for String
     */
    @JsonSetter("flair_icon")
    public void setFlairIcon(String flairIcon) {
        this.flairIcon = flairIcon;
    }

    /**
     * Getter for FlairUploadId.
     * @return Returns the Integer
     */
    @JsonGetter("flair_upload_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getFlairUploadId() {
        return flairUploadId;
    }

    /**
     * Setter for FlairUploadId.
     * @param flairUploadId Value for Integer
     */
    @JsonSetter("flair_upload_id")
    public void setFlairUploadId(Integer flairUploadId) {
        this.flairUploadId = flairUploadId;
    }

    /**
     * Getter for FlairBgColor.
     * @return Returns the String
     */
    @JsonGetter("flair_bg_color")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFlairBgColor() {
        return flairBgColor;
    }

    /**
     * Setter for FlairBgColor.
     * @param flairBgColor Value for String
     */
    @JsonSetter("flair_bg_color")
    public void setFlairBgColor(String flairBgColor) {
        this.flairBgColor = flairBgColor;
    }

    /**
     * Getter for PublicAdmission.
     * @return Returns the Boolean
     */
    @JsonGetter("public_admission")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getPublicAdmission() {
        return publicAdmission;
    }

    /**
     * Setter for PublicAdmission.
     * @param publicAdmission Value for Boolean
     */
    @JsonSetter("public_admission")
    public void setPublicAdmission(Boolean publicAdmission) {
        this.publicAdmission = publicAdmission;
    }

    /**
     * Getter for PublicExit.
     * @return Returns the Boolean
     */
    @JsonGetter("public_exit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getPublicExit() {
        return publicExit;
    }

    /**
     * Setter for PublicExit.
     * @param publicExit Value for Boolean
     */
    @JsonSetter("public_exit")
    public void setPublicExit(Boolean publicExit) {
        this.publicExit = publicExit;
    }

    /**
     * Getter for DefaultNotificationLevel.
     * @return Returns the Integer
     */
    @JsonGetter("default_notification_level")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDefaultNotificationLevel() {
        return defaultNotificationLevel;
    }

    /**
     * Setter for DefaultNotificationLevel.
     * @param defaultNotificationLevel Value for Integer
     */
    @JsonSetter("default_notification_level")
    public void setDefaultNotificationLevel(Integer defaultNotificationLevel) {
        this.defaultNotificationLevel = defaultNotificationLevel;
    }

    /**
     * Getter for MutedCategoryIds.
     * @return Returns the List of Integer
     */
    @JsonGetter("muted_category_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getMutedCategoryIds() {
        return mutedCategoryIds;
    }

    /**
     * Setter for MutedCategoryIds.
     * @param mutedCategoryIds Value for List of Integer
     */
    @JsonSetter("muted_category_ids")
    public void setMutedCategoryIds(List<Integer> mutedCategoryIds) {
        this.mutedCategoryIds = mutedCategoryIds;
    }

    /**
     * Getter for RegularCategoryIds.
     * @return Returns the List of Integer
     */
    @JsonGetter("regular_category_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getRegularCategoryIds() {
        return regularCategoryIds;
    }

    /**
     * Setter for RegularCategoryIds.
     * @param regularCategoryIds Value for List of Integer
     */
    @JsonSetter("regular_category_ids")
    public void setRegularCategoryIds(List<Integer> regularCategoryIds) {
        this.regularCategoryIds = regularCategoryIds;
    }

    /**
     * Getter for WatchingCategoryIds.
     * @return Returns the List of Integer
     */
    @JsonGetter("watching_category_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getWatchingCategoryIds() {
        return watchingCategoryIds;
    }

    /**
     * Setter for WatchingCategoryIds.
     * @param watchingCategoryIds Value for List of Integer
     */
    @JsonSetter("watching_category_ids")
    public void setWatchingCategoryIds(List<Integer> watchingCategoryIds) {
        this.watchingCategoryIds = watchingCategoryIds;
    }

    /**
     * Getter for TrackingCategoryIds.
     * @return Returns the List of Integer
     */
    @JsonGetter("tracking_category_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getTrackingCategoryIds() {
        return trackingCategoryIds;
    }

    /**
     * Setter for TrackingCategoryIds.
     * @param trackingCategoryIds Value for List of Integer
     */
    @JsonSetter("tracking_category_ids")
    public void setTrackingCategoryIds(List<Integer> trackingCategoryIds) {
        this.trackingCategoryIds = trackingCategoryIds;
    }

    /**
     * Getter for WatchingFirstPostCategoryIds.
     * @return Returns the List of Integer
     */
    @JsonGetter("watching_first_post_category_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getWatchingFirstPostCategoryIds() {
        return watchingFirstPostCategoryIds;
    }

    /**
     * Setter for WatchingFirstPostCategoryIds.
     * @param watchingFirstPostCategoryIds Value for List of Integer
     */
    @JsonSetter("watching_first_post_category_ids")
    public void setWatchingFirstPostCategoryIds(List<Integer> watchingFirstPostCategoryIds) {
        this.watchingFirstPostCategoryIds = watchingFirstPostCategoryIds;
    }

    /**
     * Converts this Group into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Group [" + "name=" + name + ", fullName=" + fullName + ", bioRaw=" + bioRaw
                + ", usernames=" + usernames + ", ownerUsernames=" + ownerUsernames
                + ", automaticMembershipEmailDomains=" + automaticMembershipEmailDomains
                + ", visibilityLevel=" + visibilityLevel + ", primaryGroup=" + primaryGroup
                + ", flairIcon=" + flairIcon + ", flairUploadId=" + flairUploadId
                + ", flairBgColor=" + flairBgColor + ", publicAdmission=" + publicAdmission
                + ", publicExit=" + publicExit + ", defaultNotificationLevel="
                + defaultNotificationLevel + ", mutedCategoryIds=" + mutedCategoryIds
                + ", regularCategoryIds=" + regularCategoryIds + ", watchingCategoryIds="
                + watchingCategoryIds + ", trackingCategoryIds=" + trackingCategoryIds
                + ", watchingFirstPostCategoryIds=" + watchingFirstPostCategoryIds + "]";
    }

    /**
     * Builds a new {@link Group.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Group.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name)
                .fullName(getFullName())
                .bioRaw(getBioRaw())
                .usernames(getUsernames())
                .ownerUsernames(getOwnerUsernames())
                .automaticMembershipEmailDomains(getAutomaticMembershipEmailDomains())
                .visibilityLevel(getVisibilityLevel())
                .primaryGroup(getPrimaryGroup())
                .flairIcon(getFlairIcon())
                .flairUploadId(getFlairUploadId())
                .flairBgColor(getFlairBgColor())
                .publicAdmission(getPublicAdmission())
                .publicExit(getPublicExit())
                .defaultNotificationLevel(getDefaultNotificationLevel())
                .mutedCategoryIds(getMutedCategoryIds())
                .regularCategoryIds(getRegularCategoryIds())
                .watchingCategoryIds(getWatchingCategoryIds())
                .trackingCategoryIds(getTrackingCategoryIds())
                .watchingFirstPostCategoryIds(getWatchingFirstPostCategoryIds());
        return builder;
    }

    /**
     * Class to build instances of {@link Group}.
     */
    public static class Builder {
        private String name;
        private String fullName;
        private String bioRaw;
        private String usernames;
        private String ownerUsernames;
        private String automaticMembershipEmailDomains;
        private Integer visibilityLevel;
        private Boolean primaryGroup;
        private String flairIcon;
        private Integer flairUploadId;
        private String flairBgColor;
        private Boolean publicAdmission;
        private Boolean publicExit;
        private Integer defaultNotificationLevel;
        private List<Integer> mutedCategoryIds;
        private List<Integer> regularCategoryIds;
        private List<Integer> watchingCategoryIds;
        private List<Integer> trackingCategoryIds;
        private List<Integer> watchingFirstPostCategoryIds;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  String value for name.
         */
        public Builder(String name) {
            this.name = name;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for fullName.
         * @param  fullName  String value for fullName.
         * @return Builder
         */
        public Builder fullName(String fullName) {
            this.fullName = fullName;
            return this;
        }

        /**
         * Setter for bioRaw.
         * @param  bioRaw  String value for bioRaw.
         * @return Builder
         */
        public Builder bioRaw(String bioRaw) {
            this.bioRaw = bioRaw;
            return this;
        }

        /**
         * Setter for usernames.
         * @param  usernames  String value for usernames.
         * @return Builder
         */
        public Builder usernames(String usernames) {
            this.usernames = usernames;
            return this;
        }

        /**
         * Setter for ownerUsernames.
         * @param  ownerUsernames  String value for ownerUsernames.
         * @return Builder
         */
        public Builder ownerUsernames(String ownerUsernames) {
            this.ownerUsernames = ownerUsernames;
            return this;
        }

        /**
         * Setter for automaticMembershipEmailDomains.
         * @param  automaticMembershipEmailDomains  String value for
         *         automaticMembershipEmailDomains.
         * @return Builder
         */
        public Builder automaticMembershipEmailDomains(String automaticMembershipEmailDomains) {
            this.automaticMembershipEmailDomains = automaticMembershipEmailDomains;
            return this;
        }

        /**
         * Setter for visibilityLevel.
         * @param  visibilityLevel  Integer value for visibilityLevel.
         * @return Builder
         */
        public Builder visibilityLevel(Integer visibilityLevel) {
            this.visibilityLevel = visibilityLevel;
            return this;
        }

        /**
         * Setter for primaryGroup.
         * @param  primaryGroup  Boolean value for primaryGroup.
         * @return Builder
         */
        public Builder primaryGroup(Boolean primaryGroup) {
            this.primaryGroup = primaryGroup;
            return this;
        }

        /**
         * Setter for flairIcon.
         * @param  flairIcon  String value for flairIcon.
         * @return Builder
         */
        public Builder flairIcon(String flairIcon) {
            this.flairIcon = flairIcon;
            return this;
        }

        /**
         * Setter for flairUploadId.
         * @param  flairUploadId  Integer value for flairUploadId.
         * @return Builder
         */
        public Builder flairUploadId(Integer flairUploadId) {
            this.flairUploadId = flairUploadId;
            return this;
        }

        /**
         * Setter for flairBgColor.
         * @param  flairBgColor  String value for flairBgColor.
         * @return Builder
         */
        public Builder flairBgColor(String flairBgColor) {
            this.flairBgColor = flairBgColor;
            return this;
        }

        /**
         * Setter for publicAdmission.
         * @param  publicAdmission  Boolean value for publicAdmission.
         * @return Builder
         */
        public Builder publicAdmission(Boolean publicAdmission) {
            this.publicAdmission = publicAdmission;
            return this;
        }

        /**
         * Setter for publicExit.
         * @param  publicExit  Boolean value for publicExit.
         * @return Builder
         */
        public Builder publicExit(Boolean publicExit) {
            this.publicExit = publicExit;
            return this;
        }

        /**
         * Setter for defaultNotificationLevel.
         * @param  defaultNotificationLevel  Integer value for defaultNotificationLevel.
         * @return Builder
         */
        public Builder defaultNotificationLevel(Integer defaultNotificationLevel) {
            this.defaultNotificationLevel = defaultNotificationLevel;
            return this;
        }

        /**
         * Setter for mutedCategoryIds.
         * @param  mutedCategoryIds  List of Integer value for mutedCategoryIds.
         * @return Builder
         */
        public Builder mutedCategoryIds(List<Integer> mutedCategoryIds) {
            this.mutedCategoryIds = mutedCategoryIds;
            return this;
        }

        /**
         * Setter for regularCategoryIds.
         * @param  regularCategoryIds  List of Integer value for regularCategoryIds.
         * @return Builder
         */
        public Builder regularCategoryIds(List<Integer> regularCategoryIds) {
            this.regularCategoryIds = regularCategoryIds;
            return this;
        }

        /**
         * Setter for watchingCategoryIds.
         * @param  watchingCategoryIds  List of Integer value for watchingCategoryIds.
         * @return Builder
         */
        public Builder watchingCategoryIds(List<Integer> watchingCategoryIds) {
            this.watchingCategoryIds = watchingCategoryIds;
            return this;
        }

        /**
         * Setter for trackingCategoryIds.
         * @param  trackingCategoryIds  List of Integer value for trackingCategoryIds.
         * @return Builder
         */
        public Builder trackingCategoryIds(List<Integer> trackingCategoryIds) {
            this.trackingCategoryIds = trackingCategoryIds;
            return this;
        }

        /**
         * Setter for watchingFirstPostCategoryIds.
         * @param  watchingFirstPostCategoryIds  List of Integer value for
         *         watchingFirstPostCategoryIds.
         * @return Builder
         */
        public Builder watchingFirstPostCategoryIds(List<Integer> watchingFirstPostCategoryIds) {
            this.watchingFirstPostCategoryIds = watchingFirstPostCategoryIds;
            return this;
        }

        /**
         * Builds a new {@link Group} object using the set fields.
         * @return {@link Group}
         */
        public Group build() {
            return new Group(name, fullName, bioRaw, usernames, ownerUsernames,
                    automaticMembershipEmailDomains, visibilityLevel, primaryGroup, flairIcon,
                    flairUploadId, flairBgColor, publicAdmission, publicExit,
                    defaultNotificationLevel, mutedCategoryIds, regularCategoryIds,
                    watchingCategoryIds, trackingCategoryIds, watchingFirstPostCategoryIds);
        }
    }
}
