/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;
import java.util.List;

/**
 * This is a model class for Group1 type.
 */
public class Group1 {
    private int id;
    private boolean automatic;
    private String name;
    private Integer userCount;
    private int mentionableLevel;
    private int messageableLevel;
    private int visibilityLevel;
    private boolean primaryGroup;
    private String title;
    private String grantTrustLevel;
    private String incomingEmail;
    private boolean hasMessages;
    private String flairUrl;
    private String flairBgColor;
    private String flairColor;
    private String bioRaw;
    private String bioCooked;
    private String bioExcerpt;
    private boolean publicAdmission;
    private boolean publicExit;
    private boolean allowMembershipRequests;
    private String fullName;
    private int defaultNotificationLevel;
    private String membershipRequestTemplate;
    private boolean isGroupUser;
    private int membersVisibilityLevel;
    private boolean canSeeMembers;
    private boolean canAdminGroup;
    private Boolean canEditGroup;
    private boolean publishReadState;
    private boolean isGroupOwnerDisplay;
    private boolean mentionable;
    private boolean messageable;
    private String automaticMembershipEmailDomains;
    private OptionalNullable<String> smtpUpdatedAt;
    private OptionalNullable<Object> smtpUpdatedBy;
    private Boolean smtpEnabled;
    private String smtpServer;
    private String smtpPort;
    private Integer smtpSslMode;
    private String emailUsername;
    private OptionalNullable<String> emailFromAlias;
    private String emailPassword;
    private int messageCount;
    private boolean allowUnknownSenderTopicReplies;
    private List<Object> associatedGroupIds;
    private List<Object> watchingCategoryIds;
    private List<Object> trackingCategoryIds;
    private List<Object> watchingFirstPostCategoryIds;
    private List<Object> regularCategoryIds;
    private List<Object> mutedCategoryIds;
    private List<Object> watchingTags;
    private List<Object> watchingFirstPostTags;
    private List<Object> trackingTags;
    private List<Object> regularTags;
    private List<Object> mutedTags;

    /**
     * Default constructor.
     */
    public Group1() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  automatic  boolean value for automatic.
     * @param  name  String value for name.
     * @param  mentionableLevel  int value for mentionableLevel.
     * @param  messageableLevel  int value for messageableLevel.
     * @param  visibilityLevel  int value for visibilityLevel.
     * @param  primaryGroup  boolean value for primaryGroup.
     * @param  title  String value for title.
     * @param  grantTrustLevel  String value for grantTrustLevel.
     * @param  incomingEmail  String value for incomingEmail.
     * @param  hasMessages  boolean value for hasMessages.
     * @param  flairUrl  String value for flairUrl.
     * @param  flairBgColor  String value for flairBgColor.
     * @param  flairColor  String value for flairColor.
     * @param  bioRaw  String value for bioRaw.
     * @param  bioCooked  String value for bioCooked.
     * @param  bioExcerpt  String value for bioExcerpt.
     * @param  publicAdmission  boolean value for publicAdmission.
     * @param  publicExit  boolean value for publicExit.
     * @param  allowMembershipRequests  boolean value for allowMembershipRequests.
     * @param  fullName  String value for fullName.
     * @param  defaultNotificationLevel  int value for defaultNotificationLevel.
     * @param  membershipRequestTemplate  String value for membershipRequestTemplate.
     * @param  isGroupUser  boolean value for isGroupUser.
     * @param  membersVisibilityLevel  int value for membersVisibilityLevel.
     * @param  canSeeMembers  boolean value for canSeeMembers.
     * @param  canAdminGroup  boolean value for canAdminGroup.
     * @param  publishReadState  boolean value for publishReadState.
     * @param  isGroupOwnerDisplay  boolean value for isGroupOwnerDisplay.
     * @param  mentionable  boolean value for mentionable.
     * @param  messageable  boolean value for messageable.
     * @param  automaticMembershipEmailDomains  String value for automaticMembershipEmailDomains.
     * @param  smtpServer  String value for smtpServer.
     * @param  smtpPort  String value for smtpPort.
     * @param  smtpSslMode  Integer value for smtpSslMode.
     * @param  emailUsername  String value for emailUsername.
     * @param  emailPassword  String value for emailPassword.
     * @param  messageCount  int value for messageCount.
     * @param  allowUnknownSenderTopicReplies  boolean value for allowUnknownSenderTopicReplies.
     * @param  watchingCategoryIds  List of Object value for watchingCategoryIds.
     * @param  trackingCategoryIds  List of Object value for trackingCategoryIds.
     * @param  watchingFirstPostCategoryIds  List of Object value for watchingFirstPostCategoryIds.
     * @param  regularCategoryIds  List of Object value for regularCategoryIds.
     * @param  mutedCategoryIds  List of Object value for mutedCategoryIds.
     * @param  userCount  Integer value for userCount.
     * @param  canEditGroup  Boolean value for canEditGroup.
     * @param  smtpUpdatedAt  String value for smtpUpdatedAt.
     * @param  smtpUpdatedBy  Object value for smtpUpdatedBy.
     * @param  smtpEnabled  Boolean value for smtpEnabled.
     * @param  emailFromAlias  String value for emailFromAlias.
     * @param  associatedGroupIds  List of Object value for associatedGroupIds.
     * @param  watchingTags  List of Object value for watchingTags.
     * @param  watchingFirstPostTags  List of Object value for watchingFirstPostTags.
     * @param  trackingTags  List of Object value for trackingTags.
     * @param  regularTags  List of Object value for regularTags.
     * @param  mutedTags  List of Object value for mutedTags.
     */
    public Group1(
            int id,
            boolean automatic,
            String name,
            int mentionableLevel,
            int messageableLevel,
            int visibilityLevel,
            boolean primaryGroup,
            String title,
            String grantTrustLevel,
            String incomingEmail,
            boolean hasMessages,
            String flairUrl,
            String flairBgColor,
            String flairColor,
            String bioRaw,
            String bioCooked,
            String bioExcerpt,
            boolean publicAdmission,
            boolean publicExit,
            boolean allowMembershipRequests,
            String fullName,
            int defaultNotificationLevel,
            String membershipRequestTemplate,
            boolean isGroupUser,
            int membersVisibilityLevel,
            boolean canSeeMembers,
            boolean canAdminGroup,
            boolean publishReadState,
            boolean isGroupOwnerDisplay,
            boolean mentionable,
            boolean messageable,
            String automaticMembershipEmailDomains,
            String smtpServer,
            String smtpPort,
            Integer smtpSslMode,
            String emailUsername,
            String emailPassword,
            int messageCount,
            boolean allowUnknownSenderTopicReplies,
            List<Object> watchingCategoryIds,
            List<Object> trackingCategoryIds,
            List<Object> watchingFirstPostCategoryIds,
            List<Object> regularCategoryIds,
            List<Object> mutedCategoryIds,
            Integer userCount,
            Boolean canEditGroup,
            String smtpUpdatedAt,
            Object smtpUpdatedBy,
            Boolean smtpEnabled,
            String emailFromAlias,
            List<Object> associatedGroupIds,
            List<Object> watchingTags,
            List<Object> watchingFirstPostTags,
            List<Object> trackingTags,
            List<Object> regularTags,
            List<Object> mutedTags) {
        this.id = id;
        this.automatic = automatic;
        this.name = name;
        this.userCount = userCount;
        this.mentionableLevel = mentionableLevel;
        this.messageableLevel = messageableLevel;
        this.visibilityLevel = visibilityLevel;
        this.primaryGroup = primaryGroup;
        this.title = title;
        this.grantTrustLevel = grantTrustLevel;
        this.incomingEmail = incomingEmail;
        this.hasMessages = hasMessages;
        this.flairUrl = flairUrl;
        this.flairBgColor = flairBgColor;
        this.flairColor = flairColor;
        this.bioRaw = bioRaw;
        this.bioCooked = bioCooked;
        this.bioExcerpt = bioExcerpt;
        this.publicAdmission = publicAdmission;
        this.publicExit = publicExit;
        this.allowMembershipRequests = allowMembershipRequests;
        this.fullName = fullName;
        this.defaultNotificationLevel = defaultNotificationLevel;
        this.membershipRequestTemplate = membershipRequestTemplate;
        this.isGroupUser = isGroupUser;
        this.membersVisibilityLevel = membersVisibilityLevel;
        this.canSeeMembers = canSeeMembers;
        this.canAdminGroup = canAdminGroup;
        this.canEditGroup = canEditGroup;
        this.publishReadState = publishReadState;
        this.isGroupOwnerDisplay = isGroupOwnerDisplay;
        this.mentionable = mentionable;
        this.messageable = messageable;
        this.automaticMembershipEmailDomains = automaticMembershipEmailDomains;
        this.smtpUpdatedAt = OptionalNullable.of(smtpUpdatedAt);
        this.smtpUpdatedBy = OptionalNullable.of(smtpUpdatedBy);
        this.smtpEnabled = smtpEnabled;
        this.smtpServer = smtpServer;
        this.smtpPort = smtpPort;
        this.smtpSslMode = smtpSslMode;
        this.emailUsername = emailUsername;
        this.emailFromAlias = OptionalNullable.of(emailFromAlias);
        this.emailPassword = emailPassword;
        this.messageCount = messageCount;
        this.allowUnknownSenderTopicReplies = allowUnknownSenderTopicReplies;
        this.associatedGroupIds = associatedGroupIds;
        this.watchingCategoryIds = watchingCategoryIds;
        this.trackingCategoryIds = trackingCategoryIds;
        this.watchingFirstPostCategoryIds = watchingFirstPostCategoryIds;
        this.regularCategoryIds = regularCategoryIds;
        this.mutedCategoryIds = mutedCategoryIds;
        this.watchingTags = watchingTags;
        this.watchingFirstPostTags = watchingFirstPostTags;
        this.trackingTags = trackingTags;
        this.regularTags = regularTags;
        this.mutedTags = mutedTags;
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  automatic  boolean value for automatic.
     * @param  name  String value for name.
     * @param  mentionableLevel  int value for mentionableLevel.
     * @param  messageableLevel  int value for messageableLevel.
     * @param  visibilityLevel  int value for visibilityLevel.
     * @param  primaryGroup  boolean value for primaryGroup.
     * @param  title  String value for title.
     * @param  grantTrustLevel  String value for grantTrustLevel.
     * @param  incomingEmail  String value for incomingEmail.
     * @param  hasMessages  boolean value for hasMessages.
     * @param  flairUrl  String value for flairUrl.
     * @param  flairBgColor  String value for flairBgColor.
     * @param  flairColor  String value for flairColor.
     * @param  bioRaw  String value for bioRaw.
     * @param  bioCooked  String value for bioCooked.
     * @param  bioExcerpt  String value for bioExcerpt.
     * @param  publicAdmission  boolean value for publicAdmission.
     * @param  publicExit  boolean value for publicExit.
     * @param  allowMembershipRequests  boolean value for allowMembershipRequests.
     * @param  fullName  String value for fullName.
     * @param  defaultNotificationLevel  int value for defaultNotificationLevel.
     * @param  membershipRequestTemplate  String value for membershipRequestTemplate.
     * @param  isGroupUser  boolean value for isGroupUser.
     * @param  membersVisibilityLevel  int value for membersVisibilityLevel.
     * @param  canSeeMembers  boolean value for canSeeMembers.
     * @param  canAdminGroup  boolean value for canAdminGroup.
     * @param  publishReadState  boolean value for publishReadState.
     * @param  isGroupOwnerDisplay  boolean value for isGroupOwnerDisplay.
     * @param  mentionable  boolean value for mentionable.
     * @param  messageable  boolean value for messageable.
     * @param  automaticMembershipEmailDomains  String value for automaticMembershipEmailDomains.
     * @param  smtpServer  String value for smtpServer.
     * @param  smtpPort  String value for smtpPort.
     * @param  smtpSslMode  Integer value for smtpSslMode.
     * @param  emailUsername  String value for emailUsername.
     * @param  emailPassword  String value for emailPassword.
     * @param  messageCount  int value for messageCount.
     * @param  allowUnknownSenderTopicReplies  boolean value for allowUnknownSenderTopicReplies.
     * @param  watchingCategoryIds  List of Object value for watchingCategoryIds.
     * @param  trackingCategoryIds  List of Object value for trackingCategoryIds.
     * @param  watchingFirstPostCategoryIds  List of Object value for watchingFirstPostCategoryIds.
     * @param  regularCategoryIds  List of Object value for regularCategoryIds.
     * @param  mutedCategoryIds  List of Object value for mutedCategoryIds.
     * @param  userCount  Integer value for userCount.
     * @param  canEditGroup  Boolean value for canEditGroup.
     * @param  smtpUpdatedAt  String value for smtpUpdatedAt.
     * @param  smtpUpdatedBy  Object value for smtpUpdatedBy.
     * @param  smtpEnabled  Boolean value for smtpEnabled.
     * @param  emailFromAlias  String value for emailFromAlias.
     * @param  associatedGroupIds  List of Object value for associatedGroupIds.
     * @param  watchingTags  List of Object value for watchingTags.
     * @param  watchingFirstPostTags  List of Object value for watchingFirstPostTags.
     * @param  trackingTags  List of Object value for trackingTags.
     * @param  regularTags  List of Object value for regularTags.
     * @param  mutedTags  List of Object value for mutedTags.
     */

    protected Group1(int id, boolean automatic, String name, int mentionableLevel,
            int messageableLevel, int visibilityLevel, boolean primaryGroup, String title,
            String grantTrustLevel, String incomingEmail, boolean hasMessages, String flairUrl,
            String flairBgColor, String flairColor, String bioRaw, String bioCooked,
            String bioExcerpt, boolean publicAdmission, boolean publicExit,
            boolean allowMembershipRequests, String fullName, int defaultNotificationLevel,
            String membershipRequestTemplate, boolean isGroupUser, int membersVisibilityLevel,
            boolean canSeeMembers, boolean canAdminGroup, boolean publishReadState,
            boolean isGroupOwnerDisplay, boolean mentionable, boolean messageable,
            String automaticMembershipEmailDomains, String smtpServer, String smtpPort,
            Integer smtpSslMode, String emailUsername, String emailPassword, int messageCount,
            boolean allowUnknownSenderTopicReplies, List<Object> watchingCategoryIds,
            List<Object> trackingCategoryIds, List<Object> watchingFirstPostCategoryIds,
            List<Object> regularCategoryIds, List<Object> mutedCategoryIds, Integer userCount,
            Boolean canEditGroup, OptionalNullable<String> smtpUpdatedAt,
            OptionalNullable<Object> smtpUpdatedBy, Boolean smtpEnabled,
            OptionalNullable<String> emailFromAlias, List<Object> associatedGroupIds,
            List<Object> watchingTags, List<Object> watchingFirstPostTags,
            List<Object> trackingTags, List<Object> regularTags, List<Object> mutedTags) {
        this.id = id;
        this.automatic = automatic;
        this.name = name;
        this.userCount = userCount;
        this.mentionableLevel = mentionableLevel;
        this.messageableLevel = messageableLevel;
        this.visibilityLevel = visibilityLevel;
        this.primaryGroup = primaryGroup;
        this.title = title;
        this.grantTrustLevel = grantTrustLevel;
        this.incomingEmail = incomingEmail;
        this.hasMessages = hasMessages;
        this.flairUrl = flairUrl;
        this.flairBgColor = flairBgColor;
        this.flairColor = flairColor;
        this.bioRaw = bioRaw;
        this.bioCooked = bioCooked;
        this.bioExcerpt = bioExcerpt;
        this.publicAdmission = publicAdmission;
        this.publicExit = publicExit;
        this.allowMembershipRequests = allowMembershipRequests;
        this.fullName = fullName;
        this.defaultNotificationLevel = defaultNotificationLevel;
        this.membershipRequestTemplate = membershipRequestTemplate;
        this.isGroupUser = isGroupUser;
        this.membersVisibilityLevel = membersVisibilityLevel;
        this.canSeeMembers = canSeeMembers;
        this.canAdminGroup = canAdminGroup;
        this.canEditGroup = canEditGroup;
        this.publishReadState = publishReadState;
        this.isGroupOwnerDisplay = isGroupOwnerDisplay;
        this.mentionable = mentionable;
        this.messageable = messageable;
        this.automaticMembershipEmailDomains = automaticMembershipEmailDomains;
        this.smtpUpdatedAt = smtpUpdatedAt;
        this.smtpUpdatedBy = smtpUpdatedBy;
        this.smtpEnabled = smtpEnabled;
        this.smtpServer = smtpServer;
        this.smtpPort = smtpPort;
        this.smtpSslMode = smtpSslMode;
        this.emailUsername = emailUsername;
        this.emailFromAlias = emailFromAlias;
        this.emailPassword = emailPassword;
        this.messageCount = messageCount;
        this.allowUnknownSenderTopicReplies = allowUnknownSenderTopicReplies;
        this.associatedGroupIds = associatedGroupIds;
        this.watchingCategoryIds = watchingCategoryIds;
        this.trackingCategoryIds = trackingCategoryIds;
        this.watchingFirstPostCategoryIds = watchingFirstPostCategoryIds;
        this.regularCategoryIds = regularCategoryIds;
        this.mutedCategoryIds = mutedCategoryIds;
        this.watchingTags = watchingTags;
        this.watchingFirstPostTags = watchingFirstPostTags;
        this.trackingTags = trackingTags;
        this.regularTags = regularTags;
        this.mutedTags = mutedTags;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for Automatic.
     * @return Returns the boolean
     */
    @JsonGetter("automatic")
    public boolean getAutomatic() {
        return automatic;
    }

    /**
     * Setter for Automatic.
     * @param automatic Value for boolean
     */
    @JsonSetter("automatic")
    public void setAutomatic(boolean automatic) {
        this.automatic = automatic;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for UserCount.
     * @return Returns the Integer
     */
    @JsonGetter("user_count")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getUserCount() {
        return userCount;
    }

    /**
     * Setter for UserCount.
     * @param userCount Value for Integer
     */
    @JsonSetter("user_count")
    public void setUserCount(Integer userCount) {
        this.userCount = userCount;
    }

    /**
     * Getter for MentionableLevel.
     * @return Returns the int
     */
    @JsonGetter("mentionable_level")
    public int getMentionableLevel() {
        return mentionableLevel;
    }

    /**
     * Setter for MentionableLevel.
     * @param mentionableLevel Value for int
     */
    @JsonSetter("mentionable_level")
    public void setMentionableLevel(int mentionableLevel) {
        this.mentionableLevel = mentionableLevel;
    }

    /**
     * Getter for MessageableLevel.
     * @return Returns the int
     */
    @JsonGetter("messageable_level")
    public int getMessageableLevel() {
        return messageableLevel;
    }

    /**
     * Setter for MessageableLevel.
     * @param messageableLevel Value for int
     */
    @JsonSetter("messageable_level")
    public void setMessageableLevel(int messageableLevel) {
        this.messageableLevel = messageableLevel;
    }

    /**
     * Getter for VisibilityLevel.
     * @return Returns the int
     */
    @JsonGetter("visibility_level")
    public int getVisibilityLevel() {
        return visibilityLevel;
    }

    /**
     * Setter for VisibilityLevel.
     * @param visibilityLevel Value for int
     */
    @JsonSetter("visibility_level")
    public void setVisibilityLevel(int visibilityLevel) {
        this.visibilityLevel = visibilityLevel;
    }

    /**
     * Getter for PrimaryGroup.
     * @return Returns the boolean
     */
    @JsonGetter("primary_group")
    public boolean getPrimaryGroup() {
        return primaryGroup;
    }

    /**
     * Setter for PrimaryGroup.
     * @param primaryGroup Value for boolean
     */
    @JsonSetter("primary_group")
    public void setPrimaryGroup(boolean primaryGroup) {
        this.primaryGroup = primaryGroup;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for GrantTrustLevel.
     * @return Returns the String
     */
    @JsonGetter("grant_trust_level")
    public String getGrantTrustLevel() {
        return grantTrustLevel;
    }

    /**
     * Setter for GrantTrustLevel.
     * @param grantTrustLevel Value for String
     */
    @JsonSetter("grant_trust_level")
    public void setGrantTrustLevel(String grantTrustLevel) {
        this.grantTrustLevel = grantTrustLevel;
    }

    /**
     * Getter for IncomingEmail.
     * @return Returns the String
     */
    @JsonGetter("incoming_email")
    public String getIncomingEmail() {
        return incomingEmail;
    }

    /**
     * Setter for IncomingEmail.
     * @param incomingEmail Value for String
     */
    @JsonSetter("incoming_email")
    public void setIncomingEmail(String incomingEmail) {
        this.incomingEmail = incomingEmail;
    }

    /**
     * Getter for HasMessages.
     * @return Returns the boolean
     */
    @JsonGetter("has_messages")
    public boolean getHasMessages() {
        return hasMessages;
    }

    /**
     * Setter for HasMessages.
     * @param hasMessages Value for boolean
     */
    @JsonSetter("has_messages")
    public void setHasMessages(boolean hasMessages) {
        this.hasMessages = hasMessages;
    }

    /**
     * Getter for FlairUrl.
     * @return Returns the String
     */
    @JsonGetter("flair_url")
    public String getFlairUrl() {
        return flairUrl;
    }

    /**
     * Setter for FlairUrl.
     * @param flairUrl Value for String
     */
    @JsonSetter("flair_url")
    public void setFlairUrl(String flairUrl) {
        this.flairUrl = flairUrl;
    }

    /**
     * Getter for FlairBgColor.
     * @return Returns the String
     */
    @JsonGetter("flair_bg_color")
    public String getFlairBgColor() {
        return flairBgColor;
    }

    /**
     * Setter for FlairBgColor.
     * @param flairBgColor Value for String
     */
    @JsonSetter("flair_bg_color")
    public void setFlairBgColor(String flairBgColor) {
        this.flairBgColor = flairBgColor;
    }

    /**
     * Getter for FlairColor.
     * @return Returns the String
     */
    @JsonGetter("flair_color")
    public String getFlairColor() {
        return flairColor;
    }

    /**
     * Setter for FlairColor.
     * @param flairColor Value for String
     */
    @JsonSetter("flair_color")
    public void setFlairColor(String flairColor) {
        this.flairColor = flairColor;
    }

    /**
     * Getter for BioRaw.
     * @return Returns the String
     */
    @JsonGetter("bio_raw")
    public String getBioRaw() {
        return bioRaw;
    }

    /**
     * Setter for BioRaw.
     * @param bioRaw Value for String
     */
    @JsonSetter("bio_raw")
    public void setBioRaw(String bioRaw) {
        this.bioRaw = bioRaw;
    }

    /**
     * Getter for BioCooked.
     * @return Returns the String
     */
    @JsonGetter("bio_cooked")
    public String getBioCooked() {
        return bioCooked;
    }

    /**
     * Setter for BioCooked.
     * @param bioCooked Value for String
     */
    @JsonSetter("bio_cooked")
    public void setBioCooked(String bioCooked) {
        this.bioCooked = bioCooked;
    }

    /**
     * Getter for BioExcerpt.
     * @return Returns the String
     */
    @JsonGetter("bio_excerpt")
    public String getBioExcerpt() {
        return bioExcerpt;
    }

    /**
     * Setter for BioExcerpt.
     * @param bioExcerpt Value for String
     */
    @JsonSetter("bio_excerpt")
    public void setBioExcerpt(String bioExcerpt) {
        this.bioExcerpt = bioExcerpt;
    }

    /**
     * Getter for PublicAdmission.
     * @return Returns the boolean
     */
    @JsonGetter("public_admission")
    public boolean getPublicAdmission() {
        return publicAdmission;
    }

    /**
     * Setter for PublicAdmission.
     * @param publicAdmission Value for boolean
     */
    @JsonSetter("public_admission")
    public void setPublicAdmission(boolean publicAdmission) {
        this.publicAdmission = publicAdmission;
    }

    /**
     * Getter for PublicExit.
     * @return Returns the boolean
     */
    @JsonGetter("public_exit")
    public boolean getPublicExit() {
        return publicExit;
    }

    /**
     * Setter for PublicExit.
     * @param publicExit Value for boolean
     */
    @JsonSetter("public_exit")
    public void setPublicExit(boolean publicExit) {
        this.publicExit = publicExit;
    }

    /**
     * Getter for AllowMembershipRequests.
     * @return Returns the boolean
     */
    @JsonGetter("allow_membership_requests")
    public boolean getAllowMembershipRequests() {
        return allowMembershipRequests;
    }

    /**
     * Setter for AllowMembershipRequests.
     * @param allowMembershipRequests Value for boolean
     */
    @JsonSetter("allow_membership_requests")
    public void setAllowMembershipRequests(boolean allowMembershipRequests) {
        this.allowMembershipRequests = allowMembershipRequests;
    }

    /**
     * Getter for FullName.
     * @return Returns the String
     */
    @JsonGetter("full_name")
    public String getFullName() {
        return fullName;
    }

    /**
     * Setter for FullName.
     * @param fullName Value for String
     */
    @JsonSetter("full_name")
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for DefaultNotificationLevel.
     * @return Returns the int
     */
    @JsonGetter("default_notification_level")
    public int getDefaultNotificationLevel() {
        return defaultNotificationLevel;
    }

    /**
     * Setter for DefaultNotificationLevel.
     * @param defaultNotificationLevel Value for int
     */
    @JsonSetter("default_notification_level")
    public void setDefaultNotificationLevel(int defaultNotificationLevel) {
        this.defaultNotificationLevel = defaultNotificationLevel;
    }

    /**
     * Getter for MembershipRequestTemplate.
     * @return Returns the String
     */
    @JsonGetter("membership_request_template")
    public String getMembershipRequestTemplate() {
        return membershipRequestTemplate;
    }

    /**
     * Setter for MembershipRequestTemplate.
     * @param membershipRequestTemplate Value for String
     */
    @JsonSetter("membership_request_template")
    public void setMembershipRequestTemplate(String membershipRequestTemplate) {
        this.membershipRequestTemplate = membershipRequestTemplate;
    }

    /**
     * Getter for IsGroupUser.
     * @return Returns the boolean
     */
    @JsonGetter("is_group_user")
    public boolean getIsGroupUser() {
        return isGroupUser;
    }

    /**
     * Setter for IsGroupUser.
     * @param isGroupUser Value for boolean
     */
    @JsonSetter("is_group_user")
    public void setIsGroupUser(boolean isGroupUser) {
        this.isGroupUser = isGroupUser;
    }

    /**
     * Getter for MembersVisibilityLevel.
     * @return Returns the int
     */
    @JsonGetter("members_visibility_level")
    public int getMembersVisibilityLevel() {
        return membersVisibilityLevel;
    }

    /**
     * Setter for MembersVisibilityLevel.
     * @param membersVisibilityLevel Value for int
     */
    @JsonSetter("members_visibility_level")
    public void setMembersVisibilityLevel(int membersVisibilityLevel) {
        this.membersVisibilityLevel = membersVisibilityLevel;
    }

    /**
     * Getter for CanSeeMembers.
     * @return Returns the boolean
     */
    @JsonGetter("can_see_members")
    public boolean getCanSeeMembers() {
        return canSeeMembers;
    }

    /**
     * Setter for CanSeeMembers.
     * @param canSeeMembers Value for boolean
     */
    @JsonSetter("can_see_members")
    public void setCanSeeMembers(boolean canSeeMembers) {
        this.canSeeMembers = canSeeMembers;
    }

    /**
     * Getter for CanAdminGroup.
     * @return Returns the boolean
     */
    @JsonGetter("can_admin_group")
    public boolean getCanAdminGroup() {
        return canAdminGroup;
    }

    /**
     * Setter for CanAdminGroup.
     * @param canAdminGroup Value for boolean
     */
    @JsonSetter("can_admin_group")
    public void setCanAdminGroup(boolean canAdminGroup) {
        this.canAdminGroup = canAdminGroup;
    }

    /**
     * Getter for CanEditGroup.
     * @return Returns the Boolean
     */
    @JsonGetter("can_edit_group")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getCanEditGroup() {
        return canEditGroup;
    }

    /**
     * Setter for CanEditGroup.
     * @param canEditGroup Value for Boolean
     */
    @JsonSetter("can_edit_group")
    public void setCanEditGroup(Boolean canEditGroup) {
        this.canEditGroup = canEditGroup;
    }

    /**
     * Getter for PublishReadState.
     * @return Returns the boolean
     */
    @JsonGetter("publish_read_state")
    public boolean getPublishReadState() {
        return publishReadState;
    }

    /**
     * Setter for PublishReadState.
     * @param publishReadState Value for boolean
     */
    @JsonSetter("publish_read_state")
    public void setPublishReadState(boolean publishReadState) {
        this.publishReadState = publishReadState;
    }

    /**
     * Getter for IsGroupOwnerDisplay.
     * @return Returns the boolean
     */
    @JsonGetter("is_group_owner_display")
    public boolean getIsGroupOwnerDisplay() {
        return isGroupOwnerDisplay;
    }

    /**
     * Setter for IsGroupOwnerDisplay.
     * @param isGroupOwnerDisplay Value for boolean
     */
    @JsonSetter("is_group_owner_display")
    public void setIsGroupOwnerDisplay(boolean isGroupOwnerDisplay) {
        this.isGroupOwnerDisplay = isGroupOwnerDisplay;
    }

    /**
     * Getter for Mentionable.
     * @return Returns the boolean
     */
    @JsonGetter("mentionable")
    public boolean getMentionable() {
        return mentionable;
    }

    /**
     * Setter for Mentionable.
     * @param mentionable Value for boolean
     */
    @JsonSetter("mentionable")
    public void setMentionable(boolean mentionable) {
        this.mentionable = mentionable;
    }

    /**
     * Getter for Messageable.
     * @return Returns the boolean
     */
    @JsonGetter("messageable")
    public boolean getMessageable() {
        return messageable;
    }

    /**
     * Setter for Messageable.
     * @param messageable Value for boolean
     */
    @JsonSetter("messageable")
    public void setMessageable(boolean messageable) {
        this.messageable = messageable;
    }

    /**
     * Getter for AutomaticMembershipEmailDomains.
     * @return Returns the String
     */
    @JsonGetter("automatic_membership_email_domains")
    public String getAutomaticMembershipEmailDomains() {
        return automaticMembershipEmailDomains;
    }

    /**
     * Setter for AutomaticMembershipEmailDomains.
     * @param automaticMembershipEmailDomains Value for String
     */
    @JsonSetter("automatic_membership_email_domains")
    public void setAutomaticMembershipEmailDomains(String automaticMembershipEmailDomains) {
        this.automaticMembershipEmailDomains = automaticMembershipEmailDomains;
    }

    /**
     * Internal Getter for SmtpUpdatedAt.
     * @return Returns the Internal String
     */
    @JsonGetter("smtp_updated_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetSmtpUpdatedAt() {
        return this.smtpUpdatedAt;
    }

    /**
     * Getter for SmtpUpdatedAt.
     * @return Returns the String
     */
    public String getSmtpUpdatedAt() {
        return OptionalNullable.getFrom(smtpUpdatedAt);
    }

    /**
     * Setter for SmtpUpdatedAt.
     * @param smtpUpdatedAt Value for String
     */
    @JsonSetter("smtp_updated_at")
    public void setSmtpUpdatedAt(String smtpUpdatedAt) {
        this.smtpUpdatedAt = OptionalNullable.of(smtpUpdatedAt);
    }

    /**
     * UnSetter for SmtpUpdatedAt.
     */
    public void unsetSmtpUpdatedAt() {
        smtpUpdatedAt = null;
    }

    /**
     * Internal Getter for SmtpUpdatedBy.
     * @return Returns the Internal Object
     */
    @JsonGetter("smtp_updated_by")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Object> internalGetSmtpUpdatedBy() {
        return this.smtpUpdatedBy;
    }

    /**
     * Getter for SmtpUpdatedBy.
     * @return Returns the Object
     */
    public Object getSmtpUpdatedBy() {
        return OptionalNullable.getFrom(smtpUpdatedBy);
    }

    /**
     * Setter for SmtpUpdatedBy.
     * @param smtpUpdatedBy Value for Object
     */
    @JsonSetter("smtp_updated_by")
    public void setSmtpUpdatedBy(Object smtpUpdatedBy) {
        this.smtpUpdatedBy = OptionalNullable.of(smtpUpdatedBy);
    }

    /**
     * UnSetter for SmtpUpdatedBy.
     */
    public void unsetSmtpUpdatedBy() {
        smtpUpdatedBy = null;
    }

    /**
     * Getter for SmtpEnabled.
     * @return Returns the Boolean
     */
    @JsonGetter("smtp_enabled")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getSmtpEnabled() {
        return smtpEnabled;
    }

    /**
     * Setter for SmtpEnabled.
     * @param smtpEnabled Value for Boolean
     */
    @JsonSetter("smtp_enabled")
    public void setSmtpEnabled(Boolean smtpEnabled) {
        this.smtpEnabled = smtpEnabled;
    }

    /**
     * Getter for SmtpServer.
     * @return Returns the String
     */
    @JsonGetter("smtp_server")
    public String getSmtpServer() {
        return smtpServer;
    }

    /**
     * Setter for SmtpServer.
     * @param smtpServer Value for String
     */
    @JsonSetter("smtp_server")
    public void setSmtpServer(String smtpServer) {
        this.smtpServer = smtpServer;
    }

    /**
     * Getter for SmtpPort.
     * @return Returns the String
     */
    @JsonGetter("smtp_port")
    public String getSmtpPort() {
        return smtpPort;
    }

    /**
     * Setter for SmtpPort.
     * @param smtpPort Value for String
     */
    @JsonSetter("smtp_port")
    public void setSmtpPort(String smtpPort) {
        this.smtpPort = smtpPort;
    }

    /**
     * Getter for SmtpSslMode.
     * @return Returns the Integer
     */
    @JsonGetter("smtp_ssl_mode")
    public Integer getSmtpSslMode() {
        return smtpSslMode;
    }

    /**
     * Setter for SmtpSslMode.
     * @param smtpSslMode Value for Integer
     */
    @JsonSetter("smtp_ssl_mode")
    public void setSmtpSslMode(Integer smtpSslMode) {
        this.smtpSslMode = smtpSslMode;
    }

    /**
     * Getter for EmailUsername.
     * @return Returns the String
     */
    @JsonGetter("email_username")
    public String getEmailUsername() {
        return emailUsername;
    }

    /**
     * Setter for EmailUsername.
     * @param emailUsername Value for String
     */
    @JsonSetter("email_username")
    public void setEmailUsername(String emailUsername) {
        this.emailUsername = emailUsername;
    }

    /**
     * Internal Getter for EmailFromAlias.
     * @return Returns the Internal String
     */
    @JsonGetter("email_from_alias")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetEmailFromAlias() {
        return this.emailFromAlias;
    }

    /**
     * Getter for EmailFromAlias.
     * @return Returns the String
     */
    public String getEmailFromAlias() {
        return OptionalNullable.getFrom(emailFromAlias);
    }

    /**
     * Setter for EmailFromAlias.
     * @param emailFromAlias Value for String
     */
    @JsonSetter("email_from_alias")
    public void setEmailFromAlias(String emailFromAlias) {
        this.emailFromAlias = OptionalNullable.of(emailFromAlias);
    }

    /**
     * UnSetter for EmailFromAlias.
     */
    public void unsetEmailFromAlias() {
        emailFromAlias = null;
    }

    /**
     * Getter for EmailPassword.
     * @return Returns the String
     */
    @JsonGetter("email_password")
    public String getEmailPassword() {
        return emailPassword;
    }

    /**
     * Setter for EmailPassword.
     * @param emailPassword Value for String
     */
    @JsonSetter("email_password")
    public void setEmailPassword(String emailPassword) {
        this.emailPassword = emailPassword;
    }

    /**
     * Getter for MessageCount.
     * @return Returns the int
     */
    @JsonGetter("message_count")
    public int getMessageCount() {
        return messageCount;
    }

    /**
     * Setter for MessageCount.
     * @param messageCount Value for int
     */
    @JsonSetter("message_count")
    public void setMessageCount(int messageCount) {
        this.messageCount = messageCount;
    }

    /**
     * Getter for AllowUnknownSenderTopicReplies.
     * @return Returns the boolean
     */
    @JsonGetter("allow_unknown_sender_topic_replies")
    public boolean getAllowUnknownSenderTopicReplies() {
        return allowUnknownSenderTopicReplies;
    }

    /**
     * Setter for AllowUnknownSenderTopicReplies.
     * @param allowUnknownSenderTopicReplies Value for boolean
     */
    @JsonSetter("allow_unknown_sender_topic_replies")
    public void setAllowUnknownSenderTopicReplies(boolean allowUnknownSenderTopicReplies) {
        this.allowUnknownSenderTopicReplies = allowUnknownSenderTopicReplies;
    }

    /**
     * Getter for AssociatedGroupIds.
     * @return Returns the List of Object
     */
    @JsonGetter("associated_group_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Object> getAssociatedGroupIds() {
        return associatedGroupIds;
    }

    /**
     * Setter for AssociatedGroupIds.
     * @param associatedGroupIds Value for List of Object
     */
    @JsonSetter("associated_group_ids")
    public void setAssociatedGroupIds(List<Object> associatedGroupIds) {
        this.associatedGroupIds = associatedGroupIds;
    }

    /**
     * Getter for WatchingCategoryIds.
     * @return Returns the List of Object
     */
    @JsonGetter("watching_category_ids")
    public List<Object> getWatchingCategoryIds() {
        return watchingCategoryIds;
    }

    /**
     * Setter for WatchingCategoryIds.
     * @param watchingCategoryIds Value for List of Object
     */
    @JsonSetter("watching_category_ids")
    public void setWatchingCategoryIds(List<Object> watchingCategoryIds) {
        this.watchingCategoryIds = watchingCategoryIds;
    }

    /**
     * Getter for TrackingCategoryIds.
     * @return Returns the List of Object
     */
    @JsonGetter("tracking_category_ids")
    public List<Object> getTrackingCategoryIds() {
        return trackingCategoryIds;
    }

    /**
     * Setter for TrackingCategoryIds.
     * @param trackingCategoryIds Value for List of Object
     */
    @JsonSetter("tracking_category_ids")
    public void setTrackingCategoryIds(List<Object> trackingCategoryIds) {
        this.trackingCategoryIds = trackingCategoryIds;
    }

    /**
     * Getter for WatchingFirstPostCategoryIds.
     * @return Returns the List of Object
     */
    @JsonGetter("watching_first_post_category_ids")
    public List<Object> getWatchingFirstPostCategoryIds() {
        return watchingFirstPostCategoryIds;
    }

    /**
     * Setter for WatchingFirstPostCategoryIds.
     * @param watchingFirstPostCategoryIds Value for List of Object
     */
    @JsonSetter("watching_first_post_category_ids")
    public void setWatchingFirstPostCategoryIds(List<Object> watchingFirstPostCategoryIds) {
        this.watchingFirstPostCategoryIds = watchingFirstPostCategoryIds;
    }

    /**
     * Getter for RegularCategoryIds.
     * @return Returns the List of Object
     */
    @JsonGetter("regular_category_ids")
    public List<Object> getRegularCategoryIds() {
        return regularCategoryIds;
    }

    /**
     * Setter for RegularCategoryIds.
     * @param regularCategoryIds Value for List of Object
     */
    @JsonSetter("regular_category_ids")
    public void setRegularCategoryIds(List<Object> regularCategoryIds) {
        this.regularCategoryIds = regularCategoryIds;
    }

    /**
     * Getter for MutedCategoryIds.
     * @return Returns the List of Object
     */
    @JsonGetter("muted_category_ids")
    public List<Object> getMutedCategoryIds() {
        return mutedCategoryIds;
    }

    /**
     * Setter for MutedCategoryIds.
     * @param mutedCategoryIds Value for List of Object
     */
    @JsonSetter("muted_category_ids")
    public void setMutedCategoryIds(List<Object> mutedCategoryIds) {
        this.mutedCategoryIds = mutedCategoryIds;
    }

    /**
     * Getter for WatchingTags.
     * @return Returns the List of Object
     */
    @JsonGetter("watching_tags")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Object> getWatchingTags() {
        return watchingTags;
    }

    /**
     * Setter for WatchingTags.
     * @param watchingTags Value for List of Object
     */
    @JsonSetter("watching_tags")
    public void setWatchingTags(List<Object> watchingTags) {
        this.watchingTags = watchingTags;
    }

    /**
     * Getter for WatchingFirstPostTags.
     * @return Returns the List of Object
     */
    @JsonGetter("watching_first_post_tags")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Object> getWatchingFirstPostTags() {
        return watchingFirstPostTags;
    }

    /**
     * Setter for WatchingFirstPostTags.
     * @param watchingFirstPostTags Value for List of Object
     */
    @JsonSetter("watching_first_post_tags")
    public void setWatchingFirstPostTags(List<Object> watchingFirstPostTags) {
        this.watchingFirstPostTags = watchingFirstPostTags;
    }

    /**
     * Getter for TrackingTags.
     * @return Returns the List of Object
     */
    @JsonGetter("tracking_tags")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Object> getTrackingTags() {
        return trackingTags;
    }

    /**
     * Setter for TrackingTags.
     * @param trackingTags Value for List of Object
     */
    @JsonSetter("tracking_tags")
    public void setTrackingTags(List<Object> trackingTags) {
        this.trackingTags = trackingTags;
    }

    /**
     * Getter for RegularTags.
     * @return Returns the List of Object
     */
    @JsonGetter("regular_tags")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Object> getRegularTags() {
        return regularTags;
    }

    /**
     * Setter for RegularTags.
     * @param regularTags Value for List of Object
     */
    @JsonSetter("regular_tags")
    public void setRegularTags(List<Object> regularTags) {
        this.regularTags = regularTags;
    }

    /**
     * Getter for MutedTags.
     * @return Returns the List of Object
     */
    @JsonGetter("muted_tags")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Object> getMutedTags() {
        return mutedTags;
    }

    /**
     * Setter for MutedTags.
     * @param mutedTags Value for List of Object
     */
    @JsonSetter("muted_tags")
    public void setMutedTags(List<Object> mutedTags) {
        this.mutedTags = mutedTags;
    }

    /**
     * Converts this Group1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Group1 [" + "id=" + id + ", automatic=" + automatic + ", name=" + name
                + ", mentionableLevel=" + mentionableLevel + ", messageableLevel="
                + messageableLevel + ", visibilityLevel=" + visibilityLevel + ", primaryGroup="
                + primaryGroup + ", title=" + title + ", grantTrustLevel=" + grantTrustLevel
                + ", incomingEmail=" + incomingEmail + ", hasMessages=" + hasMessages
                + ", flairUrl=" + flairUrl + ", flairBgColor=" + flairBgColor + ", flairColor="
                + flairColor + ", bioRaw=" + bioRaw + ", bioCooked=" + bioCooked + ", bioExcerpt="
                + bioExcerpt + ", publicAdmission=" + publicAdmission + ", publicExit=" + publicExit
                + ", allowMembershipRequests=" + allowMembershipRequests + ", fullName=" + fullName
                + ", defaultNotificationLevel=" + defaultNotificationLevel
                + ", membershipRequestTemplate=" + membershipRequestTemplate + ", isGroupUser="
                + isGroupUser + ", membersVisibilityLevel=" + membersVisibilityLevel
                + ", canSeeMembers=" + canSeeMembers + ", canAdminGroup=" + canAdminGroup
                + ", publishReadState=" + publishReadState + ", isGroupOwnerDisplay="
                + isGroupOwnerDisplay + ", mentionable=" + mentionable + ", messageable="
                + messageable + ", automaticMembershipEmailDomains="
                + automaticMembershipEmailDomains + ", smtpServer=" + smtpServer + ", smtpPort="
                + smtpPort + ", smtpSslMode=" + smtpSslMode + ", emailUsername=" + emailUsername
                + ", emailPassword=" + emailPassword + ", messageCount=" + messageCount
                + ", allowUnknownSenderTopicReplies=" + allowUnknownSenderTopicReplies
                + ", watchingCategoryIds=" + watchingCategoryIds + ", trackingCategoryIds="
                + trackingCategoryIds + ", watchingFirstPostCategoryIds="
                + watchingFirstPostCategoryIds + ", regularCategoryIds=" + regularCategoryIds
                + ", mutedCategoryIds=" + mutedCategoryIds + ", userCount=" + userCount
                + ", canEditGroup=" + canEditGroup + ", smtpUpdatedAt=" + smtpUpdatedAt
                + ", smtpUpdatedBy=" + smtpUpdatedBy + ", smtpEnabled=" + smtpEnabled
                + ", emailFromAlias=" + emailFromAlias + ", associatedGroupIds="
                + associatedGroupIds + ", watchingTags=" + watchingTags + ", watchingFirstPostTags="
                + watchingFirstPostTags + ", trackingTags=" + trackingTags + ", regularTags="
                + regularTags + ", mutedTags=" + mutedTags + "]";
    }

    /**
     * Builds a new {@link Group1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Group1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, automatic, name, mentionableLevel, messageableLevel,
                visibilityLevel, primaryGroup, title, grantTrustLevel, incomingEmail, hasMessages,
                flairUrl, flairBgColor, flairColor, bioRaw, bioCooked, bioExcerpt, publicAdmission,
                publicExit, allowMembershipRequests, fullName, defaultNotificationLevel,
                membershipRequestTemplate, isGroupUser, membersVisibilityLevel, canSeeMembers,
                canAdminGroup, publishReadState, isGroupOwnerDisplay, mentionable, messageable,
                automaticMembershipEmailDomains, smtpServer, smtpPort, smtpSslMode, emailUsername,
                emailPassword, messageCount, allowUnknownSenderTopicReplies, watchingCategoryIds,
                trackingCategoryIds, watchingFirstPostCategoryIds, regularCategoryIds,
                mutedCategoryIds)
                .userCount(getUserCount())
                .canEditGroup(getCanEditGroup())
                .smtpEnabled(getSmtpEnabled())
                .associatedGroupIds(getAssociatedGroupIds())
                .watchingTags(getWatchingTags())
                .watchingFirstPostTags(getWatchingFirstPostTags())
                .trackingTags(getTrackingTags())
                .regularTags(getRegularTags())
                .mutedTags(getMutedTags());
        builder.smtpUpdatedAt = internalGetSmtpUpdatedAt();
        builder.smtpUpdatedBy = internalGetSmtpUpdatedBy();
        builder.emailFromAlias = internalGetEmailFromAlias();
        return builder;
    }

    /**
     * Class to build instances of {@link Group1}.
     */
    public static class Builder {
        private int id;
        private boolean automatic;
        private String name;
        private int mentionableLevel;
        private int messageableLevel;
        private int visibilityLevel;
        private boolean primaryGroup;
        private String title;
        private String grantTrustLevel;
        private String incomingEmail;
        private boolean hasMessages;
        private String flairUrl;
        private String flairBgColor;
        private String flairColor;
        private String bioRaw;
        private String bioCooked;
        private String bioExcerpt;
        private boolean publicAdmission;
        private boolean publicExit;
        private boolean allowMembershipRequests;
        private String fullName;
        private int defaultNotificationLevel;
        private String membershipRequestTemplate;
        private boolean isGroupUser;
        private int membersVisibilityLevel;
        private boolean canSeeMembers;
        private boolean canAdminGroup;
        private boolean publishReadState;
        private boolean isGroupOwnerDisplay;
        private boolean mentionable;
        private boolean messageable;
        private String automaticMembershipEmailDomains;
        private String smtpServer;
        private String smtpPort;
        private Integer smtpSslMode;
        private String emailUsername;
        private String emailPassword;
        private int messageCount;
        private boolean allowUnknownSenderTopicReplies;
        private List<Object> watchingCategoryIds;
        private List<Object> trackingCategoryIds;
        private List<Object> watchingFirstPostCategoryIds;
        private List<Object> regularCategoryIds;
        private List<Object> mutedCategoryIds;
        private Integer userCount;
        private Boolean canEditGroup;
        private OptionalNullable<String> smtpUpdatedAt;
        private OptionalNullable<Object> smtpUpdatedBy;
        private Boolean smtpEnabled;
        private OptionalNullable<String> emailFromAlias;
        private List<Object> associatedGroupIds;
        private List<Object> watchingTags;
        private List<Object> watchingFirstPostTags;
        private List<Object> trackingTags;
        private List<Object> regularTags;
        private List<Object> mutedTags;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  automatic  boolean value for automatic.
         * @param  name  String value for name.
         * @param  mentionableLevel  int value for mentionableLevel.
         * @param  messageableLevel  int value for messageableLevel.
         * @param  visibilityLevel  int value for visibilityLevel.
         * @param  primaryGroup  boolean value for primaryGroup.
         * @param  title  String value for title.
         * @param  grantTrustLevel  String value for grantTrustLevel.
         * @param  incomingEmail  String value for incomingEmail.
         * @param  hasMessages  boolean value for hasMessages.
         * @param  flairUrl  String value for flairUrl.
         * @param  flairBgColor  String value for flairBgColor.
         * @param  flairColor  String value for flairColor.
         * @param  bioRaw  String value for bioRaw.
         * @param  bioCooked  String value for bioCooked.
         * @param  bioExcerpt  String value for bioExcerpt.
         * @param  publicAdmission  boolean value for publicAdmission.
         * @param  publicExit  boolean value for publicExit.
         * @param  allowMembershipRequests  boolean value for allowMembershipRequests.
         * @param  fullName  String value for fullName.
         * @param  defaultNotificationLevel  int value for defaultNotificationLevel.
         * @param  membershipRequestTemplate  String value for membershipRequestTemplate.
         * @param  isGroupUser  boolean value for isGroupUser.
         * @param  membersVisibilityLevel  int value for membersVisibilityLevel.
         * @param  canSeeMembers  boolean value for canSeeMembers.
         * @param  canAdminGroup  boolean value for canAdminGroup.
         * @param  publishReadState  boolean value for publishReadState.
         * @param  isGroupOwnerDisplay  boolean value for isGroupOwnerDisplay.
         * @param  mentionable  boolean value for mentionable.
         * @param  messageable  boolean value for messageable.
         * @param  automaticMembershipEmailDomains  String value for
         *         automaticMembershipEmailDomains.
         * @param  smtpServer  String value for smtpServer.
         * @param  smtpPort  String value for smtpPort.
         * @param  smtpSslMode  Integer value for smtpSslMode.
         * @param  emailUsername  String value for emailUsername.
         * @param  emailPassword  String value for emailPassword.
         * @param  messageCount  int value for messageCount.
         * @param  allowUnknownSenderTopicReplies  boolean value for allowUnknownSenderTopicReplies.
         * @param  watchingCategoryIds  List of Object value for watchingCategoryIds.
         * @param  trackingCategoryIds  List of Object value for trackingCategoryIds.
         * @param  watchingFirstPostCategoryIds  List of Object value for
         *         watchingFirstPostCategoryIds.
         * @param  regularCategoryIds  List of Object value for regularCategoryIds.
         * @param  mutedCategoryIds  List of Object value for mutedCategoryIds.
         */
        public Builder(int id, boolean automatic, String name, int mentionableLevel,
                int messageableLevel, int visibilityLevel, boolean primaryGroup, String title,
                String grantTrustLevel, String incomingEmail, boolean hasMessages, String flairUrl,
                String flairBgColor, String flairColor, String bioRaw, String bioCooked,
                String bioExcerpt, boolean publicAdmission, boolean publicExit,
                boolean allowMembershipRequests, String fullName, int defaultNotificationLevel,
                String membershipRequestTemplate, boolean isGroupUser, int membersVisibilityLevel,
                boolean canSeeMembers, boolean canAdminGroup, boolean publishReadState,
                boolean isGroupOwnerDisplay, boolean mentionable, boolean messageable,
                String automaticMembershipEmailDomains, String smtpServer, String smtpPort,
                Integer smtpSslMode, String emailUsername, String emailPassword, int messageCount,
                boolean allowUnknownSenderTopicReplies, List<Object> watchingCategoryIds,
                List<Object> trackingCategoryIds, List<Object> watchingFirstPostCategoryIds,
                List<Object> regularCategoryIds, List<Object> mutedCategoryIds) {
            this.id = id;
            this.automatic = automatic;
            this.name = name;
            this.mentionableLevel = mentionableLevel;
            this.messageableLevel = messageableLevel;
            this.visibilityLevel = visibilityLevel;
            this.primaryGroup = primaryGroup;
            this.title = title;
            this.grantTrustLevel = grantTrustLevel;
            this.incomingEmail = incomingEmail;
            this.hasMessages = hasMessages;
            this.flairUrl = flairUrl;
            this.flairBgColor = flairBgColor;
            this.flairColor = flairColor;
            this.bioRaw = bioRaw;
            this.bioCooked = bioCooked;
            this.bioExcerpt = bioExcerpt;
            this.publicAdmission = publicAdmission;
            this.publicExit = publicExit;
            this.allowMembershipRequests = allowMembershipRequests;
            this.fullName = fullName;
            this.defaultNotificationLevel = defaultNotificationLevel;
            this.membershipRequestTemplate = membershipRequestTemplate;
            this.isGroupUser = isGroupUser;
            this.membersVisibilityLevel = membersVisibilityLevel;
            this.canSeeMembers = canSeeMembers;
            this.canAdminGroup = canAdminGroup;
            this.publishReadState = publishReadState;
            this.isGroupOwnerDisplay = isGroupOwnerDisplay;
            this.mentionable = mentionable;
            this.messageable = messageable;
            this.automaticMembershipEmailDomains = automaticMembershipEmailDomains;
            this.smtpServer = smtpServer;
            this.smtpPort = smtpPort;
            this.smtpSslMode = smtpSslMode;
            this.emailUsername = emailUsername;
            this.emailPassword = emailPassword;
            this.messageCount = messageCount;
            this.allowUnknownSenderTopicReplies = allowUnknownSenderTopicReplies;
            this.watchingCategoryIds = watchingCategoryIds;
            this.trackingCategoryIds = trackingCategoryIds;
            this.watchingFirstPostCategoryIds = watchingFirstPostCategoryIds;
            this.regularCategoryIds = regularCategoryIds;
            this.mutedCategoryIds = mutedCategoryIds;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for automatic.
         * @param  automatic  boolean value for automatic.
         * @return Builder
         */
        public Builder automatic(boolean automatic) {
            this.automatic = automatic;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for mentionableLevel.
         * @param  mentionableLevel  int value for mentionableLevel.
         * @return Builder
         */
        public Builder mentionableLevel(int mentionableLevel) {
            this.mentionableLevel = mentionableLevel;
            return this;
        }

        /**
         * Setter for messageableLevel.
         * @param  messageableLevel  int value for messageableLevel.
         * @return Builder
         */
        public Builder messageableLevel(int messageableLevel) {
            this.messageableLevel = messageableLevel;
            return this;
        }

        /**
         * Setter for visibilityLevel.
         * @param  visibilityLevel  int value for visibilityLevel.
         * @return Builder
         */
        public Builder visibilityLevel(int visibilityLevel) {
            this.visibilityLevel = visibilityLevel;
            return this;
        }

        /**
         * Setter for primaryGroup.
         * @param  primaryGroup  boolean value for primaryGroup.
         * @return Builder
         */
        public Builder primaryGroup(boolean primaryGroup) {
            this.primaryGroup = primaryGroup;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for grantTrustLevel.
         * @param  grantTrustLevel  String value for grantTrustLevel.
         * @return Builder
         */
        public Builder grantTrustLevel(String grantTrustLevel) {
            this.grantTrustLevel = grantTrustLevel;
            return this;
        }

        /**
         * Setter for incomingEmail.
         * @param  incomingEmail  String value for incomingEmail.
         * @return Builder
         */
        public Builder incomingEmail(String incomingEmail) {
            this.incomingEmail = incomingEmail;
            return this;
        }

        /**
         * Setter for hasMessages.
         * @param  hasMessages  boolean value for hasMessages.
         * @return Builder
         */
        public Builder hasMessages(boolean hasMessages) {
            this.hasMessages = hasMessages;
            return this;
        }

        /**
         * Setter for flairUrl.
         * @param  flairUrl  String value for flairUrl.
         * @return Builder
         */
        public Builder flairUrl(String flairUrl) {
            this.flairUrl = flairUrl;
            return this;
        }

        /**
         * Setter for flairBgColor.
         * @param  flairBgColor  String value for flairBgColor.
         * @return Builder
         */
        public Builder flairBgColor(String flairBgColor) {
            this.flairBgColor = flairBgColor;
            return this;
        }

        /**
         * Setter for flairColor.
         * @param  flairColor  String value for flairColor.
         * @return Builder
         */
        public Builder flairColor(String flairColor) {
            this.flairColor = flairColor;
            return this;
        }

        /**
         * Setter for bioRaw.
         * @param  bioRaw  String value for bioRaw.
         * @return Builder
         */
        public Builder bioRaw(String bioRaw) {
            this.bioRaw = bioRaw;
            return this;
        }

        /**
         * Setter for bioCooked.
         * @param  bioCooked  String value for bioCooked.
         * @return Builder
         */
        public Builder bioCooked(String bioCooked) {
            this.bioCooked = bioCooked;
            return this;
        }

        /**
         * Setter for bioExcerpt.
         * @param  bioExcerpt  String value for bioExcerpt.
         * @return Builder
         */
        public Builder bioExcerpt(String bioExcerpt) {
            this.bioExcerpt = bioExcerpt;
            return this;
        }

        /**
         * Setter for publicAdmission.
         * @param  publicAdmission  boolean value for publicAdmission.
         * @return Builder
         */
        public Builder publicAdmission(boolean publicAdmission) {
            this.publicAdmission = publicAdmission;
            return this;
        }

        /**
         * Setter for publicExit.
         * @param  publicExit  boolean value for publicExit.
         * @return Builder
         */
        public Builder publicExit(boolean publicExit) {
            this.publicExit = publicExit;
            return this;
        }

        /**
         * Setter for allowMembershipRequests.
         * @param  allowMembershipRequests  boolean value for allowMembershipRequests.
         * @return Builder
         */
        public Builder allowMembershipRequests(boolean allowMembershipRequests) {
            this.allowMembershipRequests = allowMembershipRequests;
            return this;
        }

        /**
         * Setter for fullName.
         * @param  fullName  String value for fullName.
         * @return Builder
         */
        public Builder fullName(String fullName) {
            this.fullName = fullName;
            return this;
        }

        /**
         * Setter for defaultNotificationLevel.
         * @param  defaultNotificationLevel  int value for defaultNotificationLevel.
         * @return Builder
         */
        public Builder defaultNotificationLevel(int defaultNotificationLevel) {
            this.defaultNotificationLevel = defaultNotificationLevel;
            return this;
        }

        /**
         * Setter for membershipRequestTemplate.
         * @param  membershipRequestTemplate  String value for membershipRequestTemplate.
         * @return Builder
         */
        public Builder membershipRequestTemplate(String membershipRequestTemplate) {
            this.membershipRequestTemplate = membershipRequestTemplate;
            return this;
        }

        /**
         * Setter for isGroupUser.
         * @param  isGroupUser  boolean value for isGroupUser.
         * @return Builder
         */
        public Builder isGroupUser(boolean isGroupUser) {
            this.isGroupUser = isGroupUser;
            return this;
        }

        /**
         * Setter for membersVisibilityLevel.
         * @param  membersVisibilityLevel  int value for membersVisibilityLevel.
         * @return Builder
         */
        public Builder membersVisibilityLevel(int membersVisibilityLevel) {
            this.membersVisibilityLevel = membersVisibilityLevel;
            return this;
        }

        /**
         * Setter for canSeeMembers.
         * @param  canSeeMembers  boolean value for canSeeMembers.
         * @return Builder
         */
        public Builder canSeeMembers(boolean canSeeMembers) {
            this.canSeeMembers = canSeeMembers;
            return this;
        }

        /**
         * Setter for canAdminGroup.
         * @param  canAdminGroup  boolean value for canAdminGroup.
         * @return Builder
         */
        public Builder canAdminGroup(boolean canAdminGroup) {
            this.canAdminGroup = canAdminGroup;
            return this;
        }

        /**
         * Setter for publishReadState.
         * @param  publishReadState  boolean value for publishReadState.
         * @return Builder
         */
        public Builder publishReadState(boolean publishReadState) {
            this.publishReadState = publishReadState;
            return this;
        }

        /**
         * Setter for isGroupOwnerDisplay.
         * @param  isGroupOwnerDisplay  boolean value for isGroupOwnerDisplay.
         * @return Builder
         */
        public Builder isGroupOwnerDisplay(boolean isGroupOwnerDisplay) {
            this.isGroupOwnerDisplay = isGroupOwnerDisplay;
            return this;
        }

        /**
         * Setter for mentionable.
         * @param  mentionable  boolean value for mentionable.
         * @return Builder
         */
        public Builder mentionable(boolean mentionable) {
            this.mentionable = mentionable;
            return this;
        }

        /**
         * Setter for messageable.
         * @param  messageable  boolean value for messageable.
         * @return Builder
         */
        public Builder messageable(boolean messageable) {
            this.messageable = messageable;
            return this;
        }

        /**
         * Setter for automaticMembershipEmailDomains.
         * @param  automaticMembershipEmailDomains  String value for
         *         automaticMembershipEmailDomains.
         * @return Builder
         */
        public Builder automaticMembershipEmailDomains(String automaticMembershipEmailDomains) {
            this.automaticMembershipEmailDomains = automaticMembershipEmailDomains;
            return this;
        }

        /**
         * Setter for smtpServer.
         * @param  smtpServer  String value for smtpServer.
         * @return Builder
         */
        public Builder smtpServer(String smtpServer) {
            this.smtpServer = smtpServer;
            return this;
        }

        /**
         * Setter for smtpPort.
         * @param  smtpPort  String value for smtpPort.
         * @return Builder
         */
        public Builder smtpPort(String smtpPort) {
            this.smtpPort = smtpPort;
            return this;
        }

        /**
         * Setter for smtpSslMode.
         * @param  smtpSslMode  Integer value for smtpSslMode.
         * @return Builder
         */
        public Builder smtpSslMode(Integer smtpSslMode) {
            this.smtpSslMode = smtpSslMode;
            return this;
        }

        /**
         * Setter for emailUsername.
         * @param  emailUsername  String value for emailUsername.
         * @return Builder
         */
        public Builder emailUsername(String emailUsername) {
            this.emailUsername = emailUsername;
            return this;
        }

        /**
         * Setter for emailPassword.
         * @param  emailPassword  String value for emailPassword.
         * @return Builder
         */
        public Builder emailPassword(String emailPassword) {
            this.emailPassword = emailPassword;
            return this;
        }

        /**
         * Setter for messageCount.
         * @param  messageCount  int value for messageCount.
         * @return Builder
         */
        public Builder messageCount(int messageCount) {
            this.messageCount = messageCount;
            return this;
        }

        /**
         * Setter for allowUnknownSenderTopicReplies.
         * @param  allowUnknownSenderTopicReplies  boolean value for allowUnknownSenderTopicReplies.
         * @return Builder
         */
        public Builder allowUnknownSenderTopicReplies(boolean allowUnknownSenderTopicReplies) {
            this.allowUnknownSenderTopicReplies = allowUnknownSenderTopicReplies;
            return this;
        }

        /**
         * Setter for watchingCategoryIds.
         * @param  watchingCategoryIds  List of Object value for watchingCategoryIds.
         * @return Builder
         */
        public Builder watchingCategoryIds(List<Object> watchingCategoryIds) {
            this.watchingCategoryIds = watchingCategoryIds;
            return this;
        }

        /**
         * Setter for trackingCategoryIds.
         * @param  trackingCategoryIds  List of Object value for trackingCategoryIds.
         * @return Builder
         */
        public Builder trackingCategoryIds(List<Object> trackingCategoryIds) {
            this.trackingCategoryIds = trackingCategoryIds;
            return this;
        }

        /**
         * Setter for watchingFirstPostCategoryIds.
         * @param  watchingFirstPostCategoryIds  List of Object value for
         *         watchingFirstPostCategoryIds.
         * @return Builder
         */
        public Builder watchingFirstPostCategoryIds(List<Object> watchingFirstPostCategoryIds) {
            this.watchingFirstPostCategoryIds = watchingFirstPostCategoryIds;
            return this;
        }

        /**
         * Setter for regularCategoryIds.
         * @param  regularCategoryIds  List of Object value for regularCategoryIds.
         * @return Builder
         */
        public Builder regularCategoryIds(List<Object> regularCategoryIds) {
            this.regularCategoryIds = regularCategoryIds;
            return this;
        }

        /**
         * Setter for mutedCategoryIds.
         * @param  mutedCategoryIds  List of Object value for mutedCategoryIds.
         * @return Builder
         */
        public Builder mutedCategoryIds(List<Object> mutedCategoryIds) {
            this.mutedCategoryIds = mutedCategoryIds;
            return this;
        }

        /**
         * Setter for userCount.
         * @param  userCount  Integer value for userCount.
         * @return Builder
         */
        public Builder userCount(Integer userCount) {
            this.userCount = userCount;
            return this;
        }

        /**
         * Setter for canEditGroup.
         * @param  canEditGroup  Boolean value for canEditGroup.
         * @return Builder
         */
        public Builder canEditGroup(Boolean canEditGroup) {
            this.canEditGroup = canEditGroup;
            return this;
        }

        /**
         * Setter for smtpUpdatedAt.
         * @param  smtpUpdatedAt  String value for smtpUpdatedAt.
         * @return Builder
         */
        public Builder smtpUpdatedAt(String smtpUpdatedAt) {
            this.smtpUpdatedAt = OptionalNullable.of(smtpUpdatedAt);
            return this;
        }

        /**
         * UnSetter for smtpUpdatedAt.
         * @return Builder
         */
        public Builder unsetSmtpUpdatedAt() {
            smtpUpdatedAt = null;
            return this;
        }

        /**
         * Setter for smtpUpdatedBy.
         * @param  smtpUpdatedBy  Object value for smtpUpdatedBy.
         * @return Builder
         */
        public Builder smtpUpdatedBy(Object smtpUpdatedBy) {
            this.smtpUpdatedBy = OptionalNullable.of(smtpUpdatedBy);
            return this;
        }

        /**
         * UnSetter for smtpUpdatedBy.
         * @return Builder
         */
        public Builder unsetSmtpUpdatedBy() {
            smtpUpdatedBy = null;
            return this;
        }

        /**
         * Setter for smtpEnabled.
         * @param  smtpEnabled  Boolean value for smtpEnabled.
         * @return Builder
         */
        public Builder smtpEnabled(Boolean smtpEnabled) {
            this.smtpEnabled = smtpEnabled;
            return this;
        }

        /**
         * Setter for emailFromAlias.
         * @param  emailFromAlias  String value for emailFromAlias.
         * @return Builder
         */
        public Builder emailFromAlias(String emailFromAlias) {
            this.emailFromAlias = OptionalNullable.of(emailFromAlias);
            return this;
        }

        /**
         * UnSetter for emailFromAlias.
         * @return Builder
         */
        public Builder unsetEmailFromAlias() {
            emailFromAlias = null;
            return this;
        }

        /**
         * Setter for associatedGroupIds.
         * @param  associatedGroupIds  List of Object value for associatedGroupIds.
         * @return Builder
         */
        public Builder associatedGroupIds(List<Object> associatedGroupIds) {
            this.associatedGroupIds = associatedGroupIds;
            return this;
        }

        /**
         * Setter for watchingTags.
         * @param  watchingTags  List of Object value for watchingTags.
         * @return Builder
         */
        public Builder watchingTags(List<Object> watchingTags) {
            this.watchingTags = watchingTags;
            return this;
        }

        /**
         * Setter for watchingFirstPostTags.
         * @param  watchingFirstPostTags  List of Object value for watchingFirstPostTags.
         * @return Builder
         */
        public Builder watchingFirstPostTags(List<Object> watchingFirstPostTags) {
            this.watchingFirstPostTags = watchingFirstPostTags;
            return this;
        }

        /**
         * Setter for trackingTags.
         * @param  trackingTags  List of Object value for trackingTags.
         * @return Builder
         */
        public Builder trackingTags(List<Object> trackingTags) {
            this.trackingTags = trackingTags;
            return this;
        }

        /**
         * Setter for regularTags.
         * @param  regularTags  List of Object value for regularTags.
         * @return Builder
         */
        public Builder regularTags(List<Object> regularTags) {
            this.regularTags = regularTags;
            return this;
        }

        /**
         * Setter for mutedTags.
         * @param  mutedTags  List of Object value for mutedTags.
         * @return Builder
         */
        public Builder mutedTags(List<Object> mutedTags) {
            this.mutedTags = mutedTags;
            return this;
        }

        /**
         * Builds a new {@link Group1} object using the set fields.
         * @return {@link Group1}
         */
        public Group1 build() {
            return new Group1(id, automatic, name, mentionableLevel, messageableLevel,
                    visibilityLevel, primaryGroup, title, grantTrustLevel, incomingEmail,
                    hasMessages, flairUrl, flairBgColor, flairColor, bioRaw, bioCooked, bioExcerpt,
                    publicAdmission, publicExit, allowMembershipRequests, fullName,
                    defaultNotificationLevel, membershipRequestTemplate, isGroupUser,
                    membersVisibilityLevel, canSeeMembers, canAdminGroup, publishReadState,
                    isGroupOwnerDisplay, mentionable, messageable, automaticMembershipEmailDomains,
                    smtpServer, smtpPort, smtpSslMode, emailUsername, emailPassword, messageCount,
                    allowUnknownSenderTopicReplies, watchingCategoryIds, trackingCategoryIds,
                    watchingFirstPostCategoryIds, regularCategoryIds, mutedCategoryIds, userCount,
                    canEditGroup, smtpUpdatedAt, smtpUpdatedBy, smtpEnabled, emailFromAlias,
                    associatedGroupIds, watchingTags, watchingFirstPostTags, trackingTags,
                    regularTags, mutedTags);
        }
    }
}
