/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GroupsJsonRequest type.
 */
public class GroupsJsonRequest {
    private Group group;

    /**
     * Default constructor.
     */
    public GroupsJsonRequest() {
    }

    /**
     * Initialization constructor.
     * @param  group  Group value for group.
     */
    public GroupsJsonRequest(
            Group group) {
        this.group = group;
    }

    /**
     * Getter for Group.
     * @return Returns the Group
     */
    @JsonGetter("group")
    public Group getGroup() {
        return group;
    }

    /**
     * Setter for Group.
     * @param group Value for Group
     */
    @JsonSetter("group")
    public void setGroup(Group group) {
        this.group = group;
    }

    /**
     * Converts this GroupsJsonRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GroupsJsonRequest [" + "group=" + group + "]";
    }

    /**
     * Builds a new {@link GroupsJsonRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GroupsJsonRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(group);
        return builder;
    }

    /**
     * Class to build instances of {@link GroupsJsonRequest}.
     */
    public static class Builder {
        private Group group;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  group  Group value for group.
         */
        public Builder(Group group) {
            this.group = group;
        }

        /**
         * Setter for group.
         * @param  group  Group value for group.
         * @return Builder
         */
        public Builder group(Group group) {
            this.group = group;
            return this;
        }

        /**
         * Builds a new {@link GroupsJsonRequest} object using the set fields.
         * @return {@link GroupsJsonRequest}
         */
        public GroupsJsonRequest build() {
            return new GroupsJsonRequest(group);
        }
    }
}
