/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for NotificationsJsonResponse type.
 */
public class NotificationsJsonResponse {
    private List<Notification> notifications;
    private Integer totalRowsNotifications;
    private Integer seenNotificationId;
    private String loadMoreNotifications;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public NotificationsJsonResponse() {
    }

    /**
     * Initialization constructor.
     * @param  notifications  List of Notification value for notifications.
     * @param  totalRowsNotifications  Integer value for totalRowsNotifications.
     * @param  seenNotificationId  Integer value for seenNotificationId.
     * @param  loadMoreNotifications  String value for loadMoreNotifications.
     */
    public NotificationsJsonResponse(
            List<Notification> notifications,
            Integer totalRowsNotifications,
            Integer seenNotificationId,
            String loadMoreNotifications) {
        this.notifications = notifications;
        this.totalRowsNotifications = totalRowsNotifications;
        this.seenNotificationId = seenNotificationId;
        this.loadMoreNotifications = loadMoreNotifications;
    }

    /**
     * Getter for Notifications.
     * @return Returns the List of Notification
     */
    @JsonGetter("notifications")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Notification> getNotifications() {
        return notifications;
    }

    /**
     * Setter for Notifications.
     * @param notifications Value for List of Notification
     */
    @JsonSetter("notifications")
    public void setNotifications(List<Notification> notifications) {
        this.notifications = notifications;
    }

    /**
     * Getter for TotalRowsNotifications.
     * @return Returns the Integer
     */
    @JsonGetter("total_rows_notifications")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTotalRowsNotifications() {
        return totalRowsNotifications;
    }

    /**
     * Setter for TotalRowsNotifications.
     * @param totalRowsNotifications Value for Integer
     */
    @JsonSetter("total_rows_notifications")
    public void setTotalRowsNotifications(Integer totalRowsNotifications) {
        this.totalRowsNotifications = totalRowsNotifications;
    }

    /**
     * Getter for SeenNotificationId.
     * @return Returns the Integer
     */
    @JsonGetter("seen_notification_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getSeenNotificationId() {
        return seenNotificationId;
    }

    /**
     * Setter for SeenNotificationId.
     * @param seenNotificationId Value for Integer
     */
    @JsonSetter("seen_notification_id")
    public void setSeenNotificationId(Integer seenNotificationId) {
        this.seenNotificationId = seenNotificationId;
    }

    /**
     * Getter for LoadMoreNotifications.
     * @return Returns the String
     */
    @JsonGetter("load_more_notifications")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLoadMoreNotifications() {
        return loadMoreNotifications;
    }

    /**
     * Setter for LoadMoreNotifications.
     * @param loadMoreNotifications Value for String
     */
    @JsonSetter("load_more_notifications")
    public void setLoadMoreNotifications(String loadMoreNotifications) {
        this.loadMoreNotifications = loadMoreNotifications;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this NotificationsJsonResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NotificationsJsonResponse [" + "notifications=" + notifications
                + ", totalRowsNotifications=" + totalRowsNotifications + ", seenNotificationId="
                + seenNotificationId + ", loadMoreNotifications=" + loadMoreNotifications
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link NotificationsJsonResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NotificationsJsonResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .notifications(getNotifications())
                .totalRowsNotifications(getTotalRowsNotifications())
                .seenNotificationId(getSeenNotificationId())
                .loadMoreNotifications(getLoadMoreNotifications());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link NotificationsJsonResponse}.
     */
    public static class Builder {
        private List<Notification> notifications;
        private Integer totalRowsNotifications;
        private Integer seenNotificationId;
        private String loadMoreNotifications;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for notifications.
         * @param  notifications  List of Notification value for notifications.
         * @return Builder
         */
        public Builder notifications(List<Notification> notifications) {
            this.notifications = notifications;
            return this;
        }

        /**
         * Setter for totalRowsNotifications.
         * @param  totalRowsNotifications  Integer value for totalRowsNotifications.
         * @return Builder
         */
        public Builder totalRowsNotifications(Integer totalRowsNotifications) {
            this.totalRowsNotifications = totalRowsNotifications;
            return this;
        }

        /**
         * Setter for seenNotificationId.
         * @param  seenNotificationId  Integer value for seenNotificationId.
         * @return Builder
         */
        public Builder seenNotificationId(Integer seenNotificationId) {
            this.seenNotificationId = seenNotificationId;
            return this;
        }

        /**
         * Setter for loadMoreNotifications.
         * @param  loadMoreNotifications  String value for loadMoreNotifications.
         * @return Builder
         */
        public Builder loadMoreNotifications(String loadMoreNotifications) {
            this.loadMoreNotifications = loadMoreNotifications;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link NotificationsJsonResponse} object using the set fields.
         * @return {@link NotificationsJsonResponse}
         */
        public NotificationsJsonResponse build() {
            NotificationsJsonResponse model =
                    new NotificationsJsonResponse(notifications, totalRowsNotifications,
                            seenNotificationId, loadMoreNotifications);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
