/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for PostsJsonResponse type.
 */
public class PostsJsonResponse {
    private List<LatestPost> latestPosts;

    /**
     * Default constructor.
     */
    public PostsJsonResponse() {
    }

    /**
     * Initialization constructor.
     * @param  latestPosts  List of LatestPost value for latestPosts.
     */
    public PostsJsonResponse(
            List<LatestPost> latestPosts) {
        this.latestPosts = latestPosts;
    }

    /**
     * Getter for LatestPosts.
     * @return Returns the List of LatestPost
     */
    @JsonGetter("latest_posts")
    public List<LatestPost> getLatestPosts() {
        return latestPosts;
    }

    /**
     * Setter for LatestPosts.
     * @param latestPosts Value for List of LatestPost
     */
    @JsonSetter("latest_posts")
    public void setLatestPosts(List<LatestPost> latestPosts) {
        this.latestPosts = latestPosts;
    }

    /**
     * Converts this PostsJsonResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PostsJsonResponse [" + "latestPosts=" + latestPosts + "]";
    }

    /**
     * Builds a new {@link PostsJsonResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PostsJsonResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(latestPosts);
        return builder;
    }

    /**
     * Class to build instances of {@link PostsJsonResponse}.
     */
    public static class Builder {
        private List<LatestPost> latestPosts;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  latestPosts  List of LatestPost value for latestPosts.
         */
        public Builder(List<LatestPost> latestPosts) {
            this.latestPosts = latestPosts;
        }

        /**
         * Setter for latestPosts.
         * @param  latestPosts  List of LatestPost value for latestPosts.
         * @return Builder
         */
        public Builder latestPosts(List<LatestPost> latestPosts) {
            this.latestPosts = latestPosts;
            return this;
        }

        /**
         * Builds a new {@link PostsJsonResponse} object using the set fields.
         * @return {@link PostsJsonResponse}
         */
        public PostsJsonResponse build() {
            return new PostsJsonResponse(latestPosts);
        }
    }
}
