/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for PostStream1 type.
 */
public class PostStream1 {
    private List<Post4> posts;
    private List<Object> stream;

    /**
     * Default constructor.
     */
    public PostStream1() {
    }

    /**
     * Initialization constructor.
     * @param  posts  List of Post4 value for posts.
     * @param  stream  List of Object value for stream.
     */
    public PostStream1(
            List<Post4> posts,
            List<Object> stream) {
        this.posts = posts;
        this.stream = stream;
    }

    /**
     * Getter for Posts.
     * @return Returns the List of Post4
     */
    @JsonGetter("posts")
    public List<Post4> getPosts() {
        return posts;
    }

    /**
     * Setter for Posts.
     * @param posts Value for List of Post4
     */
    @JsonSetter("posts")
    public void setPosts(List<Post4> posts) {
        this.posts = posts;
    }

    /**
     * Getter for Stream.
     * @return Returns the List of Object
     */
    @JsonGetter("stream")
    public List<Object> getStream() {
        return stream;
    }

    /**
     * Setter for Stream.
     * @param stream Value for List of Object
     */
    @JsonSetter("stream")
    public void setStream(List<Object> stream) {
        this.stream = stream;
    }

    /**
     * Converts this PostStream1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PostStream1 [" + "posts=" + posts + ", stream=" + stream + "]";
    }

    /**
     * Builds a new {@link PostStream1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PostStream1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(posts, stream);
        return builder;
    }

    /**
     * Class to build instances of {@link PostStream1}.
     */
    public static class Builder {
        private List<Post4> posts;
        private List<Object> stream;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  posts  List of Post4 value for posts.
         * @param  stream  List of Object value for stream.
         */
        public Builder(List<Post4> posts, List<Object> stream) {
            this.posts = posts;
            this.stream = stream;
        }

        /**
         * Setter for posts.
         * @param  posts  List of Post4 value for posts.
         * @return Builder
         */
        public Builder posts(List<Post4> posts) {
            this.posts = posts;
            return this;
        }

        /**
         * Setter for stream.
         * @param  stream  List of Object value for stream.
         * @return Builder
         */
        public Builder stream(List<Object> stream) {
            this.stream = stream;
            return this;
        }

        /**
         * Builds a new {@link PostStream1} object using the set fields.
         * @return {@link PostStream1}
         */
        public PostStream1 build() {
            return new PostStream1(posts, stream);
        }
    }
}
