/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for PostStream type.
 */
public class PostStream {
    private List<Post3> posts;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PostStream() {
    }

    /**
     * Initialization constructor.
     * @param  posts  List of Post3 value for posts.
     */
    public PostStream(
            List<Post3> posts) {
        this.posts = posts;
    }

    /**
     * Getter for Posts.
     * @return Returns the List of Post3
     */
    @JsonGetter("posts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Post3> getPosts() {
        return posts;
    }

    /**
     * Setter for Posts.
     * @param posts Value for List of Post3
     */
    @JsonSetter("posts")
    public void setPosts(List<Post3> posts) {
        this.posts = posts;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PostStream into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PostStream [" + "posts=" + posts + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link PostStream.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PostStream.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .posts(getPosts());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PostStream}.
     */
    public static class Builder {
        private List<Post3> posts;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for posts.
         * @param  posts  List of Post3 value for posts.
         * @return Builder
         */
        public Builder posts(List<Post3> posts) {
            this.posts = posts;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PostStream} object using the set fields.
         * @return {@link PostStream}
         */
        public PostStream build() {
            PostStream model =
                    new PostStream(posts);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
