/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PostsJsonRequest type.
 */
public class PostsJsonRequest {
    private String title;
    private String raw;
    private Integer topicId;
    private Integer category;
    private String targetRecipients;
    private String targetUsernames;
    private String archetype;
    private String createdAt;
    private Integer replyToPostNumber;
    private String embedUrl;
    private String externalId;
    private Boolean autoTrack;

    /**
     * Default constructor.
     */
    public PostsJsonRequest() {
    }

    /**
     * Initialization constructor.
     * @param  raw  String value for raw.
     * @param  title  String value for title.
     * @param  topicId  Integer value for topicId.
     * @param  category  Integer value for category.
     * @param  targetRecipients  String value for targetRecipients.
     * @param  targetUsernames  String value for targetUsernames.
     * @param  archetype  String value for archetype.
     * @param  createdAt  String value for createdAt.
     * @param  replyToPostNumber  Integer value for replyToPostNumber.
     * @param  embedUrl  String value for embedUrl.
     * @param  externalId  String value for externalId.
     * @param  autoTrack  Boolean value for autoTrack.
     */
    public PostsJsonRequest(
            String raw,
            String title,
            Integer topicId,
            Integer category,
            String targetRecipients,
            String targetUsernames,
            String archetype,
            String createdAt,
            Integer replyToPostNumber,
            String embedUrl,
            String externalId,
            Boolean autoTrack) {
        this.title = title;
        this.raw = raw;
        this.topicId = topicId;
        this.category = category;
        this.targetRecipients = targetRecipients;
        this.targetUsernames = targetUsernames;
        this.archetype = archetype;
        this.createdAt = createdAt;
        this.replyToPostNumber = replyToPostNumber;
        this.embedUrl = embedUrl;
        this.externalId = externalId;
        this.autoTrack = autoTrack;
    }

    /**
     * Getter for Title.
     * Required if creating a new topic or new private message.
     * @return Returns the String
     */
    @JsonGetter("title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * Required if creating a new topic or new private message.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for Raw.
     * @return Returns the String
     */
    @JsonGetter("raw")
    public String getRaw() {
        return raw;
    }

    /**
     * Setter for Raw.
     * @param raw Value for String
     */
    @JsonSetter("raw")
    public void setRaw(String raw) {
        this.raw = raw;
    }

    /**
     * Getter for TopicId.
     * Required if creating a new post.
     * @return Returns the Integer
     */
    @JsonGetter("topic_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * Setter for TopicId.
     * Required if creating a new post.
     * @param topicId Value for Integer
     */
    @JsonSetter("topic_id")
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * Getter for Category.
     * Optional if creating a new topic, and ignored if creating a new post.
     * @return Returns the Integer
     */
    @JsonGetter("category")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCategory() {
        return category;
    }

    /**
     * Setter for Category.
     * Optional if creating a new topic, and ignored if creating a new post.
     * @param category Value for Integer
     */
    @JsonSetter("category")
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * Getter for TargetRecipients.
     * Required for private message, comma separated.
     * @return Returns the String
     */
    @JsonGetter("target_recipients")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTargetRecipients() {
        return targetRecipients;
    }

    /**
     * Setter for TargetRecipients.
     * Required for private message, comma separated.
     * @param targetRecipients Value for String
     */
    @JsonSetter("target_recipients")
    public void setTargetRecipients(String targetRecipients) {
        this.targetRecipients = targetRecipients;
    }

    /**
     * Getter for TargetUsernames.
     * Deprecated. Use target_recipients instead.
     * @return Returns the String
     */
    @JsonGetter("target_usernames")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTargetUsernames() {
        return targetUsernames;
    }

    /**
     * Setter for TargetUsernames.
     * Deprecated. Use target_recipients instead.
     * @param targetUsernames Value for String
     */
    @JsonSetter("target_usernames")
    public void setTargetUsernames(String targetUsernames) {
        this.targetUsernames = targetUsernames;
    }

    /**
     * Getter for Archetype.
     * Required for new private message.
     * @return Returns the String
     */
    @JsonGetter("archetype")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getArchetype() {
        return archetype;
    }

    /**
     * Setter for Archetype.
     * Required for new private message.
     * @param archetype Value for String
     */
    @JsonSetter("archetype")
    public void setArchetype(String archetype) {
        this.archetype = archetype;
    }

    /**
     * Getter for CreatedAt.
     * @return Returns the String
     */
    @JsonGetter("created_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * @param createdAt Value for String
     */
    @JsonSetter("created_at")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for ReplyToPostNumber.
     * Optional, the post number to reply to inside a topic.
     * @return Returns the Integer
     */
    @JsonGetter("reply_to_post_number")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getReplyToPostNumber() {
        return replyToPostNumber;
    }

    /**
     * Setter for ReplyToPostNumber.
     * Optional, the post number to reply to inside a topic.
     * @param replyToPostNumber Value for Integer
     */
    @JsonSetter("reply_to_post_number")
    public void setReplyToPostNumber(Integer replyToPostNumber) {
        this.replyToPostNumber = replyToPostNumber;
    }

    /**
     * Getter for EmbedUrl.
     * Provide a URL from a remote system to associate a forum topic with that URL, typically for
     * using Discourse as a comments system for an external blog.
     * @return Returns the String
     */
    @JsonGetter("embed_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEmbedUrl() {
        return embedUrl;
    }

    /**
     * Setter for EmbedUrl.
     * Provide a URL from a remote system to associate a forum topic with that URL, typically for
     * using Discourse as a comments system for an external blog.
     * @param embedUrl Value for String
     */
    @JsonSetter("embed_url")
    public void setEmbedUrl(String embedUrl) {
        this.embedUrl = embedUrl;
    }

    /**
     * Getter for ExternalId.
     * Provide an external_id from a remote system to associate a forum topic with that id.
     * @return Returns the String
     */
    @JsonGetter("external_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExternalId() {
        return externalId;
    }

    /**
     * Setter for ExternalId.
     * Provide an external_id from a remote system to associate a forum topic with that id.
     * @param externalId Value for String
     */
    @JsonSetter("external_id")
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * Getter for AutoTrack.
     * If false, the user will not track the topic. By default, the user will track the topic.
     * @return Returns the Boolean
     */
    @JsonGetter("auto_track")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getAutoTrack() {
        return autoTrack;
    }

    /**
     * Setter for AutoTrack.
     * If false, the user will not track the topic. By default, the user will track the topic.
     * @param autoTrack Value for Boolean
     */
    @JsonSetter("auto_track")
    public void setAutoTrack(Boolean autoTrack) {
        this.autoTrack = autoTrack;
    }

    /**
     * Converts this PostsJsonRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PostsJsonRequest [" + "raw=" + raw + ", title=" + title + ", topicId=" + topicId
                + ", category=" + category + ", targetRecipients=" + targetRecipients
                + ", targetUsernames=" + targetUsernames + ", archetype=" + archetype
                + ", createdAt=" + createdAt + ", replyToPostNumber=" + replyToPostNumber
                + ", embedUrl=" + embedUrl + ", externalId=" + externalId + ", autoTrack="
                + autoTrack + "]";
    }

    /**
     * Builds a new {@link PostsJsonRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PostsJsonRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(raw)
                .title(getTitle())
                .topicId(getTopicId())
                .category(getCategory())
                .targetRecipients(getTargetRecipients())
                .targetUsernames(getTargetUsernames())
                .archetype(getArchetype())
                .createdAt(getCreatedAt())
                .replyToPostNumber(getReplyToPostNumber())
                .embedUrl(getEmbedUrl())
                .externalId(getExternalId())
                .autoTrack(getAutoTrack());
        return builder;
    }

    /**
     * Class to build instances of {@link PostsJsonRequest}.
     */
    public static class Builder {
        private String raw;
        private String title;
        private Integer topicId;
        private Integer category;
        private String targetRecipients;
        private String targetUsernames;
        private String archetype;
        private String createdAt;
        private Integer replyToPostNumber;
        private String embedUrl;
        private String externalId;
        private Boolean autoTrack;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  raw  String value for raw.
         */
        public Builder(String raw) {
            this.raw = raw;
        }

        /**
         * Setter for raw.
         * @param  raw  String value for raw.
         * @return Builder
         */
        public Builder raw(String raw) {
            this.raw = raw;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for topicId.
         * @param  topicId  Integer value for topicId.
         * @return Builder
         */
        public Builder topicId(Integer topicId) {
            this.topicId = topicId;
            return this;
        }

        /**
         * Setter for category.
         * @param  category  Integer value for category.
         * @return Builder
         */
        public Builder category(Integer category) {
            this.category = category;
            return this;
        }

        /**
         * Setter for targetRecipients.
         * @param  targetRecipients  String value for targetRecipients.
         * @return Builder
         */
        public Builder targetRecipients(String targetRecipients) {
            this.targetRecipients = targetRecipients;
            return this;
        }

        /**
         * Setter for targetUsernames.
         * @param  targetUsernames  String value for targetUsernames.
         * @return Builder
         */
        public Builder targetUsernames(String targetUsernames) {
            this.targetUsernames = targetUsernames;
            return this;
        }

        /**
         * Setter for archetype.
         * @param  archetype  String value for archetype.
         * @return Builder
         */
        public Builder archetype(String archetype) {
            this.archetype = archetype;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for replyToPostNumber.
         * @param  replyToPostNumber  Integer value for replyToPostNumber.
         * @return Builder
         */
        public Builder replyToPostNumber(Integer replyToPostNumber) {
            this.replyToPostNumber = replyToPostNumber;
            return this;
        }

        /**
         * Setter for embedUrl.
         * @param  embedUrl  String value for embedUrl.
         * @return Builder
         */
        public Builder embedUrl(String embedUrl) {
            this.embedUrl = embedUrl;
            return this;
        }

        /**
         * Setter for externalId.
         * @param  externalId  String value for externalId.
         * @return Builder
         */
        public Builder externalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        /**
         * Setter for autoTrack.
         * @param  autoTrack  Boolean value for autoTrack.
         * @return Builder
         */
        public Builder autoTrack(Boolean autoTrack) {
            this.autoTrack = autoTrack;
            return this;
        }

        /**
         * Builds a new {@link PostsJsonRequest} object using the set fields.
         * @return {@link PostsJsonRequest}
         */
        public PostsJsonRequest build() {
            return new PostsJsonRequest(raw, title, topicId, category, targetRecipients,
                    targetUsernames, archetype, createdAt, replyToPostNumber, embedUrl, externalId,
                    autoTrack);
        }
    }
}
