/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Reminder type.
 */
public class Reminder {
    private int value;
    private String unit;
    private Period period;
    private String type;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Reminder() {
    }

    /**
     * Initialization constructor.
     * @param  value  int value for value.
     * @param  unit  String value for unit.
     * @param  period  Period value for period.
     * @param  type  String value for type.
     */
    public Reminder(
            int value,
            String unit,
            Period period,
            String type) {
        this.value = value;
        this.unit = unit;
        this.period = period;
        this.type = type;
    }

    /**
     * Getter for Value.
     * @return Returns the int
     */
    @JsonGetter("value")
    public int getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * @param value Value for int
     */
    @JsonSetter("value")
    public void setValue(int value) {
        this.value = value;
    }

    /**
     * Getter for Unit.
     * @return Returns the String
     */
    @JsonGetter("unit")
    public String getUnit() {
        return unit;
    }

    /**
     * Setter for Unit.
     * @param unit Value for String
     */
    @JsonSetter("unit")
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * Getter for Period.
     * @return Returns the Period
     */
    @JsonGetter("period")
    public Period getPeriod() {
        return period;
    }

    /**
     * Setter for Period.
     * @param period Value for Period
     */
    @JsonSetter("period")
    public void setPeriod(Period period) {
        this.period = period;
    }

    /**
     * Getter for Type.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Reminder into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Reminder [" + "value=" + value + ", unit=" + unit + ", period=" + period + ", type="
                + type + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Reminder.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Reminder.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(value, unit, period, type);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Reminder}.
     */
    public static class Builder {
        private int value;
        private String unit;
        private Period period;
        private String type;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  value  int value for value.
         * @param  unit  String value for unit.
         * @param  period  Period value for period.
         * @param  type  String value for type.
         */
        public Builder(int value, String unit, Period period, String type) {
            this.value = value;
            this.unit = unit;
            this.period = period;
            this.type = type;
        }

        /**
         * Setter for value.
         * @param  value  int value for value.
         * @return Builder
         */
        public Builder value(int value) {
            this.value = value;
            return this;
        }

        /**
         * Setter for unit.
         * @param  unit  String value for unit.
         * @return Builder
         */
        public Builder unit(String unit) {
            this.unit = unit;
            return this;
        }

        /**
         * Setter for period.
         * @param  period  Period value for period.
         * @return Builder
         */
        public Builder period(Period period) {
            this.period = period;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Reminder} object using the set fields.
         * @return {@link Reminder}
         */
        public Reminder build() {
            Reminder model =
                    new Reminder(value, unit, period, type);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
