/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RequiredTagGroup type.
 */
public class RequiredTagGroup {
    private String name;
    private int minCount;

    /**
     * Default constructor.
     */
    public RequiredTagGroup() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  minCount  int value for minCount.
     */
    public RequiredTagGroup(
            String name,
            int minCount) {
        this.name = name;
        this.minCount = minCount;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for MinCount.
     * @return Returns the int
     */
    @JsonGetter("min_count")
    public int getMinCount() {
        return minCount;
    }

    /**
     * Setter for MinCount.
     * @param minCount Value for int
     */
    @JsonSetter("min_count")
    public void setMinCount(int minCount) {
        this.minCount = minCount;
    }

    /**
     * Converts this RequiredTagGroup into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RequiredTagGroup [" + "name=" + name + ", minCount=" + minCount + "]";
    }

    /**
     * Builds a new {@link RequiredTagGroup.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RequiredTagGroup.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name, minCount);
        return builder;
    }

    /**
     * Class to build instances of {@link RequiredTagGroup}.
     */
    public static class Builder {
        private String name;
        private int minCount;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  String value for name.
         * @param  minCount  int value for minCount.
         */
        public Builder(String name, int minCount) {
            this.name = name;
            this.minCount = minCount;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for minCount.
         * @param  minCount  int value for minCount.
         * @return Builder
         */
        public Builder minCount(int minCount) {
            this.minCount = minCount;
            return this;
        }

        /**
         * Builds a new {@link RequiredTagGroup} object using the set fields.
         * @return {@link RequiredTagGroup}
         */
        public RequiredTagGroup build() {
            return new RequiredTagGroup(name, minCount);
        }
    }
}
