/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for TagGroupsJsonResponse3 type.
 */
public class TagGroupsJsonResponse3 {
    private String success;
    private TagGroup2 tagGroup;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public TagGroupsJsonResponse3() {
    }

    /**
     * Initialization constructor.
     * @param  success  String value for success.
     * @param  tagGroup  TagGroup2 value for tagGroup.
     */
    public TagGroupsJsonResponse3(
            String success,
            TagGroup2 tagGroup) {
        this.success = success;
        this.tagGroup = tagGroup;
    }

    /**
     * Getter for Success.
     * @return Returns the String
     */
    @JsonGetter("success")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSuccess() {
        return success;
    }

    /**
     * Setter for Success.
     * @param success Value for String
     */
    @JsonSetter("success")
    public void setSuccess(String success) {
        this.success = success;
    }

    /**
     * Getter for TagGroup.
     * @return Returns the TagGroup2
     */
    @JsonGetter("tag_group")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TagGroup2 getTagGroup() {
        return tagGroup;
    }

    /**
     * Setter for TagGroup.
     * @param tagGroup Value for TagGroup2
     */
    @JsonSetter("tag_group")
    public void setTagGroup(TagGroup2 tagGroup) {
        this.tagGroup = tagGroup;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this TagGroupsJsonResponse3 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TagGroupsJsonResponse3 [" + "success=" + success + ", tagGroup=" + tagGroup
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link TagGroupsJsonResponse3.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TagGroupsJsonResponse3.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .success(getSuccess())
                .tagGroup(getTagGroup());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link TagGroupsJsonResponse3}.
     */
    public static class Builder {
        private String success;
        private TagGroup2 tagGroup;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for success.
         * @param  success  String value for success.
         * @return Builder
         */
        public Builder success(String success) {
            this.success = success;
            return this;
        }

        /**
         * Setter for tagGroup.
         * @param  tagGroup  TagGroup2 value for tagGroup.
         * @return Builder
         */
        public Builder tagGroup(TagGroup2 tagGroup) {
            this.tagGroup = tagGroup;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link TagGroupsJsonResponse3} object using the set fields.
         * @return {@link TagGroupsJsonResponse3}
         */
        public TagGroupsJsonResponse3 build() {
            TagGroupsJsonResponse3 model =
                    new TagGroupsJsonResponse3(success, tagGroup);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
