/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for TJsonResponse1 type.
 */
public class TJsonResponse1 {
    private BasicTopic basicTopic;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public TJsonResponse1() {
    }

    /**
     * Initialization constructor.
     * @param  basicTopic  BasicTopic value for basicTopic.
     */
    public TJsonResponse1(
            BasicTopic basicTopic) {
        this.basicTopic = basicTopic;
    }

    /**
     * Getter for BasicTopic.
     * @return Returns the BasicTopic
     */
    @JsonGetter("basic_topic")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BasicTopic getBasicTopic() {
        return basicTopic;
    }

    /**
     * Setter for BasicTopic.
     * @param basicTopic Value for BasicTopic
     */
    @JsonSetter("basic_topic")
    public void setBasicTopic(BasicTopic basicTopic) {
        this.basicTopic = basicTopic;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this TJsonResponse1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TJsonResponse1 [" + "basicTopic=" + basicTopic + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link TJsonResponse1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TJsonResponse1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .basicTopic(getBasicTopic());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link TJsonResponse1}.
     */
    public static class Builder {
        private BasicTopic basicTopic;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for basicTopic.
         * @param  basicTopic  BasicTopic value for basicTopic.
         * @return Builder
         */
        public Builder basicTopic(BasicTopic basicTopic) {
            this.basicTopic = basicTopic;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link TJsonResponse1} object using the set fields.
         * @return {@link TJsonResponse1}
         */
        public TJsonResponse1 build() {
            TJsonResponse1 model =
                    new TJsonResponse1(basicTopic);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
