/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for TopicsPrivateMessagesSentJsonResponse type.
 */
public class TopicsPrivateMessagesSentJsonResponse {
    private List<User2> users;
    private List<Object> primaryGroups;
    private TopicList2 topicList;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public TopicsPrivateMessagesSentJsonResponse() {
    }

    /**
     * Initialization constructor.
     * @param  users  List of User2 value for users.
     * @param  primaryGroups  List of Object value for primaryGroups.
     * @param  topicList  TopicList2 value for topicList.
     */
    public TopicsPrivateMessagesSentJsonResponse(
            List<User2> users,
            List<Object> primaryGroups,
            TopicList2 topicList) {
        this.users = users;
        this.primaryGroups = primaryGroups;
        this.topicList = topicList;
    }

    /**
     * Getter for Users.
     * @return Returns the List of User2
     */
    @JsonGetter("users")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<User2> getUsers() {
        return users;
    }

    /**
     * Setter for Users.
     * @param users Value for List of User2
     */
    @JsonSetter("users")
    public void setUsers(List<User2> users) {
        this.users = users;
    }

    /**
     * Getter for PrimaryGroups.
     * @return Returns the List of Object
     */
    @JsonGetter("primary_groups")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Object> getPrimaryGroups() {
        return primaryGroups;
    }

    /**
     * Setter for PrimaryGroups.
     * @param primaryGroups Value for List of Object
     */
    @JsonSetter("primary_groups")
    public void setPrimaryGroups(List<Object> primaryGroups) {
        this.primaryGroups = primaryGroups;
    }

    /**
     * Getter for TopicList.
     * @return Returns the TopicList2
     */
    @JsonGetter("topic_list")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TopicList2 getTopicList() {
        return topicList;
    }

    /**
     * Setter for TopicList.
     * @param topicList Value for TopicList2
     */
    @JsonSetter("topic_list")
    public void setTopicList(TopicList2 topicList) {
        this.topicList = topicList;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this TopicsPrivateMessagesSentJsonResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TopicsPrivateMessagesSentJsonResponse [" + "users=" + users + ", primaryGroups="
                + primaryGroups + ", topicList=" + topicList + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link TopicsPrivateMessagesSentJsonResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TopicsPrivateMessagesSentJsonResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .users(getUsers())
                .primaryGroups(getPrimaryGroups())
                .topicList(getTopicList());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link TopicsPrivateMessagesSentJsonResponse}.
     */
    public static class Builder {
        private List<User2> users;
        private List<Object> primaryGroups;
        private TopicList2 topicList;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for users.
         * @param  users  List of User2 value for users.
         * @return Builder
         */
        public Builder users(List<User2> users) {
            this.users = users;
            return this;
        }

        /**
         * Setter for primaryGroups.
         * @param  primaryGroups  List of Object value for primaryGroups.
         * @return Builder
         */
        public Builder primaryGroups(List<Object> primaryGroups) {
            this.primaryGroups = primaryGroups;
            return this;
        }

        /**
         * Setter for topicList.
         * @param  topicList  TopicList2 value for topicList.
         * @return Builder
         */
        public Builder topicList(TopicList2 topicList) {
            this.topicList = topicList;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link TopicsPrivateMessagesSentJsonResponse} object using the set fields.
         * @return {@link TopicsPrivateMessagesSentJsonResponse}
         */
        public TopicsPrivateMessagesSentJsonResponse build() {
            TopicsPrivateMessagesSentJsonResponse model =
                    new TopicsPrivateMessagesSentJsonResponse(users, primaryGroups, topicList);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
