/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for UpcomingChangesStat type.
 */
public class UpcomingChangesStat {
    private String name;
    private String humanizedName;
    private String description;
    private boolean enabled;
    private List<String> specificGroups;
    private Reason reason;

    /**
     * Default constructor.
     */
    public UpcomingChangesStat() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  humanizedName  String value for humanizedName.
     * @param  description  String value for description.
     * @param  enabled  boolean value for enabled.
     * @param  specificGroups  List of String value for specificGroups.
     * @param  reason  Reason value for reason.
     */
    public UpcomingChangesStat(
            String name,
            String humanizedName,
            String description,
            boolean enabled,
            List<String> specificGroups,
            Reason reason) {
        this.name = name;
        this.humanizedName = humanizedName;
        this.description = description;
        this.enabled = enabled;
        this.specificGroups = specificGroups;
        this.reason = reason;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for HumanizedName.
     * @return Returns the String
     */
    @JsonGetter("humanized_name")
    public String getHumanizedName() {
        return humanizedName;
    }

    /**
     * Setter for HumanizedName.
     * @param humanizedName Value for String
     */
    @JsonSetter("humanized_name")
    public void setHumanizedName(String humanizedName) {
        this.humanizedName = humanizedName;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Enabled.
     * @return Returns the boolean
     */
    @JsonGetter("enabled")
    public boolean getEnabled() {
        return enabled;
    }

    /**
     * Setter for Enabled.
     * @param enabled Value for boolean
     */
    @JsonSetter("enabled")
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Getter for SpecificGroups.
     * @return Returns the List of String
     */
    @JsonGetter("specific_groups")
    public List<String> getSpecificGroups() {
        return specificGroups;
    }

    /**
     * Setter for SpecificGroups.
     * @param specificGroups Value for List of String
     */
    @JsonSetter("specific_groups")
    public void setSpecificGroups(List<String> specificGroups) {
        this.specificGroups = specificGroups;
    }

    /**
     * Getter for Reason.
     * @return Returns the Reason
     */
    @JsonGetter("reason")
    public Reason getReason() {
        return reason;
    }

    /**
     * Setter for Reason.
     * @param reason Value for Reason
     */
    @JsonSetter("reason")
    public void setReason(Reason reason) {
        this.reason = reason;
    }

    /**
     * Converts this UpcomingChangesStat into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpcomingChangesStat [" + "name=" + name + ", humanizedName=" + humanizedName
                + ", description=" + description + ", enabled=" + enabled + ", specificGroups="
                + specificGroups + ", reason=" + reason + "]";
    }

    /**
     * Builds a new {@link UpcomingChangesStat.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpcomingChangesStat.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name, humanizedName, description, enabled, specificGroups,
                reason);
        return builder;
    }

    /**
     * Class to build instances of {@link UpcomingChangesStat}.
     */
    public static class Builder {
        private String name;
        private String humanizedName;
        private String description;
        private boolean enabled;
        private List<String> specificGroups;
        private Reason reason;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  String value for name.
         * @param  humanizedName  String value for humanizedName.
         * @param  description  String value for description.
         * @param  enabled  boolean value for enabled.
         * @param  specificGroups  List of String value for specificGroups.
         * @param  reason  Reason value for reason.
         */
        public Builder(String name, String humanizedName, String description, boolean enabled,
                List<String> specificGroups, Reason reason) {
            this.name = name;
            this.humanizedName = humanizedName;
            this.description = description;
            this.enabled = enabled;
            this.specificGroups = specificGroups;
            this.reason = reason;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for humanizedName.
         * @param  humanizedName  String value for humanizedName.
         * @return Builder
         */
        public Builder humanizedName(String humanizedName) {
            this.humanizedName = humanizedName;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for enabled.
         * @param  enabled  boolean value for enabled.
         * @return Builder
         */
        public Builder enabled(boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /**
         * Setter for specificGroups.
         * @param  specificGroups  List of String value for specificGroups.
         * @return Builder
         */
        public Builder specificGroups(List<String> specificGroups) {
            this.specificGroups = specificGroups;
            return this;
        }

        /**
         * Setter for reason.
         * @param  reason  Reason value for reason.
         * @return Builder
         */
        public Builder reason(Reason reason) {
            this.reason = reason;
            return this;
        }

        /**
         * Builds a new {@link UpcomingChangesStat} object using the set fields.
         * @return {@link UpcomingChangesStat}
         */
        public UpcomingChangesStat build() {
            return new UpcomingChangesStat(name, humanizedName, description, enabled,
                    specificGroups, reason);
        }
    }
}
