/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for UploadsCompleteMultipartJsonResponse type.
 */
public class UploadsCompleteMultipartJsonResponse {
    private int id;
    private String url;
    private String originalFilename;
    private int filesize;
    private int width;
    private int height;
    private int thumbnailWidth;
    private int thumbnailHeight;
    private String extension;
    private String shortUrl;
    private String shortPath;
    private String retainHours;
    private String humanFilesize;
    private OptionalNullable<String> dominantColor;
    private OptionalNullable<Thumbnail> thumbnail;
    private OptionalNullable<OptimizedVideo> optimizedVideo;

    /**
     * Default constructor.
     */
    public UploadsCompleteMultipartJsonResponse() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  url  String value for url.
     * @param  originalFilename  String value for originalFilename.
     * @param  filesize  int value for filesize.
     * @param  width  int value for width.
     * @param  height  int value for height.
     * @param  thumbnailWidth  int value for thumbnailWidth.
     * @param  thumbnailHeight  int value for thumbnailHeight.
     * @param  extension  String value for extension.
     * @param  shortUrl  String value for shortUrl.
     * @param  shortPath  String value for shortPath.
     * @param  retainHours  String value for retainHours.
     * @param  humanFilesize  String value for humanFilesize.
     * @param  dominantColor  String value for dominantColor.
     * @param  thumbnail  Thumbnail value for thumbnail.
     * @param  optimizedVideo  OptimizedVideo value for optimizedVideo.
     */
    public UploadsCompleteMultipartJsonResponse(
            int id,
            String url,
            String originalFilename,
            int filesize,
            int width,
            int height,
            int thumbnailWidth,
            int thumbnailHeight,
            String extension,
            String shortUrl,
            String shortPath,
            String retainHours,
            String humanFilesize,
            String dominantColor,
            Thumbnail thumbnail,
            OptimizedVideo optimizedVideo) {
        this.id = id;
        this.url = url;
        this.originalFilename = originalFilename;
        this.filesize = filesize;
        this.width = width;
        this.height = height;
        this.thumbnailWidth = thumbnailWidth;
        this.thumbnailHeight = thumbnailHeight;
        this.extension = extension;
        this.shortUrl = shortUrl;
        this.shortPath = shortPath;
        this.retainHours = retainHours;
        this.humanFilesize = humanFilesize;
        this.dominantColor = OptionalNullable.of(dominantColor);
        this.thumbnail = OptionalNullable.of(thumbnail);
        this.optimizedVideo = OptionalNullable.of(optimizedVideo);
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  url  String value for url.
     * @param  originalFilename  String value for originalFilename.
     * @param  filesize  int value for filesize.
     * @param  width  int value for width.
     * @param  height  int value for height.
     * @param  thumbnailWidth  int value for thumbnailWidth.
     * @param  thumbnailHeight  int value for thumbnailHeight.
     * @param  extension  String value for extension.
     * @param  shortUrl  String value for shortUrl.
     * @param  shortPath  String value for shortPath.
     * @param  retainHours  String value for retainHours.
     * @param  humanFilesize  String value for humanFilesize.
     * @param  dominantColor  String value for dominantColor.
     * @param  thumbnail  Thumbnail value for thumbnail.
     * @param  optimizedVideo  OptimizedVideo value for optimizedVideo.
     */

    protected UploadsCompleteMultipartJsonResponse(int id, String url, String originalFilename,
            int filesize, int width, int height, int thumbnailWidth, int thumbnailHeight,
            String extension, String shortUrl, String shortPath, String retainHours,
            String humanFilesize, OptionalNullable<String> dominantColor,
            OptionalNullable<Thumbnail> thumbnail,
            OptionalNullable<OptimizedVideo> optimizedVideo) {
        this.id = id;
        this.url = url;
        this.originalFilename = originalFilename;
        this.filesize = filesize;
        this.width = width;
        this.height = height;
        this.thumbnailWidth = thumbnailWidth;
        this.thumbnailHeight = thumbnailHeight;
        this.extension = extension;
        this.shortUrl = shortUrl;
        this.shortPath = shortPath;
        this.retainHours = retainHours;
        this.humanFilesize = humanFilesize;
        this.dominantColor = dominantColor;
        this.thumbnail = thumbnail;
        this.optimizedVideo = optimizedVideo;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for Url.
     * @return Returns the String
     */
    @JsonGetter("url")
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for OriginalFilename.
     * @return Returns the String
     */
    @JsonGetter("original_filename")
    public String getOriginalFilename() {
        return originalFilename;
    }

    /**
     * Setter for OriginalFilename.
     * @param originalFilename Value for String
     */
    @JsonSetter("original_filename")
    public void setOriginalFilename(String originalFilename) {
        this.originalFilename = originalFilename;
    }

    /**
     * Getter for Filesize.
     * @return Returns the int
     */
    @JsonGetter("filesize")
    public int getFilesize() {
        return filesize;
    }

    /**
     * Setter for Filesize.
     * @param filesize Value for int
     */
    @JsonSetter("filesize")
    public void setFilesize(int filesize) {
        this.filesize = filesize;
    }

    /**
     * Getter for Width.
     * @return Returns the int
     */
    @JsonGetter("width")
    public int getWidth() {
        return width;
    }

    /**
     * Setter for Width.
     * @param width Value for int
     */
    @JsonSetter("width")
    public void setWidth(int width) {
        this.width = width;
    }

    /**
     * Getter for Height.
     * @return Returns the int
     */
    @JsonGetter("height")
    public int getHeight() {
        return height;
    }

    /**
     * Setter for Height.
     * @param height Value for int
     */
    @JsonSetter("height")
    public void setHeight(int height) {
        this.height = height;
    }

    /**
     * Getter for ThumbnailWidth.
     * @return Returns the int
     */
    @JsonGetter("thumbnail_width")
    public int getThumbnailWidth() {
        return thumbnailWidth;
    }

    /**
     * Setter for ThumbnailWidth.
     * @param thumbnailWidth Value for int
     */
    @JsonSetter("thumbnail_width")
    public void setThumbnailWidth(int thumbnailWidth) {
        this.thumbnailWidth = thumbnailWidth;
    }

    /**
     * Getter for ThumbnailHeight.
     * @return Returns the int
     */
    @JsonGetter("thumbnail_height")
    public int getThumbnailHeight() {
        return thumbnailHeight;
    }

    /**
     * Setter for ThumbnailHeight.
     * @param thumbnailHeight Value for int
     */
    @JsonSetter("thumbnail_height")
    public void setThumbnailHeight(int thumbnailHeight) {
        this.thumbnailHeight = thumbnailHeight;
    }

    /**
     * Getter for Extension.
     * @return Returns the String
     */
    @JsonGetter("extension")
    public String getExtension() {
        return extension;
    }

    /**
     * Setter for Extension.
     * @param extension Value for String
     */
    @JsonSetter("extension")
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Getter for ShortUrl.
     * @return Returns the String
     */
    @JsonGetter("short_url")
    public String getShortUrl() {
        return shortUrl;
    }

    /**
     * Setter for ShortUrl.
     * @param shortUrl Value for String
     */
    @JsonSetter("short_url")
    public void setShortUrl(String shortUrl) {
        this.shortUrl = shortUrl;
    }

    /**
     * Getter for ShortPath.
     * @return Returns the String
     */
    @JsonGetter("short_path")
    public String getShortPath() {
        return shortPath;
    }

    /**
     * Setter for ShortPath.
     * @param shortPath Value for String
     */
    @JsonSetter("short_path")
    public void setShortPath(String shortPath) {
        this.shortPath = shortPath;
    }

    /**
     * Getter for RetainHours.
     * @return Returns the String
     */
    @JsonGetter("retain_hours")
    public String getRetainHours() {
        return retainHours;
    }

    /**
     * Setter for RetainHours.
     * @param retainHours Value for String
     */
    @JsonSetter("retain_hours")
    public void setRetainHours(String retainHours) {
        this.retainHours = retainHours;
    }

    /**
     * Getter for HumanFilesize.
     * @return Returns the String
     */
    @JsonGetter("human_filesize")
    public String getHumanFilesize() {
        return humanFilesize;
    }

    /**
     * Setter for HumanFilesize.
     * @param humanFilesize Value for String
     */
    @JsonSetter("human_filesize")
    public void setHumanFilesize(String humanFilesize) {
        this.humanFilesize = humanFilesize;
    }

    /**
     * Internal Getter for DominantColor.
     * @return Returns the Internal String
     */
    @JsonGetter("dominant_color")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDominantColor() {
        return this.dominantColor;
    }

    /**
     * Getter for DominantColor.
     * @return Returns the String
     */
    public String getDominantColor() {
        return OptionalNullable.getFrom(dominantColor);
    }

    /**
     * Setter for DominantColor.
     * @param dominantColor Value for String
     */
    @JsonSetter("dominant_color")
    public void setDominantColor(String dominantColor) {
        this.dominantColor = OptionalNullable.of(dominantColor);
    }

    /**
     * UnSetter for DominantColor.
     */
    public void unsetDominantColor() {
        dominantColor = null;
    }

    /**
     * Internal Getter for Thumbnail.
     * @return Returns the Internal Thumbnail
     */
    @JsonGetter("thumbnail")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Thumbnail> internalGetThumbnail() {
        return this.thumbnail;
    }

    /**
     * Getter for Thumbnail.
     * @return Returns the Thumbnail
     */
    public Thumbnail getThumbnail() {
        return OptionalNullable.getFrom(thumbnail);
    }

    /**
     * Setter for Thumbnail.
     * @param thumbnail Value for Thumbnail
     */
    @JsonSetter("thumbnail")
    public void setThumbnail(Thumbnail thumbnail) {
        this.thumbnail = OptionalNullable.of(thumbnail);
    }

    /**
     * UnSetter for Thumbnail.
     */
    public void unsetThumbnail() {
        thumbnail = null;
    }

    /**
     * Internal Getter for OptimizedVideo.
     * @return Returns the Internal OptimizedVideo
     */
    @JsonGetter("optimized_video")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<OptimizedVideo> internalGetOptimizedVideo() {
        return this.optimizedVideo;
    }

    /**
     * Getter for OptimizedVideo.
     * @return Returns the OptimizedVideo
     */
    public OptimizedVideo getOptimizedVideo() {
        return OptionalNullable.getFrom(optimizedVideo);
    }

    /**
     * Setter for OptimizedVideo.
     * @param optimizedVideo Value for OptimizedVideo
     */
    @JsonSetter("optimized_video")
    public void setOptimizedVideo(OptimizedVideo optimizedVideo) {
        this.optimizedVideo = OptionalNullable.of(optimizedVideo);
    }

    /**
     * UnSetter for OptimizedVideo.
     */
    public void unsetOptimizedVideo() {
        optimizedVideo = null;
    }

    /**
     * Converts this UploadsCompleteMultipartJsonResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UploadsCompleteMultipartJsonResponse [" + "id=" + id + ", url=" + url
                + ", originalFilename=" + originalFilename + ", filesize=" + filesize + ", width="
                + width + ", height=" + height + ", thumbnailWidth=" + thumbnailWidth
                + ", thumbnailHeight=" + thumbnailHeight + ", extension=" + extension
                + ", shortUrl=" + shortUrl + ", shortPath=" + shortPath + ", retainHours="
                + retainHours + ", humanFilesize=" + humanFilesize + ", dominantColor="
                + dominantColor + ", thumbnail=" + thumbnail + ", optimizedVideo=" + optimizedVideo
                + "]";
    }

    /**
     * Builds a new {@link UploadsCompleteMultipartJsonResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UploadsCompleteMultipartJsonResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, url, originalFilename, filesize, width, height,
                thumbnailWidth, thumbnailHeight, extension, shortUrl, shortPath, retainHours,
                humanFilesize);
        builder.dominantColor = internalGetDominantColor();
        builder.thumbnail = internalGetThumbnail();
        builder.optimizedVideo = internalGetOptimizedVideo();
        return builder;
    }

    /**
     * Class to build instances of {@link UploadsCompleteMultipartJsonResponse}.
     */
    public static class Builder {
        private int id;
        private String url;
        private String originalFilename;
        private int filesize;
        private int width;
        private int height;
        private int thumbnailWidth;
        private int thumbnailHeight;
        private String extension;
        private String shortUrl;
        private String shortPath;
        private String retainHours;
        private String humanFilesize;
        private OptionalNullable<String> dominantColor;
        private OptionalNullable<Thumbnail> thumbnail;
        private OptionalNullable<OptimizedVideo> optimizedVideo;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  url  String value for url.
         * @param  originalFilename  String value for originalFilename.
         * @param  filesize  int value for filesize.
         * @param  width  int value for width.
         * @param  height  int value for height.
         * @param  thumbnailWidth  int value for thumbnailWidth.
         * @param  thumbnailHeight  int value for thumbnailHeight.
         * @param  extension  String value for extension.
         * @param  shortUrl  String value for shortUrl.
         * @param  shortPath  String value for shortPath.
         * @param  retainHours  String value for retainHours.
         * @param  humanFilesize  String value for humanFilesize.
         */
        public Builder(int id, String url, String originalFilename, int filesize, int width,
                int height, int thumbnailWidth, int thumbnailHeight, String extension,
                String shortUrl, String shortPath, String retainHours, String humanFilesize) {
            this.id = id;
            this.url = url;
            this.originalFilename = originalFilename;
            this.filesize = filesize;
            this.width = width;
            this.height = height;
            this.thumbnailWidth = thumbnailWidth;
            this.thumbnailHeight = thumbnailHeight;
            this.extension = extension;
            this.shortUrl = shortUrl;
            this.shortPath = shortPath;
            this.retainHours = retainHours;
            this.humanFilesize = humanFilesize;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for originalFilename.
         * @param  originalFilename  String value for originalFilename.
         * @return Builder
         */
        public Builder originalFilename(String originalFilename) {
            this.originalFilename = originalFilename;
            return this;
        }

        /**
         * Setter for filesize.
         * @param  filesize  int value for filesize.
         * @return Builder
         */
        public Builder filesize(int filesize) {
            this.filesize = filesize;
            return this;
        }

        /**
         * Setter for width.
         * @param  width  int value for width.
         * @return Builder
         */
        public Builder width(int width) {
            this.width = width;
            return this;
        }

        /**
         * Setter for height.
         * @param  height  int value for height.
         * @return Builder
         */
        public Builder height(int height) {
            this.height = height;
            return this;
        }

        /**
         * Setter for thumbnailWidth.
         * @param  thumbnailWidth  int value for thumbnailWidth.
         * @return Builder
         */
        public Builder thumbnailWidth(int thumbnailWidth) {
            this.thumbnailWidth = thumbnailWidth;
            return this;
        }

        /**
         * Setter for thumbnailHeight.
         * @param  thumbnailHeight  int value for thumbnailHeight.
         * @return Builder
         */
        public Builder thumbnailHeight(int thumbnailHeight) {
            this.thumbnailHeight = thumbnailHeight;
            return this;
        }

        /**
         * Setter for extension.
         * @param  extension  String value for extension.
         * @return Builder
         */
        public Builder extension(String extension) {
            this.extension = extension;
            return this;
        }

        /**
         * Setter for shortUrl.
         * @param  shortUrl  String value for shortUrl.
         * @return Builder
         */
        public Builder shortUrl(String shortUrl) {
            this.shortUrl = shortUrl;
            return this;
        }

        /**
         * Setter for shortPath.
         * @param  shortPath  String value for shortPath.
         * @return Builder
         */
        public Builder shortPath(String shortPath) {
            this.shortPath = shortPath;
            return this;
        }

        /**
         * Setter for retainHours.
         * @param  retainHours  String value for retainHours.
         * @return Builder
         */
        public Builder retainHours(String retainHours) {
            this.retainHours = retainHours;
            return this;
        }

        /**
         * Setter for humanFilesize.
         * @param  humanFilesize  String value for humanFilesize.
         * @return Builder
         */
        public Builder humanFilesize(String humanFilesize) {
            this.humanFilesize = humanFilesize;
            return this;
        }

        /**
         * Setter for dominantColor.
         * @param  dominantColor  String value for dominantColor.
         * @return Builder
         */
        public Builder dominantColor(String dominantColor) {
            this.dominantColor = OptionalNullable.of(dominantColor);
            return this;
        }

        /**
         * UnSetter for dominantColor.
         * @return Builder
         */
        public Builder unsetDominantColor() {
            dominantColor = null;
            return this;
        }

        /**
         * Setter for thumbnail.
         * @param  thumbnail  Thumbnail value for thumbnail.
         * @return Builder
         */
        public Builder thumbnail(Thumbnail thumbnail) {
            this.thumbnail = OptionalNullable.of(thumbnail);
            return this;
        }

        /**
         * UnSetter for thumbnail.
         * @return Builder
         */
        public Builder unsetThumbnail() {
            thumbnail = null;
            return this;
        }

        /**
         * Setter for optimizedVideo.
         * @param  optimizedVideo  OptimizedVideo value for optimizedVideo.
         * @return Builder
         */
        public Builder optimizedVideo(OptimizedVideo optimizedVideo) {
            this.optimizedVideo = OptionalNullable.of(optimizedVideo);
            return this;
        }

        /**
         * UnSetter for optimizedVideo.
         * @return Builder
         */
        public Builder unsetOptimizedVideo() {
            optimizedVideo = null;
            return this;
        }

        /**
         * Builds a new {@link UploadsCompleteMultipartJsonResponse} object using the set fields.
         * @return {@link UploadsCompleteMultipartJsonResponse}
         */
        public UploadsCompleteMultipartJsonResponse build() {
            return new UploadsCompleteMultipartJsonResponse(id, url, originalFilename, filesize,
                    width, height, thumbnailWidth, thumbnailHeight, extension, shortUrl, shortPath,
                    retainHours, humanFilesize, dominantColor, thumbnail, optimizedVideo);
        }
    }
}
