/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for UPreferencesUsernameJsonRequest type.
 */
public class UPreferencesUsernameJsonRequest {
    private String newUsername;

    /**
     * Default constructor.
     */
    public UPreferencesUsernameJsonRequest() {
    }

    /**
     * Initialization constructor.
     * @param  newUsername  String value for newUsername.
     */
    public UPreferencesUsernameJsonRequest(
            String newUsername) {
        this.newUsername = newUsername;
    }

    /**
     * Getter for NewUsername.
     * @return Returns the String
     */
    @JsonGetter("new_username")
    public String getNewUsername() {
        return newUsername;
    }

    /**
     * Setter for NewUsername.
     * @param newUsername Value for String
     */
    @JsonSetter("new_username")
    public void setNewUsername(String newUsername) {
        this.newUsername = newUsername;
    }

    /**
     * Converts this UPreferencesUsernameJsonRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UPreferencesUsernameJsonRequest [" + "newUsername=" + newUsername + "]";
    }

    /**
     * Builds a new {@link UPreferencesUsernameJsonRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UPreferencesUsernameJsonRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(newUsername);
        return builder;
    }

    /**
     * Class to build instances of {@link UPreferencesUsernameJsonRequest}.
     */
    public static class Builder {
        private String newUsername;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  newUsername  String value for newUsername.
         */
        public Builder(String newUsername) {
            this.newUsername = newUsername;
        }

        /**
         * Setter for newUsername.
         * @param  newUsername  String value for newUsername.
         * @return Builder
         */
        public Builder newUsername(String newUsername) {
            this.newUsername = newUsername;
            return this;
        }

        /**
         * Builds a new {@link UPreferencesUsernameJsonRequest} object using the set fields.
         * @return {@link UPreferencesUsernameJsonRequest}
         */
        public UPreferencesUsernameJsonRequest build() {
            return new UPreferencesUsernameJsonRequest(newUsername);
        }
    }
}
