/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;
import java.util.List;

/**
 * This is a model class for UserOption type.
 */
public class UserOption {
    private int userId;
    private boolean mailingListMode;
    private int mailingListModeFrequency;
    private boolean emailDigests;
    private int emailLevel;
    private int emailMessagesLevel;
    private boolean externalLinksInNewTab;
    private Integer bookmarkAutoDeletePreference;
    private String colorSchemeId;
    private String darkSchemeId;
    private boolean dynamicFavicon;
    private boolean enableQuoting;
    private boolean enableSmartLists;
    private boolean enableMarkdownMonospaceFont;
    private boolean enableDefer;
    private int digestAfterMinutes;
    private boolean automaticallyUnpinTopics;
    private int autoTrackTopicsAfterMsecs;
    private int notificationLevelWhenReplying;
    private int newTopicDurationMinutes;
    private int emailPreviousReplies;
    private boolean emailInReplyTo;
    private int likeNotificationFrequency;
    private boolean notifyOnLinkedPosts;
    private String pushNotificationLevel;
    private boolean enableUpcomingChangeAvailableNotifications;
    private boolean includeTl0InDigests;
    private List<Object> themeIds;
    private int themeKeySeq;
    private boolean allowPrivateMessages;
    private boolean enableAllowedPmUsers;
    private String homepageId;
    private boolean hideProfileAndPresence;
    private boolean hideProfile;
    private boolean hidePresence;
    private String textSize;
    private int textSizeSeq;
    private String titleCountMode;
    private String timezone;
    private boolean skipNewUserTips;
    private String defaultCalendar;
    private OptionalNullable<String> oldestSearchLogDate;
    private Boolean sidebarLinkToFilteredList;
    private Boolean sidebarShowCountOfNewItems;
    private Boolean watchedPrecedenceOverMuted;
    private OptionalNullable<String> seenPopups;
    private boolean topicsUnreadWhenClosed;
    private Integer compositionMode;
    private int interfaceColorMode;
    private boolean showOriginalContent;

    /**
     * Default constructor.
     */
    public UserOption() {
    }

    /**
     * Initialization constructor.
     * @param  userId  int value for userId.
     * @param  mailingListMode  boolean value for mailingListMode.
     * @param  mailingListModeFrequency  int value for mailingListModeFrequency.
     * @param  emailDigests  boolean value for emailDigests.
     * @param  emailLevel  int value for emailLevel.
     * @param  emailMessagesLevel  int value for emailMessagesLevel.
     * @param  externalLinksInNewTab  boolean value for externalLinksInNewTab.
     * @param  colorSchemeId  String value for colorSchemeId.
     * @param  darkSchemeId  String value for darkSchemeId.
     * @param  dynamicFavicon  boolean value for dynamicFavicon.
     * @param  enableQuoting  boolean value for enableQuoting.
     * @param  enableSmartLists  boolean value for enableSmartLists.
     * @param  enableMarkdownMonospaceFont  boolean value for enableMarkdownMonospaceFont.
     * @param  enableDefer  boolean value for enableDefer.
     * @param  digestAfterMinutes  int value for digestAfterMinutes.
     * @param  automaticallyUnpinTopics  boolean value for automaticallyUnpinTopics.
     * @param  autoTrackTopicsAfterMsecs  int value for autoTrackTopicsAfterMsecs.
     * @param  notificationLevelWhenReplying  int value for notificationLevelWhenReplying.
     * @param  newTopicDurationMinutes  int value for newTopicDurationMinutes.
     * @param  emailPreviousReplies  int value for emailPreviousReplies.
     * @param  emailInReplyTo  boolean value for emailInReplyTo.
     * @param  likeNotificationFrequency  int value for likeNotificationFrequency.
     * @param  notifyOnLinkedPosts  boolean value for notifyOnLinkedPosts.
     * @param  pushNotificationLevel  String value for pushNotificationLevel.
     * @param  enableUpcomingChangeAvailableNotifications  boolean value for
     *         enableUpcomingChangeAvailableNotifications.
     * @param  includeTl0InDigests  boolean value for includeTl0InDigests.
     * @param  themeIds  List of Object value for themeIds.
     * @param  themeKeySeq  int value for themeKeySeq.
     * @param  allowPrivateMessages  boolean value for allowPrivateMessages.
     * @param  enableAllowedPmUsers  boolean value for enableAllowedPmUsers.
     * @param  homepageId  String value for homepageId.
     * @param  hideProfileAndPresence  boolean value for hideProfileAndPresence.
     * @param  hideProfile  boolean value for hideProfile.
     * @param  hidePresence  boolean value for hidePresence.
     * @param  textSize  String value for textSize.
     * @param  textSizeSeq  int value for textSizeSeq.
     * @param  titleCountMode  String value for titleCountMode.
     * @param  timezone  String value for timezone.
     * @param  skipNewUserTips  boolean value for skipNewUserTips.
     * @param  topicsUnreadWhenClosed  boolean value for topicsUnreadWhenClosed.
     * @param  interfaceColorMode  int value for interfaceColorMode.
     * @param  showOriginalContent  boolean value for showOriginalContent.
     * @param  bookmarkAutoDeletePreference  Integer value for bookmarkAutoDeletePreference.
     * @param  defaultCalendar  String value for defaultCalendar.
     * @param  oldestSearchLogDate  String value for oldestSearchLogDate.
     * @param  sidebarLinkToFilteredList  Boolean value for sidebarLinkToFilteredList.
     * @param  sidebarShowCountOfNewItems  Boolean value for sidebarShowCountOfNewItems.
     * @param  watchedPrecedenceOverMuted  Boolean value for watchedPrecedenceOverMuted.
     * @param  seenPopups  String value for seenPopups.
     * @param  compositionMode  Integer value for compositionMode.
     */
    public UserOption(
            int userId,
            boolean mailingListMode,
            int mailingListModeFrequency,
            boolean emailDigests,
            int emailLevel,
            int emailMessagesLevel,
            boolean externalLinksInNewTab,
            String colorSchemeId,
            String darkSchemeId,
            boolean dynamicFavicon,
            boolean enableQuoting,
            boolean enableSmartLists,
            boolean enableMarkdownMonospaceFont,
            boolean enableDefer,
            int digestAfterMinutes,
            boolean automaticallyUnpinTopics,
            int autoTrackTopicsAfterMsecs,
            int notificationLevelWhenReplying,
            int newTopicDurationMinutes,
            int emailPreviousReplies,
            boolean emailInReplyTo,
            int likeNotificationFrequency,
            boolean notifyOnLinkedPosts,
            String pushNotificationLevel,
            boolean enableUpcomingChangeAvailableNotifications,
            boolean includeTl0InDigests,
            List<Object> themeIds,
            int themeKeySeq,
            boolean allowPrivateMessages,
            boolean enableAllowedPmUsers,
            String homepageId,
            boolean hideProfileAndPresence,
            boolean hideProfile,
            boolean hidePresence,
            String textSize,
            int textSizeSeq,
            String titleCountMode,
            String timezone,
            boolean skipNewUserTips,
            boolean topicsUnreadWhenClosed,
            int interfaceColorMode,
            boolean showOriginalContent,
            Integer bookmarkAutoDeletePreference,
            String defaultCalendar,
            String oldestSearchLogDate,
            Boolean sidebarLinkToFilteredList,
            Boolean sidebarShowCountOfNewItems,
            Boolean watchedPrecedenceOverMuted,
            String seenPopups,
            Integer compositionMode) {
        this.userId = userId;
        this.mailingListMode = mailingListMode;
        this.mailingListModeFrequency = mailingListModeFrequency;
        this.emailDigests = emailDigests;
        this.emailLevel = emailLevel;
        this.emailMessagesLevel = emailMessagesLevel;
        this.externalLinksInNewTab = externalLinksInNewTab;
        this.bookmarkAutoDeletePreference = bookmarkAutoDeletePreference;
        this.colorSchemeId = colorSchemeId;
        this.darkSchemeId = darkSchemeId;
        this.dynamicFavicon = dynamicFavicon;
        this.enableQuoting = enableQuoting;
        this.enableSmartLists = enableSmartLists;
        this.enableMarkdownMonospaceFont = enableMarkdownMonospaceFont;
        this.enableDefer = enableDefer;
        this.digestAfterMinutes = digestAfterMinutes;
        this.automaticallyUnpinTopics = automaticallyUnpinTopics;
        this.autoTrackTopicsAfterMsecs = autoTrackTopicsAfterMsecs;
        this.notificationLevelWhenReplying = notificationLevelWhenReplying;
        this.newTopicDurationMinutes = newTopicDurationMinutes;
        this.emailPreviousReplies = emailPreviousReplies;
        this.emailInReplyTo = emailInReplyTo;
        this.likeNotificationFrequency = likeNotificationFrequency;
        this.notifyOnLinkedPosts = notifyOnLinkedPosts;
        this.pushNotificationLevel = pushNotificationLevel;
        this.enableUpcomingChangeAvailableNotifications =
                enableUpcomingChangeAvailableNotifications;
        this.includeTl0InDigests = includeTl0InDigests;
        this.themeIds = themeIds;
        this.themeKeySeq = themeKeySeq;
        this.allowPrivateMessages = allowPrivateMessages;
        this.enableAllowedPmUsers = enableAllowedPmUsers;
        this.homepageId = homepageId;
        this.hideProfileAndPresence = hideProfileAndPresence;
        this.hideProfile = hideProfile;
        this.hidePresence = hidePresence;
        this.textSize = textSize;
        this.textSizeSeq = textSizeSeq;
        this.titleCountMode = titleCountMode;
        this.timezone = timezone;
        this.skipNewUserTips = skipNewUserTips;
        this.defaultCalendar = defaultCalendar;
        this.oldestSearchLogDate = OptionalNullable.of(oldestSearchLogDate);
        this.sidebarLinkToFilteredList = sidebarLinkToFilteredList;
        this.sidebarShowCountOfNewItems = sidebarShowCountOfNewItems;
        this.watchedPrecedenceOverMuted = watchedPrecedenceOverMuted;
        this.seenPopups = OptionalNullable.of(seenPopups);
        this.topicsUnreadWhenClosed = topicsUnreadWhenClosed;
        this.compositionMode = compositionMode;
        this.interfaceColorMode = interfaceColorMode;
        this.showOriginalContent = showOriginalContent;
    }

    /**
     * Initialization constructor.
     * @param  userId  int value for userId.
     * @param  mailingListMode  boolean value for mailingListMode.
     * @param  mailingListModeFrequency  int value for mailingListModeFrequency.
     * @param  emailDigests  boolean value for emailDigests.
     * @param  emailLevel  int value for emailLevel.
     * @param  emailMessagesLevel  int value for emailMessagesLevel.
     * @param  externalLinksInNewTab  boolean value for externalLinksInNewTab.
     * @param  colorSchemeId  String value for colorSchemeId.
     * @param  darkSchemeId  String value for darkSchemeId.
     * @param  dynamicFavicon  boolean value for dynamicFavicon.
     * @param  enableQuoting  boolean value for enableQuoting.
     * @param  enableSmartLists  boolean value for enableSmartLists.
     * @param  enableMarkdownMonospaceFont  boolean value for enableMarkdownMonospaceFont.
     * @param  enableDefer  boolean value for enableDefer.
     * @param  digestAfterMinutes  int value for digestAfterMinutes.
     * @param  automaticallyUnpinTopics  boolean value for automaticallyUnpinTopics.
     * @param  autoTrackTopicsAfterMsecs  int value for autoTrackTopicsAfterMsecs.
     * @param  notificationLevelWhenReplying  int value for notificationLevelWhenReplying.
     * @param  newTopicDurationMinutes  int value for newTopicDurationMinutes.
     * @param  emailPreviousReplies  int value for emailPreviousReplies.
     * @param  emailInReplyTo  boolean value for emailInReplyTo.
     * @param  likeNotificationFrequency  int value for likeNotificationFrequency.
     * @param  notifyOnLinkedPosts  boolean value for notifyOnLinkedPosts.
     * @param  pushNotificationLevel  String value for pushNotificationLevel.
     * @param  enableUpcomingChangeAvailableNotifications  boolean value for
     *         enableUpcomingChangeAvailableNotifications.
     * @param  includeTl0InDigests  boolean value for includeTl0InDigests.
     * @param  themeIds  List of Object value for themeIds.
     * @param  themeKeySeq  int value for themeKeySeq.
     * @param  allowPrivateMessages  boolean value for allowPrivateMessages.
     * @param  enableAllowedPmUsers  boolean value for enableAllowedPmUsers.
     * @param  homepageId  String value for homepageId.
     * @param  hideProfileAndPresence  boolean value for hideProfileAndPresence.
     * @param  hideProfile  boolean value for hideProfile.
     * @param  hidePresence  boolean value for hidePresence.
     * @param  textSize  String value for textSize.
     * @param  textSizeSeq  int value for textSizeSeq.
     * @param  titleCountMode  String value for titleCountMode.
     * @param  timezone  String value for timezone.
     * @param  skipNewUserTips  boolean value for skipNewUserTips.
     * @param  topicsUnreadWhenClosed  boolean value for topicsUnreadWhenClosed.
     * @param  interfaceColorMode  int value for interfaceColorMode.
     * @param  showOriginalContent  boolean value for showOriginalContent.
     * @param  bookmarkAutoDeletePreference  Integer value for bookmarkAutoDeletePreference.
     * @param  defaultCalendar  String value for defaultCalendar.
     * @param  oldestSearchLogDate  String value for oldestSearchLogDate.
     * @param  sidebarLinkToFilteredList  Boolean value for sidebarLinkToFilteredList.
     * @param  sidebarShowCountOfNewItems  Boolean value for sidebarShowCountOfNewItems.
     * @param  watchedPrecedenceOverMuted  Boolean value for watchedPrecedenceOverMuted.
     * @param  seenPopups  String value for seenPopups.
     * @param  compositionMode  Integer value for compositionMode.
     */

    protected UserOption(int userId, boolean mailingListMode, int mailingListModeFrequency,
            boolean emailDigests, int emailLevel, int emailMessagesLevel,
            boolean externalLinksInNewTab, String colorSchemeId, String darkSchemeId,
            boolean dynamicFavicon, boolean enableQuoting, boolean enableSmartLists,
            boolean enableMarkdownMonospaceFont, boolean enableDefer, int digestAfterMinutes,
            boolean automaticallyUnpinTopics, int autoTrackTopicsAfterMsecs,
            int notificationLevelWhenReplying, int newTopicDurationMinutes,
            int emailPreviousReplies, boolean emailInReplyTo, int likeNotificationFrequency,
            boolean notifyOnLinkedPosts, String pushNotificationLevel,
            boolean enableUpcomingChangeAvailableNotifications, boolean includeTl0InDigests,
            List<Object> themeIds, int themeKeySeq, boolean allowPrivateMessages,
            boolean enableAllowedPmUsers, String homepageId, boolean hideProfileAndPresence,
            boolean hideProfile, boolean hidePresence, String textSize, int textSizeSeq,
            String titleCountMode, String timezone, boolean skipNewUserTips,
            boolean topicsUnreadWhenClosed, int interfaceColorMode, boolean showOriginalContent,
            Integer bookmarkAutoDeletePreference, String defaultCalendar,
            OptionalNullable<String> oldestSearchLogDate, Boolean sidebarLinkToFilteredList,
            Boolean sidebarShowCountOfNewItems, Boolean watchedPrecedenceOverMuted,
            OptionalNullable<String> seenPopups, Integer compositionMode) {
        this.userId = userId;
        this.mailingListMode = mailingListMode;
        this.mailingListModeFrequency = mailingListModeFrequency;
        this.emailDigests = emailDigests;
        this.emailLevel = emailLevel;
        this.emailMessagesLevel = emailMessagesLevel;
        this.externalLinksInNewTab = externalLinksInNewTab;
        this.bookmarkAutoDeletePreference = bookmarkAutoDeletePreference;
        this.colorSchemeId = colorSchemeId;
        this.darkSchemeId = darkSchemeId;
        this.dynamicFavicon = dynamicFavicon;
        this.enableQuoting = enableQuoting;
        this.enableSmartLists = enableSmartLists;
        this.enableMarkdownMonospaceFont = enableMarkdownMonospaceFont;
        this.enableDefer = enableDefer;
        this.digestAfterMinutes = digestAfterMinutes;
        this.automaticallyUnpinTopics = automaticallyUnpinTopics;
        this.autoTrackTopicsAfterMsecs = autoTrackTopicsAfterMsecs;
        this.notificationLevelWhenReplying = notificationLevelWhenReplying;
        this.newTopicDurationMinutes = newTopicDurationMinutes;
        this.emailPreviousReplies = emailPreviousReplies;
        this.emailInReplyTo = emailInReplyTo;
        this.likeNotificationFrequency = likeNotificationFrequency;
        this.notifyOnLinkedPosts = notifyOnLinkedPosts;
        this.pushNotificationLevel = pushNotificationLevel;
        this.enableUpcomingChangeAvailableNotifications =
                enableUpcomingChangeAvailableNotifications;
        this.includeTl0InDigests = includeTl0InDigests;
        this.themeIds = themeIds;
        this.themeKeySeq = themeKeySeq;
        this.allowPrivateMessages = allowPrivateMessages;
        this.enableAllowedPmUsers = enableAllowedPmUsers;
        this.homepageId = homepageId;
        this.hideProfileAndPresence = hideProfileAndPresence;
        this.hideProfile = hideProfile;
        this.hidePresence = hidePresence;
        this.textSize = textSize;
        this.textSizeSeq = textSizeSeq;
        this.titleCountMode = titleCountMode;
        this.timezone = timezone;
        this.skipNewUserTips = skipNewUserTips;
        this.defaultCalendar = defaultCalendar;
        this.oldestSearchLogDate = oldestSearchLogDate;
        this.sidebarLinkToFilteredList = sidebarLinkToFilteredList;
        this.sidebarShowCountOfNewItems = sidebarShowCountOfNewItems;
        this.watchedPrecedenceOverMuted = watchedPrecedenceOverMuted;
        this.seenPopups = seenPopups;
        this.topicsUnreadWhenClosed = topicsUnreadWhenClosed;
        this.compositionMode = compositionMode;
        this.interfaceColorMode = interfaceColorMode;
        this.showOriginalContent = showOriginalContent;
    }

    /**
     * Getter for UserId.
     * @return Returns the int
     */
    @JsonGetter("user_id")
    public int getUserId() {
        return userId;
    }

    /**
     * Setter for UserId.
     * @param userId Value for int
     */
    @JsonSetter("user_id")
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * Getter for MailingListMode.
     * @return Returns the boolean
     */
    @JsonGetter("mailing_list_mode")
    public boolean getMailingListMode() {
        return mailingListMode;
    }

    /**
     * Setter for MailingListMode.
     * @param mailingListMode Value for boolean
     */
    @JsonSetter("mailing_list_mode")
    public void setMailingListMode(boolean mailingListMode) {
        this.mailingListMode = mailingListMode;
    }

    /**
     * Getter for MailingListModeFrequency.
     * @return Returns the int
     */
    @JsonGetter("mailing_list_mode_frequency")
    public int getMailingListModeFrequency() {
        return mailingListModeFrequency;
    }

    /**
     * Setter for MailingListModeFrequency.
     * @param mailingListModeFrequency Value for int
     */
    @JsonSetter("mailing_list_mode_frequency")
    public void setMailingListModeFrequency(int mailingListModeFrequency) {
        this.mailingListModeFrequency = mailingListModeFrequency;
    }

    /**
     * Getter for EmailDigests.
     * @return Returns the boolean
     */
    @JsonGetter("email_digests")
    public boolean getEmailDigests() {
        return emailDigests;
    }

    /**
     * Setter for EmailDigests.
     * @param emailDigests Value for boolean
     */
    @JsonSetter("email_digests")
    public void setEmailDigests(boolean emailDigests) {
        this.emailDigests = emailDigests;
    }

    /**
     * Getter for EmailLevel.
     * @return Returns the int
     */
    @JsonGetter("email_level")
    public int getEmailLevel() {
        return emailLevel;
    }

    /**
     * Setter for EmailLevel.
     * @param emailLevel Value for int
     */
    @JsonSetter("email_level")
    public void setEmailLevel(int emailLevel) {
        this.emailLevel = emailLevel;
    }

    /**
     * Getter for EmailMessagesLevel.
     * @return Returns the int
     */
    @JsonGetter("email_messages_level")
    public int getEmailMessagesLevel() {
        return emailMessagesLevel;
    }

    /**
     * Setter for EmailMessagesLevel.
     * @param emailMessagesLevel Value for int
     */
    @JsonSetter("email_messages_level")
    public void setEmailMessagesLevel(int emailMessagesLevel) {
        this.emailMessagesLevel = emailMessagesLevel;
    }

    /**
     * Getter for ExternalLinksInNewTab.
     * @return Returns the boolean
     */
    @JsonGetter("external_links_in_new_tab")
    public boolean getExternalLinksInNewTab() {
        return externalLinksInNewTab;
    }

    /**
     * Setter for ExternalLinksInNewTab.
     * @param externalLinksInNewTab Value for boolean
     */
    @JsonSetter("external_links_in_new_tab")
    public void setExternalLinksInNewTab(boolean externalLinksInNewTab) {
        this.externalLinksInNewTab = externalLinksInNewTab;
    }

    /**
     * Getter for BookmarkAutoDeletePreference.
     * @return Returns the Integer
     */
    @JsonGetter("bookmark_auto_delete_preference")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getBookmarkAutoDeletePreference() {
        return bookmarkAutoDeletePreference;
    }

    /**
     * Setter for BookmarkAutoDeletePreference.
     * @param bookmarkAutoDeletePreference Value for Integer
     */
    @JsonSetter("bookmark_auto_delete_preference")
    public void setBookmarkAutoDeletePreference(Integer bookmarkAutoDeletePreference) {
        this.bookmarkAutoDeletePreference = bookmarkAutoDeletePreference;
    }

    /**
     * Getter for ColorSchemeId.
     * @return Returns the String
     */
    @JsonGetter("color_scheme_id")
    public String getColorSchemeId() {
        return colorSchemeId;
    }

    /**
     * Setter for ColorSchemeId.
     * @param colorSchemeId Value for String
     */
    @JsonSetter("color_scheme_id")
    public void setColorSchemeId(String colorSchemeId) {
        this.colorSchemeId = colorSchemeId;
    }

    /**
     * Getter for DarkSchemeId.
     * @return Returns the String
     */
    @JsonGetter("dark_scheme_id")
    public String getDarkSchemeId() {
        return darkSchemeId;
    }

    /**
     * Setter for DarkSchemeId.
     * @param darkSchemeId Value for String
     */
    @JsonSetter("dark_scheme_id")
    public void setDarkSchemeId(String darkSchemeId) {
        this.darkSchemeId = darkSchemeId;
    }

    /**
     * Getter for DynamicFavicon.
     * @return Returns the boolean
     */
    @JsonGetter("dynamic_favicon")
    public boolean getDynamicFavicon() {
        return dynamicFavicon;
    }

    /**
     * Setter for DynamicFavicon.
     * @param dynamicFavicon Value for boolean
     */
    @JsonSetter("dynamic_favicon")
    public void setDynamicFavicon(boolean dynamicFavicon) {
        this.dynamicFavicon = dynamicFavicon;
    }

    /**
     * Getter for EnableQuoting.
     * @return Returns the boolean
     */
    @JsonGetter("enable_quoting")
    public boolean getEnableQuoting() {
        return enableQuoting;
    }

    /**
     * Setter for EnableQuoting.
     * @param enableQuoting Value for boolean
     */
    @JsonSetter("enable_quoting")
    public void setEnableQuoting(boolean enableQuoting) {
        this.enableQuoting = enableQuoting;
    }

    /**
     * Getter for EnableSmartLists.
     * @return Returns the boolean
     */
    @JsonGetter("enable_smart_lists")
    public boolean getEnableSmartLists() {
        return enableSmartLists;
    }

    /**
     * Setter for EnableSmartLists.
     * @param enableSmartLists Value for boolean
     */
    @JsonSetter("enable_smart_lists")
    public void setEnableSmartLists(boolean enableSmartLists) {
        this.enableSmartLists = enableSmartLists;
    }

    /**
     * Getter for EnableMarkdownMonospaceFont.
     * @return Returns the boolean
     */
    @JsonGetter("enable_markdown_monospace_font")
    public boolean getEnableMarkdownMonospaceFont() {
        return enableMarkdownMonospaceFont;
    }

    /**
     * Setter for EnableMarkdownMonospaceFont.
     * @param enableMarkdownMonospaceFont Value for boolean
     */
    @JsonSetter("enable_markdown_monospace_font")
    public void setEnableMarkdownMonospaceFont(boolean enableMarkdownMonospaceFont) {
        this.enableMarkdownMonospaceFont = enableMarkdownMonospaceFont;
    }

    /**
     * Getter for EnableDefer.
     * @return Returns the boolean
     */
    @JsonGetter("enable_defer")
    public boolean getEnableDefer() {
        return enableDefer;
    }

    /**
     * Setter for EnableDefer.
     * @param enableDefer Value for boolean
     */
    @JsonSetter("enable_defer")
    public void setEnableDefer(boolean enableDefer) {
        this.enableDefer = enableDefer;
    }

    /**
     * Getter for DigestAfterMinutes.
     * @return Returns the int
     */
    @JsonGetter("digest_after_minutes")
    public int getDigestAfterMinutes() {
        return digestAfterMinutes;
    }

    /**
     * Setter for DigestAfterMinutes.
     * @param digestAfterMinutes Value for int
     */
    @JsonSetter("digest_after_minutes")
    public void setDigestAfterMinutes(int digestAfterMinutes) {
        this.digestAfterMinutes = digestAfterMinutes;
    }

    /**
     * Getter for AutomaticallyUnpinTopics.
     * @return Returns the boolean
     */
    @JsonGetter("automatically_unpin_topics")
    public boolean getAutomaticallyUnpinTopics() {
        return automaticallyUnpinTopics;
    }

    /**
     * Setter for AutomaticallyUnpinTopics.
     * @param automaticallyUnpinTopics Value for boolean
     */
    @JsonSetter("automatically_unpin_topics")
    public void setAutomaticallyUnpinTopics(boolean automaticallyUnpinTopics) {
        this.automaticallyUnpinTopics = automaticallyUnpinTopics;
    }

    /**
     * Getter for AutoTrackTopicsAfterMsecs.
     * @return Returns the int
     */
    @JsonGetter("auto_track_topics_after_msecs")
    public int getAutoTrackTopicsAfterMsecs() {
        return autoTrackTopicsAfterMsecs;
    }

    /**
     * Setter for AutoTrackTopicsAfterMsecs.
     * @param autoTrackTopicsAfterMsecs Value for int
     */
    @JsonSetter("auto_track_topics_after_msecs")
    public void setAutoTrackTopicsAfterMsecs(int autoTrackTopicsAfterMsecs) {
        this.autoTrackTopicsAfterMsecs = autoTrackTopicsAfterMsecs;
    }

    /**
     * Getter for NotificationLevelWhenReplying.
     * @return Returns the int
     */
    @JsonGetter("notification_level_when_replying")
    public int getNotificationLevelWhenReplying() {
        return notificationLevelWhenReplying;
    }

    /**
     * Setter for NotificationLevelWhenReplying.
     * @param notificationLevelWhenReplying Value for int
     */
    @JsonSetter("notification_level_when_replying")
    public void setNotificationLevelWhenReplying(int notificationLevelWhenReplying) {
        this.notificationLevelWhenReplying = notificationLevelWhenReplying;
    }

    /**
     * Getter for NewTopicDurationMinutes.
     * @return Returns the int
     */
    @JsonGetter("new_topic_duration_minutes")
    public int getNewTopicDurationMinutes() {
        return newTopicDurationMinutes;
    }

    /**
     * Setter for NewTopicDurationMinutes.
     * @param newTopicDurationMinutes Value for int
     */
    @JsonSetter("new_topic_duration_minutes")
    public void setNewTopicDurationMinutes(int newTopicDurationMinutes) {
        this.newTopicDurationMinutes = newTopicDurationMinutes;
    }

    /**
     * Getter for EmailPreviousReplies.
     * @return Returns the int
     */
    @JsonGetter("email_previous_replies")
    public int getEmailPreviousReplies() {
        return emailPreviousReplies;
    }

    /**
     * Setter for EmailPreviousReplies.
     * @param emailPreviousReplies Value for int
     */
    @JsonSetter("email_previous_replies")
    public void setEmailPreviousReplies(int emailPreviousReplies) {
        this.emailPreviousReplies = emailPreviousReplies;
    }

    /**
     * Getter for EmailInReplyTo.
     * @return Returns the boolean
     */
    @JsonGetter("email_in_reply_to")
    public boolean getEmailInReplyTo() {
        return emailInReplyTo;
    }

    /**
     * Setter for EmailInReplyTo.
     * @param emailInReplyTo Value for boolean
     */
    @JsonSetter("email_in_reply_to")
    public void setEmailInReplyTo(boolean emailInReplyTo) {
        this.emailInReplyTo = emailInReplyTo;
    }

    /**
     * Getter for LikeNotificationFrequency.
     * @return Returns the int
     */
    @JsonGetter("like_notification_frequency")
    public int getLikeNotificationFrequency() {
        return likeNotificationFrequency;
    }

    /**
     * Setter for LikeNotificationFrequency.
     * @param likeNotificationFrequency Value for int
     */
    @JsonSetter("like_notification_frequency")
    public void setLikeNotificationFrequency(int likeNotificationFrequency) {
        this.likeNotificationFrequency = likeNotificationFrequency;
    }

    /**
     * Getter for NotifyOnLinkedPosts.
     * @return Returns the boolean
     */
    @JsonGetter("notify_on_linked_posts")
    public boolean getNotifyOnLinkedPosts() {
        return notifyOnLinkedPosts;
    }

    /**
     * Setter for NotifyOnLinkedPosts.
     * @param notifyOnLinkedPosts Value for boolean
     */
    @JsonSetter("notify_on_linked_posts")
    public void setNotifyOnLinkedPosts(boolean notifyOnLinkedPosts) {
        this.notifyOnLinkedPosts = notifyOnLinkedPosts;
    }

    /**
     * Getter for PushNotificationLevel.
     * @return Returns the String
     */
    @JsonGetter("push_notification_level")
    public String getPushNotificationLevel() {
        return pushNotificationLevel;
    }

    /**
     * Setter for PushNotificationLevel.
     * @param pushNotificationLevel Value for String
     */
    @JsonSetter("push_notification_level")
    public void setPushNotificationLevel(String pushNotificationLevel) {
        this.pushNotificationLevel = pushNotificationLevel;
    }

    /**
     * Getter for EnableUpcomingChangeAvailableNotifications.
     * @return Returns the boolean
     */
    @JsonGetter("enable_upcoming_change_available_notifications")
    public boolean getEnableUpcomingChangeAvailableNotifications() {
        return enableUpcomingChangeAvailableNotifications;
    }

    /**
     * Setter for EnableUpcomingChangeAvailableNotifications.
     * @param enableUpcomingChangeAvailableNotifications Value for boolean
     */
    @JsonSetter("enable_upcoming_change_available_notifications")
    public void setEnableUpcomingChangeAvailableNotifications(boolean enableUpcomingChangeAvailableNotifications) {
        this.enableUpcomingChangeAvailableNotifications = enableUpcomingChangeAvailableNotifications;
    }

    /**
     * Getter for IncludeTl0InDigests.
     * @return Returns the boolean
     */
    @JsonGetter("include_tl0_in_digests")
    public boolean getIncludeTl0InDigests() {
        return includeTl0InDigests;
    }

    /**
     * Setter for IncludeTl0InDigests.
     * @param includeTl0InDigests Value for boolean
     */
    @JsonSetter("include_tl0_in_digests")
    public void setIncludeTl0InDigests(boolean includeTl0InDigests) {
        this.includeTl0InDigests = includeTl0InDigests;
    }

    /**
     * Getter for ThemeIds.
     * @return Returns the List of Object
     */
    @JsonGetter("theme_ids")
    public List<Object> getThemeIds() {
        return themeIds;
    }

    /**
     * Setter for ThemeIds.
     * @param themeIds Value for List of Object
     */
    @JsonSetter("theme_ids")
    public void setThemeIds(List<Object> themeIds) {
        this.themeIds = themeIds;
    }

    /**
     * Getter for ThemeKeySeq.
     * @return Returns the int
     */
    @JsonGetter("theme_key_seq")
    public int getThemeKeySeq() {
        return themeKeySeq;
    }

    /**
     * Setter for ThemeKeySeq.
     * @param themeKeySeq Value for int
     */
    @JsonSetter("theme_key_seq")
    public void setThemeKeySeq(int themeKeySeq) {
        this.themeKeySeq = themeKeySeq;
    }

    /**
     * Getter for AllowPrivateMessages.
     * @return Returns the boolean
     */
    @JsonGetter("allow_private_messages")
    public boolean getAllowPrivateMessages() {
        return allowPrivateMessages;
    }

    /**
     * Setter for AllowPrivateMessages.
     * @param allowPrivateMessages Value for boolean
     */
    @JsonSetter("allow_private_messages")
    public void setAllowPrivateMessages(boolean allowPrivateMessages) {
        this.allowPrivateMessages = allowPrivateMessages;
    }

    /**
     * Getter for EnableAllowedPmUsers.
     * @return Returns the boolean
     */
    @JsonGetter("enable_allowed_pm_users")
    public boolean getEnableAllowedPmUsers() {
        return enableAllowedPmUsers;
    }

    /**
     * Setter for EnableAllowedPmUsers.
     * @param enableAllowedPmUsers Value for boolean
     */
    @JsonSetter("enable_allowed_pm_users")
    public void setEnableAllowedPmUsers(boolean enableAllowedPmUsers) {
        this.enableAllowedPmUsers = enableAllowedPmUsers;
    }

    /**
     * Getter for HomepageId.
     * @return Returns the String
     */
    @JsonGetter("homepage_id")
    public String getHomepageId() {
        return homepageId;
    }

    /**
     * Setter for HomepageId.
     * @param homepageId Value for String
     */
    @JsonSetter("homepage_id")
    public void setHomepageId(String homepageId) {
        this.homepageId = homepageId;
    }

    /**
     * Getter for HideProfileAndPresence.
     * @return Returns the boolean
     */
    @JsonGetter("hide_profile_and_presence")
    public boolean getHideProfileAndPresence() {
        return hideProfileAndPresence;
    }

    /**
     * Setter for HideProfileAndPresence.
     * @param hideProfileAndPresence Value for boolean
     */
    @JsonSetter("hide_profile_and_presence")
    public void setHideProfileAndPresence(boolean hideProfileAndPresence) {
        this.hideProfileAndPresence = hideProfileAndPresence;
    }

    /**
     * Getter for HideProfile.
     * @return Returns the boolean
     */
    @JsonGetter("hide_profile")
    public boolean getHideProfile() {
        return hideProfile;
    }

    /**
     * Setter for HideProfile.
     * @param hideProfile Value for boolean
     */
    @JsonSetter("hide_profile")
    public void setHideProfile(boolean hideProfile) {
        this.hideProfile = hideProfile;
    }

    /**
     * Getter for HidePresence.
     * @return Returns the boolean
     */
    @JsonGetter("hide_presence")
    public boolean getHidePresence() {
        return hidePresence;
    }

    /**
     * Setter for HidePresence.
     * @param hidePresence Value for boolean
     */
    @JsonSetter("hide_presence")
    public void setHidePresence(boolean hidePresence) {
        this.hidePresence = hidePresence;
    }

    /**
     * Getter for TextSize.
     * @return Returns the String
     */
    @JsonGetter("text_size")
    public String getTextSize() {
        return textSize;
    }

    /**
     * Setter for TextSize.
     * @param textSize Value for String
     */
    @JsonSetter("text_size")
    public void setTextSize(String textSize) {
        this.textSize = textSize;
    }

    /**
     * Getter for TextSizeSeq.
     * @return Returns the int
     */
    @JsonGetter("text_size_seq")
    public int getTextSizeSeq() {
        return textSizeSeq;
    }

    /**
     * Setter for TextSizeSeq.
     * @param textSizeSeq Value for int
     */
    @JsonSetter("text_size_seq")
    public void setTextSizeSeq(int textSizeSeq) {
        this.textSizeSeq = textSizeSeq;
    }

    /**
     * Getter for TitleCountMode.
     * @return Returns the String
     */
    @JsonGetter("title_count_mode")
    public String getTitleCountMode() {
        return titleCountMode;
    }

    /**
     * Setter for TitleCountMode.
     * @param titleCountMode Value for String
     */
    @JsonSetter("title_count_mode")
    public void setTitleCountMode(String titleCountMode) {
        this.titleCountMode = titleCountMode;
    }

    /**
     * Getter for Timezone.
     * @return Returns the String
     */
    @JsonGetter("timezone")
    public String getTimezone() {
        return timezone;
    }

    /**
     * Setter for Timezone.
     * @param timezone Value for String
     */
    @JsonSetter("timezone")
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    /**
     * Getter for SkipNewUserTips.
     * @return Returns the boolean
     */
    @JsonGetter("skip_new_user_tips")
    public boolean getSkipNewUserTips() {
        return skipNewUserTips;
    }

    /**
     * Setter for SkipNewUserTips.
     * @param skipNewUserTips Value for boolean
     */
    @JsonSetter("skip_new_user_tips")
    public void setSkipNewUserTips(boolean skipNewUserTips) {
        this.skipNewUserTips = skipNewUserTips;
    }

    /**
     * Getter for DefaultCalendar.
     * @return Returns the String
     */
    @JsonGetter("default_calendar")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDefaultCalendar() {
        return defaultCalendar;
    }

    /**
     * Setter for DefaultCalendar.
     * @param defaultCalendar Value for String
     */
    @JsonSetter("default_calendar")
    public void setDefaultCalendar(String defaultCalendar) {
        this.defaultCalendar = defaultCalendar;
    }

    /**
     * Internal Getter for OldestSearchLogDate.
     * @return Returns the Internal String
     */
    @JsonGetter("oldest_search_log_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetOldestSearchLogDate() {
        return this.oldestSearchLogDate;
    }

    /**
     * Getter for OldestSearchLogDate.
     * @return Returns the String
     */
    public String getOldestSearchLogDate() {
        return OptionalNullable.getFrom(oldestSearchLogDate);
    }

    /**
     * Setter for OldestSearchLogDate.
     * @param oldestSearchLogDate Value for String
     */
    @JsonSetter("oldest_search_log_date")
    public void setOldestSearchLogDate(String oldestSearchLogDate) {
        this.oldestSearchLogDate = OptionalNullable.of(oldestSearchLogDate);
    }

    /**
     * UnSetter for OldestSearchLogDate.
     */
    public void unsetOldestSearchLogDate() {
        oldestSearchLogDate = null;
    }

    /**
     * Getter for SidebarLinkToFilteredList.
     * @return Returns the Boolean
     */
    @JsonGetter("sidebar_link_to_filtered_list")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getSidebarLinkToFilteredList() {
        return sidebarLinkToFilteredList;
    }

    /**
     * Setter for SidebarLinkToFilteredList.
     * @param sidebarLinkToFilteredList Value for Boolean
     */
    @JsonSetter("sidebar_link_to_filtered_list")
    public void setSidebarLinkToFilteredList(Boolean sidebarLinkToFilteredList) {
        this.sidebarLinkToFilteredList = sidebarLinkToFilteredList;
    }

    /**
     * Getter for SidebarShowCountOfNewItems.
     * @return Returns the Boolean
     */
    @JsonGetter("sidebar_show_count_of_new_items")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getSidebarShowCountOfNewItems() {
        return sidebarShowCountOfNewItems;
    }

    /**
     * Setter for SidebarShowCountOfNewItems.
     * @param sidebarShowCountOfNewItems Value for Boolean
     */
    @JsonSetter("sidebar_show_count_of_new_items")
    public void setSidebarShowCountOfNewItems(Boolean sidebarShowCountOfNewItems) {
        this.sidebarShowCountOfNewItems = sidebarShowCountOfNewItems;
    }

    /**
     * Getter for WatchedPrecedenceOverMuted.
     * @return Returns the Boolean
     */
    @JsonGetter("watched_precedence_over_muted")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getWatchedPrecedenceOverMuted() {
        return watchedPrecedenceOverMuted;
    }

    /**
     * Setter for WatchedPrecedenceOverMuted.
     * @param watchedPrecedenceOverMuted Value for Boolean
     */
    @JsonSetter("watched_precedence_over_muted")
    public void setWatchedPrecedenceOverMuted(Boolean watchedPrecedenceOverMuted) {
        this.watchedPrecedenceOverMuted = watchedPrecedenceOverMuted;
    }

    /**
     * Internal Getter for SeenPopups.
     * @return Returns the Internal String
     */
    @JsonGetter("seen_popups")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetSeenPopups() {
        return this.seenPopups;
    }

    /**
     * Getter for SeenPopups.
     * @return Returns the String
     */
    public String getSeenPopups() {
        return OptionalNullable.getFrom(seenPopups);
    }

    /**
     * Setter for SeenPopups.
     * @param seenPopups Value for String
     */
    @JsonSetter("seen_popups")
    public void setSeenPopups(String seenPopups) {
        this.seenPopups = OptionalNullable.of(seenPopups);
    }

    /**
     * UnSetter for SeenPopups.
     */
    public void unsetSeenPopups() {
        seenPopups = null;
    }

    /**
     * Getter for TopicsUnreadWhenClosed.
     * @return Returns the boolean
     */
    @JsonGetter("topics_unread_when_closed")
    public boolean getTopicsUnreadWhenClosed() {
        return topicsUnreadWhenClosed;
    }

    /**
     * Setter for TopicsUnreadWhenClosed.
     * @param topicsUnreadWhenClosed Value for boolean
     */
    @JsonSetter("topics_unread_when_closed")
    public void setTopicsUnreadWhenClosed(boolean topicsUnreadWhenClosed) {
        this.topicsUnreadWhenClosed = topicsUnreadWhenClosed;
    }

    /**
     * Getter for CompositionMode.
     * @return Returns the Integer
     */
    @JsonGetter("composition_mode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCompositionMode() {
        return compositionMode;
    }

    /**
     * Setter for CompositionMode.
     * @param compositionMode Value for Integer
     */
    @JsonSetter("composition_mode")
    public void setCompositionMode(Integer compositionMode) {
        this.compositionMode = compositionMode;
    }

    /**
     * Getter for InterfaceColorMode.
     * @return Returns the int
     */
    @JsonGetter("interface_color_mode")
    public int getInterfaceColorMode() {
        return interfaceColorMode;
    }

    /**
     * Setter for InterfaceColorMode.
     * @param interfaceColorMode Value for int
     */
    @JsonSetter("interface_color_mode")
    public void setInterfaceColorMode(int interfaceColorMode) {
        this.interfaceColorMode = interfaceColorMode;
    }

    /**
     * Getter for ShowOriginalContent.
     * @return Returns the boolean
     */
    @JsonGetter("show_original_content")
    public boolean getShowOriginalContent() {
        return showOriginalContent;
    }

    /**
     * Setter for ShowOriginalContent.
     * @param showOriginalContent Value for boolean
     */
    @JsonSetter("show_original_content")
    public void setShowOriginalContent(boolean showOriginalContent) {
        this.showOriginalContent = showOriginalContent;
    }

    /**
     * Converts this UserOption into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UserOption [" + "userId=" + userId + ", mailingListMode=" + mailingListMode
                + ", mailingListModeFrequency=" + mailingListModeFrequency + ", emailDigests="
                + emailDigests + ", emailLevel=" + emailLevel + ", emailMessagesLevel="
                + emailMessagesLevel + ", externalLinksInNewTab=" + externalLinksInNewTab
                + ", colorSchemeId=" + colorSchemeId + ", darkSchemeId=" + darkSchemeId
                + ", dynamicFavicon=" + dynamicFavicon + ", enableQuoting=" + enableQuoting
                + ", enableSmartLists=" + enableSmartLists + ", enableMarkdownMonospaceFont="
                + enableMarkdownMonospaceFont + ", enableDefer=" + enableDefer
                + ", digestAfterMinutes=" + digestAfterMinutes + ", automaticallyUnpinTopics="
                + automaticallyUnpinTopics + ", autoTrackTopicsAfterMsecs="
                + autoTrackTopicsAfterMsecs + ", notificationLevelWhenReplying="
                + notificationLevelWhenReplying + ", newTopicDurationMinutes="
                + newTopicDurationMinutes + ", emailPreviousReplies=" + emailPreviousReplies
                + ", emailInReplyTo=" + emailInReplyTo + ", likeNotificationFrequency="
                + likeNotificationFrequency + ", notifyOnLinkedPosts=" + notifyOnLinkedPosts
                + ", pushNotificationLevel=" + pushNotificationLevel
                + ", enableUpcomingChangeAvailableNotifications="
                + enableUpcomingChangeAvailableNotifications + ", includeTl0InDigests="
                + includeTl0InDigests + ", themeIds=" + themeIds + ", themeKeySeq=" + themeKeySeq
                + ", allowPrivateMessages=" + allowPrivateMessages + ", enableAllowedPmUsers="
                + enableAllowedPmUsers + ", homepageId=" + homepageId + ", hideProfileAndPresence="
                + hideProfileAndPresence + ", hideProfile=" + hideProfile + ", hidePresence="
                + hidePresence + ", textSize=" + textSize + ", textSizeSeq=" + textSizeSeq
                + ", titleCountMode=" + titleCountMode + ", timezone=" + timezone
                + ", skipNewUserTips=" + skipNewUserTips + ", topicsUnreadWhenClosed="
                + topicsUnreadWhenClosed + ", interfaceColorMode=" + interfaceColorMode
                + ", showOriginalContent=" + showOriginalContent + ", bookmarkAutoDeletePreference="
                + bookmarkAutoDeletePreference + ", defaultCalendar=" + defaultCalendar
                + ", oldestSearchLogDate=" + oldestSearchLogDate + ", sidebarLinkToFilteredList="
                + sidebarLinkToFilteredList + ", sidebarShowCountOfNewItems="
                + sidebarShowCountOfNewItems + ", watchedPrecedenceOverMuted="
                + watchedPrecedenceOverMuted + ", seenPopups=" + seenPopups + ", compositionMode="
                + compositionMode + "]";
    }

    /**
     * Builds a new {@link UserOption.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UserOption.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(userId, mailingListMode, mailingListModeFrequency,
                emailDigests, emailLevel, emailMessagesLevel, externalLinksInNewTab, colorSchemeId,
                darkSchemeId, dynamicFavicon, enableQuoting, enableSmartLists,
                enableMarkdownMonospaceFont, enableDefer, digestAfterMinutes,
                automaticallyUnpinTopics, autoTrackTopicsAfterMsecs, notificationLevelWhenReplying,
                newTopicDurationMinutes, emailPreviousReplies, emailInReplyTo,
                likeNotificationFrequency, notifyOnLinkedPosts, pushNotificationLevel,
                enableUpcomingChangeAvailableNotifications, includeTl0InDigests, themeIds,
                themeKeySeq, allowPrivateMessages, enableAllowedPmUsers, homepageId,
                hideProfileAndPresence, hideProfile, hidePresence, textSize, textSizeSeq,
                titleCountMode, timezone, skipNewUserTips, topicsUnreadWhenClosed,
                interfaceColorMode, showOriginalContent)
                .bookmarkAutoDeletePreference(getBookmarkAutoDeletePreference())
                .defaultCalendar(getDefaultCalendar())
                .sidebarLinkToFilteredList(getSidebarLinkToFilteredList())
                .sidebarShowCountOfNewItems(getSidebarShowCountOfNewItems())
                .watchedPrecedenceOverMuted(getWatchedPrecedenceOverMuted())
                .compositionMode(getCompositionMode());
        builder.oldestSearchLogDate = internalGetOldestSearchLogDate();
        builder.seenPopups = internalGetSeenPopups();
        return builder;
    }

    /**
     * Class to build instances of {@link UserOption}.
     */
    public static class Builder {
        private int userId;
        private boolean mailingListMode;
        private int mailingListModeFrequency;
        private boolean emailDigests;
        private int emailLevel;
        private int emailMessagesLevel;
        private boolean externalLinksInNewTab;
        private String colorSchemeId;
        private String darkSchemeId;
        private boolean dynamicFavicon;
        private boolean enableQuoting;
        private boolean enableSmartLists;
        private boolean enableMarkdownMonospaceFont;
        private boolean enableDefer;
        private int digestAfterMinutes;
        private boolean automaticallyUnpinTopics;
        private int autoTrackTopicsAfterMsecs;
        private int notificationLevelWhenReplying;
        private int newTopicDurationMinutes;
        private int emailPreviousReplies;
        private boolean emailInReplyTo;
        private int likeNotificationFrequency;
        private boolean notifyOnLinkedPosts;
        private String pushNotificationLevel;
        private boolean enableUpcomingChangeAvailableNotifications;
        private boolean includeTl0InDigests;
        private List<Object> themeIds;
        private int themeKeySeq;
        private boolean allowPrivateMessages;
        private boolean enableAllowedPmUsers;
        private String homepageId;
        private boolean hideProfileAndPresence;
        private boolean hideProfile;
        private boolean hidePresence;
        private String textSize;
        private int textSizeSeq;
        private String titleCountMode;
        private String timezone;
        private boolean skipNewUserTips;
        private boolean topicsUnreadWhenClosed;
        private int interfaceColorMode;
        private boolean showOriginalContent;
        private Integer bookmarkAutoDeletePreference;
        private String defaultCalendar;
        private OptionalNullable<String> oldestSearchLogDate;
        private Boolean sidebarLinkToFilteredList;
        private Boolean sidebarShowCountOfNewItems;
        private Boolean watchedPrecedenceOverMuted;
        private OptionalNullable<String> seenPopups;
        private Integer compositionMode;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  userId  int value for userId.
         * @param  mailingListMode  boolean value for mailingListMode.
         * @param  mailingListModeFrequency  int value for mailingListModeFrequency.
         * @param  emailDigests  boolean value for emailDigests.
         * @param  emailLevel  int value for emailLevel.
         * @param  emailMessagesLevel  int value for emailMessagesLevel.
         * @param  externalLinksInNewTab  boolean value for externalLinksInNewTab.
         * @param  colorSchemeId  String value for colorSchemeId.
         * @param  darkSchemeId  String value for darkSchemeId.
         * @param  dynamicFavicon  boolean value for dynamicFavicon.
         * @param  enableQuoting  boolean value for enableQuoting.
         * @param  enableSmartLists  boolean value for enableSmartLists.
         * @param  enableMarkdownMonospaceFont  boolean value for enableMarkdownMonospaceFont.
         * @param  enableDefer  boolean value for enableDefer.
         * @param  digestAfterMinutes  int value for digestAfterMinutes.
         * @param  automaticallyUnpinTopics  boolean value for automaticallyUnpinTopics.
         * @param  autoTrackTopicsAfterMsecs  int value for autoTrackTopicsAfterMsecs.
         * @param  notificationLevelWhenReplying  int value for notificationLevelWhenReplying.
         * @param  newTopicDurationMinutes  int value for newTopicDurationMinutes.
         * @param  emailPreviousReplies  int value for emailPreviousReplies.
         * @param  emailInReplyTo  boolean value for emailInReplyTo.
         * @param  likeNotificationFrequency  int value for likeNotificationFrequency.
         * @param  notifyOnLinkedPosts  boolean value for notifyOnLinkedPosts.
         * @param  pushNotificationLevel  String value for pushNotificationLevel.
         * @param  enableUpcomingChangeAvailableNotifications  boolean value for
         *         enableUpcomingChangeAvailableNotifications.
         * @param  includeTl0InDigests  boolean value for includeTl0InDigests.
         * @param  themeIds  List of Object value for themeIds.
         * @param  themeKeySeq  int value for themeKeySeq.
         * @param  allowPrivateMessages  boolean value for allowPrivateMessages.
         * @param  enableAllowedPmUsers  boolean value for enableAllowedPmUsers.
         * @param  homepageId  String value for homepageId.
         * @param  hideProfileAndPresence  boolean value for hideProfileAndPresence.
         * @param  hideProfile  boolean value for hideProfile.
         * @param  hidePresence  boolean value for hidePresence.
         * @param  textSize  String value for textSize.
         * @param  textSizeSeq  int value for textSizeSeq.
         * @param  titleCountMode  String value for titleCountMode.
         * @param  timezone  String value for timezone.
         * @param  skipNewUserTips  boolean value for skipNewUserTips.
         * @param  topicsUnreadWhenClosed  boolean value for topicsUnreadWhenClosed.
         * @param  interfaceColorMode  int value for interfaceColorMode.
         * @param  showOriginalContent  boolean value for showOriginalContent.
         */
        public Builder(int userId, boolean mailingListMode, int mailingListModeFrequency,
                boolean emailDigests, int emailLevel, int emailMessagesLevel,
                boolean externalLinksInNewTab, String colorSchemeId, String darkSchemeId,
                boolean dynamicFavicon, boolean enableQuoting, boolean enableSmartLists,
                boolean enableMarkdownMonospaceFont, boolean enableDefer, int digestAfterMinutes,
                boolean automaticallyUnpinTopics, int autoTrackTopicsAfterMsecs,
                int notificationLevelWhenReplying, int newTopicDurationMinutes,
                int emailPreviousReplies, boolean emailInReplyTo, int likeNotificationFrequency,
                boolean notifyOnLinkedPosts, String pushNotificationLevel,
                boolean enableUpcomingChangeAvailableNotifications, boolean includeTl0InDigests,
                List<Object> themeIds, int themeKeySeq, boolean allowPrivateMessages,
                boolean enableAllowedPmUsers, String homepageId, boolean hideProfileAndPresence,
                boolean hideProfile, boolean hidePresence, String textSize, int textSizeSeq,
                String titleCountMode, String timezone, boolean skipNewUserTips,
                boolean topicsUnreadWhenClosed, int interfaceColorMode,
                boolean showOriginalContent) {
            this.userId = userId;
            this.mailingListMode = mailingListMode;
            this.mailingListModeFrequency = mailingListModeFrequency;
            this.emailDigests = emailDigests;
            this.emailLevel = emailLevel;
            this.emailMessagesLevel = emailMessagesLevel;
            this.externalLinksInNewTab = externalLinksInNewTab;
            this.colorSchemeId = colorSchemeId;
            this.darkSchemeId = darkSchemeId;
            this.dynamicFavicon = dynamicFavicon;
            this.enableQuoting = enableQuoting;
            this.enableSmartLists = enableSmartLists;
            this.enableMarkdownMonospaceFont = enableMarkdownMonospaceFont;
            this.enableDefer = enableDefer;
            this.digestAfterMinutes = digestAfterMinutes;
            this.automaticallyUnpinTopics = automaticallyUnpinTopics;
            this.autoTrackTopicsAfterMsecs = autoTrackTopicsAfterMsecs;
            this.notificationLevelWhenReplying = notificationLevelWhenReplying;
            this.newTopicDurationMinutes = newTopicDurationMinutes;
            this.emailPreviousReplies = emailPreviousReplies;
            this.emailInReplyTo = emailInReplyTo;
            this.likeNotificationFrequency = likeNotificationFrequency;
            this.notifyOnLinkedPosts = notifyOnLinkedPosts;
            this.pushNotificationLevel = pushNotificationLevel;
            this.enableUpcomingChangeAvailableNotifications =
                    enableUpcomingChangeAvailableNotifications;
            this.includeTl0InDigests = includeTl0InDigests;
            this.themeIds = themeIds;
            this.themeKeySeq = themeKeySeq;
            this.allowPrivateMessages = allowPrivateMessages;
            this.enableAllowedPmUsers = enableAllowedPmUsers;
            this.homepageId = homepageId;
            this.hideProfileAndPresence = hideProfileAndPresence;
            this.hideProfile = hideProfile;
            this.hidePresence = hidePresence;
            this.textSize = textSize;
            this.textSizeSeq = textSizeSeq;
            this.titleCountMode = titleCountMode;
            this.timezone = timezone;
            this.skipNewUserTips = skipNewUserTips;
            this.topicsUnreadWhenClosed = topicsUnreadWhenClosed;
            this.interfaceColorMode = interfaceColorMode;
            this.showOriginalContent = showOriginalContent;
        }

        /**
         * Setter for userId.
         * @param  userId  int value for userId.
         * @return Builder
         */
        public Builder userId(int userId) {
            this.userId = userId;
            return this;
        }

        /**
         * Setter for mailingListMode.
         * @param  mailingListMode  boolean value for mailingListMode.
         * @return Builder
         */
        public Builder mailingListMode(boolean mailingListMode) {
            this.mailingListMode = mailingListMode;
            return this;
        }

        /**
         * Setter for mailingListModeFrequency.
         * @param  mailingListModeFrequency  int value for mailingListModeFrequency.
         * @return Builder
         */
        public Builder mailingListModeFrequency(int mailingListModeFrequency) {
            this.mailingListModeFrequency = mailingListModeFrequency;
            return this;
        }

        /**
         * Setter for emailDigests.
         * @param  emailDigests  boolean value for emailDigests.
         * @return Builder
         */
        public Builder emailDigests(boolean emailDigests) {
            this.emailDigests = emailDigests;
            return this;
        }

        /**
         * Setter for emailLevel.
         * @param  emailLevel  int value for emailLevel.
         * @return Builder
         */
        public Builder emailLevel(int emailLevel) {
            this.emailLevel = emailLevel;
            return this;
        }

        /**
         * Setter for emailMessagesLevel.
         * @param  emailMessagesLevel  int value for emailMessagesLevel.
         * @return Builder
         */
        public Builder emailMessagesLevel(int emailMessagesLevel) {
            this.emailMessagesLevel = emailMessagesLevel;
            return this;
        }

        /**
         * Setter for externalLinksInNewTab.
         * @param  externalLinksInNewTab  boolean value for externalLinksInNewTab.
         * @return Builder
         */
        public Builder externalLinksInNewTab(boolean externalLinksInNewTab) {
            this.externalLinksInNewTab = externalLinksInNewTab;
            return this;
        }

        /**
         * Setter for colorSchemeId.
         * @param  colorSchemeId  String value for colorSchemeId.
         * @return Builder
         */
        public Builder colorSchemeId(String colorSchemeId) {
            this.colorSchemeId = colorSchemeId;
            return this;
        }

        /**
         * Setter for darkSchemeId.
         * @param  darkSchemeId  String value for darkSchemeId.
         * @return Builder
         */
        public Builder darkSchemeId(String darkSchemeId) {
            this.darkSchemeId = darkSchemeId;
            return this;
        }

        /**
         * Setter for dynamicFavicon.
         * @param  dynamicFavicon  boolean value for dynamicFavicon.
         * @return Builder
         */
        public Builder dynamicFavicon(boolean dynamicFavicon) {
            this.dynamicFavicon = dynamicFavicon;
            return this;
        }

        /**
         * Setter for enableQuoting.
         * @param  enableQuoting  boolean value for enableQuoting.
         * @return Builder
         */
        public Builder enableQuoting(boolean enableQuoting) {
            this.enableQuoting = enableQuoting;
            return this;
        }

        /**
         * Setter for enableSmartLists.
         * @param  enableSmartLists  boolean value for enableSmartLists.
         * @return Builder
         */
        public Builder enableSmartLists(boolean enableSmartLists) {
            this.enableSmartLists = enableSmartLists;
            return this;
        }

        /**
         * Setter for enableMarkdownMonospaceFont.
         * @param  enableMarkdownMonospaceFont  boolean value for enableMarkdownMonospaceFont.
         * @return Builder
         */
        public Builder enableMarkdownMonospaceFont(boolean enableMarkdownMonospaceFont) {
            this.enableMarkdownMonospaceFont = enableMarkdownMonospaceFont;
            return this;
        }

        /**
         * Setter for enableDefer.
         * @param  enableDefer  boolean value for enableDefer.
         * @return Builder
         */
        public Builder enableDefer(boolean enableDefer) {
            this.enableDefer = enableDefer;
            return this;
        }

        /**
         * Setter for digestAfterMinutes.
         * @param  digestAfterMinutes  int value for digestAfterMinutes.
         * @return Builder
         */
        public Builder digestAfterMinutes(int digestAfterMinutes) {
            this.digestAfterMinutes = digestAfterMinutes;
            return this;
        }

        /**
         * Setter for automaticallyUnpinTopics.
         * @param  automaticallyUnpinTopics  boolean value for automaticallyUnpinTopics.
         * @return Builder
         */
        public Builder automaticallyUnpinTopics(boolean automaticallyUnpinTopics) {
            this.automaticallyUnpinTopics = automaticallyUnpinTopics;
            return this;
        }

        /**
         * Setter for autoTrackTopicsAfterMsecs.
         * @param  autoTrackTopicsAfterMsecs  int value for autoTrackTopicsAfterMsecs.
         * @return Builder
         */
        public Builder autoTrackTopicsAfterMsecs(int autoTrackTopicsAfterMsecs) {
            this.autoTrackTopicsAfterMsecs = autoTrackTopicsAfterMsecs;
            return this;
        }

        /**
         * Setter for notificationLevelWhenReplying.
         * @param  notificationLevelWhenReplying  int value for notificationLevelWhenReplying.
         * @return Builder
         */
        public Builder notificationLevelWhenReplying(int notificationLevelWhenReplying) {
            this.notificationLevelWhenReplying = notificationLevelWhenReplying;
            return this;
        }

        /**
         * Setter for newTopicDurationMinutes.
         * @param  newTopicDurationMinutes  int value for newTopicDurationMinutes.
         * @return Builder
         */
        public Builder newTopicDurationMinutes(int newTopicDurationMinutes) {
            this.newTopicDurationMinutes = newTopicDurationMinutes;
            return this;
        }

        /**
         * Setter for emailPreviousReplies.
         * @param  emailPreviousReplies  int value for emailPreviousReplies.
         * @return Builder
         */
        public Builder emailPreviousReplies(int emailPreviousReplies) {
            this.emailPreviousReplies = emailPreviousReplies;
            return this;
        }

        /**
         * Setter for emailInReplyTo.
         * @param  emailInReplyTo  boolean value for emailInReplyTo.
         * @return Builder
         */
        public Builder emailInReplyTo(boolean emailInReplyTo) {
            this.emailInReplyTo = emailInReplyTo;
            return this;
        }

        /**
         * Setter for likeNotificationFrequency.
         * @param  likeNotificationFrequency  int value for likeNotificationFrequency.
         * @return Builder
         */
        public Builder likeNotificationFrequency(int likeNotificationFrequency) {
            this.likeNotificationFrequency = likeNotificationFrequency;
            return this;
        }

        /**
         * Setter for notifyOnLinkedPosts.
         * @param  notifyOnLinkedPosts  boolean value for notifyOnLinkedPosts.
         * @return Builder
         */
        public Builder notifyOnLinkedPosts(boolean notifyOnLinkedPosts) {
            this.notifyOnLinkedPosts = notifyOnLinkedPosts;
            return this;
        }

        /**
         * Setter for pushNotificationLevel.
         * @param  pushNotificationLevel  String value for pushNotificationLevel.
         * @return Builder
         */
        public Builder pushNotificationLevel(String pushNotificationLevel) {
            this.pushNotificationLevel = pushNotificationLevel;
            return this;
        }

        /**
         * Setter for enableUpcomingChangeAvailableNotifications.
         * @param  enableUpcomingChangeAvailableNotifications  boolean value for
         *         enableUpcomingChangeAvailableNotifications.
         * @return Builder
         */
        public Builder enableUpcomingChangeAvailableNotifications(
                boolean enableUpcomingChangeAvailableNotifications) {
            this.enableUpcomingChangeAvailableNotifications =
                    enableUpcomingChangeAvailableNotifications;
            return this;
        }

        /**
         * Setter for includeTl0InDigests.
         * @param  includeTl0InDigests  boolean value for includeTl0InDigests.
         * @return Builder
         */
        public Builder includeTl0InDigests(boolean includeTl0InDigests) {
            this.includeTl0InDigests = includeTl0InDigests;
            return this;
        }

        /**
         * Setter for themeIds.
         * @param  themeIds  List of Object value for themeIds.
         * @return Builder
         */
        public Builder themeIds(List<Object> themeIds) {
            this.themeIds = themeIds;
            return this;
        }

        /**
         * Setter for themeKeySeq.
         * @param  themeKeySeq  int value for themeKeySeq.
         * @return Builder
         */
        public Builder themeKeySeq(int themeKeySeq) {
            this.themeKeySeq = themeKeySeq;
            return this;
        }

        /**
         * Setter for allowPrivateMessages.
         * @param  allowPrivateMessages  boolean value for allowPrivateMessages.
         * @return Builder
         */
        public Builder allowPrivateMessages(boolean allowPrivateMessages) {
            this.allowPrivateMessages = allowPrivateMessages;
            return this;
        }

        /**
         * Setter for enableAllowedPmUsers.
         * @param  enableAllowedPmUsers  boolean value for enableAllowedPmUsers.
         * @return Builder
         */
        public Builder enableAllowedPmUsers(boolean enableAllowedPmUsers) {
            this.enableAllowedPmUsers = enableAllowedPmUsers;
            return this;
        }

        /**
         * Setter for homepageId.
         * @param  homepageId  String value for homepageId.
         * @return Builder
         */
        public Builder homepageId(String homepageId) {
            this.homepageId = homepageId;
            return this;
        }

        /**
         * Setter for hideProfileAndPresence.
         * @param  hideProfileAndPresence  boolean value for hideProfileAndPresence.
         * @return Builder
         */
        public Builder hideProfileAndPresence(boolean hideProfileAndPresence) {
            this.hideProfileAndPresence = hideProfileAndPresence;
            return this;
        }

        /**
         * Setter for hideProfile.
         * @param  hideProfile  boolean value for hideProfile.
         * @return Builder
         */
        public Builder hideProfile(boolean hideProfile) {
            this.hideProfile = hideProfile;
            return this;
        }

        /**
         * Setter for hidePresence.
         * @param  hidePresence  boolean value for hidePresence.
         * @return Builder
         */
        public Builder hidePresence(boolean hidePresence) {
            this.hidePresence = hidePresence;
            return this;
        }

        /**
         * Setter for textSize.
         * @param  textSize  String value for textSize.
         * @return Builder
         */
        public Builder textSize(String textSize) {
            this.textSize = textSize;
            return this;
        }

        /**
         * Setter for textSizeSeq.
         * @param  textSizeSeq  int value for textSizeSeq.
         * @return Builder
         */
        public Builder textSizeSeq(int textSizeSeq) {
            this.textSizeSeq = textSizeSeq;
            return this;
        }

        /**
         * Setter for titleCountMode.
         * @param  titleCountMode  String value for titleCountMode.
         * @return Builder
         */
        public Builder titleCountMode(String titleCountMode) {
            this.titleCountMode = titleCountMode;
            return this;
        }

        /**
         * Setter for timezone.
         * @param  timezone  String value for timezone.
         * @return Builder
         */
        public Builder timezone(String timezone) {
            this.timezone = timezone;
            return this;
        }

        /**
         * Setter for skipNewUserTips.
         * @param  skipNewUserTips  boolean value for skipNewUserTips.
         * @return Builder
         */
        public Builder skipNewUserTips(boolean skipNewUserTips) {
            this.skipNewUserTips = skipNewUserTips;
            return this;
        }

        /**
         * Setter for topicsUnreadWhenClosed.
         * @param  topicsUnreadWhenClosed  boolean value for topicsUnreadWhenClosed.
         * @return Builder
         */
        public Builder topicsUnreadWhenClosed(boolean topicsUnreadWhenClosed) {
            this.topicsUnreadWhenClosed = topicsUnreadWhenClosed;
            return this;
        }

        /**
         * Setter for interfaceColorMode.
         * @param  interfaceColorMode  int value for interfaceColorMode.
         * @return Builder
         */
        public Builder interfaceColorMode(int interfaceColorMode) {
            this.interfaceColorMode = interfaceColorMode;
            return this;
        }

        /**
         * Setter for showOriginalContent.
         * @param  showOriginalContent  boolean value for showOriginalContent.
         * @return Builder
         */
        public Builder showOriginalContent(boolean showOriginalContent) {
            this.showOriginalContent = showOriginalContent;
            return this;
        }

        /**
         * Setter for bookmarkAutoDeletePreference.
         * @param  bookmarkAutoDeletePreference  Integer value for bookmarkAutoDeletePreference.
         * @return Builder
         */
        public Builder bookmarkAutoDeletePreference(Integer bookmarkAutoDeletePreference) {
            this.bookmarkAutoDeletePreference = bookmarkAutoDeletePreference;
            return this;
        }

        /**
         * Setter for defaultCalendar.
         * @param  defaultCalendar  String value for defaultCalendar.
         * @return Builder
         */
        public Builder defaultCalendar(String defaultCalendar) {
            this.defaultCalendar = defaultCalendar;
            return this;
        }

        /**
         * Setter for oldestSearchLogDate.
         * @param  oldestSearchLogDate  String value for oldestSearchLogDate.
         * @return Builder
         */
        public Builder oldestSearchLogDate(String oldestSearchLogDate) {
            this.oldestSearchLogDate = OptionalNullable.of(oldestSearchLogDate);
            return this;
        }

        /**
         * UnSetter for oldestSearchLogDate.
         * @return Builder
         */
        public Builder unsetOldestSearchLogDate() {
            oldestSearchLogDate = null;
            return this;
        }

        /**
         * Setter for sidebarLinkToFilteredList.
         * @param  sidebarLinkToFilteredList  Boolean value for sidebarLinkToFilteredList.
         * @return Builder
         */
        public Builder sidebarLinkToFilteredList(Boolean sidebarLinkToFilteredList) {
            this.sidebarLinkToFilteredList = sidebarLinkToFilteredList;
            return this;
        }

        /**
         * Setter for sidebarShowCountOfNewItems.
         * @param  sidebarShowCountOfNewItems  Boolean value for sidebarShowCountOfNewItems.
         * @return Builder
         */
        public Builder sidebarShowCountOfNewItems(Boolean sidebarShowCountOfNewItems) {
            this.sidebarShowCountOfNewItems = sidebarShowCountOfNewItems;
            return this;
        }

        /**
         * Setter for watchedPrecedenceOverMuted.
         * @param  watchedPrecedenceOverMuted  Boolean value for watchedPrecedenceOverMuted.
         * @return Builder
         */
        public Builder watchedPrecedenceOverMuted(Boolean watchedPrecedenceOverMuted) {
            this.watchedPrecedenceOverMuted = watchedPrecedenceOverMuted;
            return this;
        }

        /**
         * Setter for seenPopups.
         * @param  seenPopups  String value for seenPopups.
         * @return Builder
         */
        public Builder seenPopups(String seenPopups) {
            this.seenPopups = OptionalNullable.of(seenPopups);
            return this;
        }

        /**
         * UnSetter for seenPopups.
         * @return Builder
         */
        public Builder unsetSeenPopups() {
            seenPopups = null;
            return this;
        }

        /**
         * Setter for compositionMode.
         * @param  compositionMode  Integer value for compositionMode.
         * @return Builder
         */
        public Builder compositionMode(Integer compositionMode) {
            this.compositionMode = compositionMode;
            return this;
        }

        /**
         * Builds a new {@link UserOption} object using the set fields.
         * @return {@link UserOption}
         */
        public UserOption build() {
            return new UserOption(userId, mailingListMode, mailingListModeFrequency, emailDigests,
                    emailLevel, emailMessagesLevel, externalLinksInNewTab, colorSchemeId,
                    darkSchemeId, dynamicFavicon, enableQuoting, enableSmartLists,
                    enableMarkdownMonospaceFont, enableDefer, digestAfterMinutes,
                    automaticallyUnpinTopics, autoTrackTopicsAfterMsecs,
                    notificationLevelWhenReplying, newTopicDurationMinutes, emailPreviousReplies,
                    emailInReplyTo, likeNotificationFrequency, notifyOnLinkedPosts,
                    pushNotificationLevel, enableUpcomingChangeAvailableNotifications,
                    includeTl0InDigests, themeIds, themeKeySeq, allowPrivateMessages,
                    enableAllowedPmUsers, homepageId, hideProfileAndPresence, hideProfile,
                    hidePresence, textSize, textSizeSeq, titleCountMode, timezone, skipNewUserTips,
                    topicsUnreadWhenClosed, interfaceColorMode, showOriginalContent,
                    bookmarkAutoDeletePreference, defaultCalendar, oldestSearchLogDate,
                    sidebarLinkToFilteredList, sidebarShowCountOfNewItems,
                    watchedPrecedenceOverMuted, seenPopups, compositionMode);
        }
    }
}
