/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;
import java.util.List;

/**
 * This is a model class for UserColorScheme type.
 */
public class UserColorScheme {
    private int id;
    private String name;
    private boolean isDark;
    private OptionalNullable<Integer> themeId;
    private List<Object> colors;

    /**
     * Default constructor.
     */
    public UserColorScheme() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  name  String value for name.
     * @param  isDark  boolean value for isDark.
     * @param  colors  List of Object value for colors.
     * @param  themeId  Integer value for themeId.
     */
    public UserColorScheme(
            int id,
            String name,
            boolean isDark,
            List<Object> colors,
            Integer themeId) {
        this.id = id;
        this.name = name;
        this.isDark = isDark;
        this.themeId = OptionalNullable.of(themeId);
        this.colors = colors;
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  name  String value for name.
     * @param  isDark  boolean value for isDark.
     * @param  colors  List of Object value for colors.
     * @param  themeId  Integer value for themeId.
     */

    protected UserColorScheme(int id, String name, boolean isDark, List<Object> colors,
            OptionalNullable<Integer> themeId) {
        this.id = id;
        this.name = name;
        this.isDark = isDark;
        this.themeId = themeId;
        this.colors = colors;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for IsDark.
     * @return Returns the boolean
     */
    @JsonGetter("is_dark")
    public boolean getIsDark() {
        return isDark;
    }

    /**
     * Setter for IsDark.
     * @param isDark Value for boolean
     */
    @JsonSetter("is_dark")
    public void setIsDark(boolean isDark) {
        this.isDark = isDark;
    }

    /**
     * Internal Getter for ThemeId.
     * @return Returns the Internal Integer
     */
    @JsonGetter("theme_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetThemeId() {
        return this.themeId;
    }

    /**
     * Getter for ThemeId.
     * @return Returns the Integer
     */
    public Integer getThemeId() {
        return OptionalNullable.getFrom(themeId);
    }

    /**
     * Setter for ThemeId.
     * @param themeId Value for Integer
     */
    @JsonSetter("theme_id")
    public void setThemeId(Integer themeId) {
        this.themeId = OptionalNullable.of(themeId);
    }

    /**
     * UnSetter for ThemeId.
     */
    public void unsetThemeId() {
        themeId = null;
    }

    /**
     * Getter for Colors.
     * @return Returns the List of Object
     */
    @JsonGetter("colors")
    public List<Object> getColors() {
        return colors;
    }

    /**
     * Setter for Colors.
     * @param colors Value for List of Object
     */
    @JsonSetter("colors")
    public void setColors(List<Object> colors) {
        this.colors = colors;
    }

    /**
     * Converts this UserColorScheme into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UserColorScheme [" + "id=" + id + ", name=" + name + ", isDark=" + isDark
                + ", colors=" + colors + ", themeId=" + themeId + "]";
    }

    /**
     * Builds a new {@link UserColorScheme.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UserColorScheme.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, name, isDark, colors);
        builder.themeId = internalGetThemeId();
        return builder;
    }

    /**
     * Class to build instances of {@link UserColorScheme}.
     */
    public static class Builder {
        private int id;
        private String name;
        private boolean isDark;
        private List<Object> colors;
        private OptionalNullable<Integer> themeId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  name  String value for name.
         * @param  isDark  boolean value for isDark.
         * @param  colors  List of Object value for colors.
         */
        public Builder(int id, String name, boolean isDark, List<Object> colors) {
            this.id = id;
            this.name = name;
            this.isDark = isDark;
            this.colors = colors;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for isDark.
         * @param  isDark  boolean value for isDark.
         * @return Builder
         */
        public Builder isDark(boolean isDark) {
            this.isDark = isDark;
            return this;
        }

        /**
         * Setter for colors.
         * @param  colors  List of Object value for colors.
         * @return Builder
         */
        public Builder colors(List<Object> colors) {
            this.colors = colors;
            return this;
        }

        /**
         * Setter for themeId.
         * @param  themeId  Integer value for themeId.
         * @return Builder
         */
        public Builder themeId(Integer themeId) {
            this.themeId = OptionalNullable.of(themeId);
            return this;
        }

        /**
         * UnSetter for themeId.
         * @return Builder
         */
        public Builder unsetThemeId() {
            themeId = null;
            return this;
        }

        /**
         * Builds a new {@link UserColorScheme} object using the set fields.
         * @return {@link UserColorScheme}
         */
        public UserColorScheme build() {
            return new UserColorScheme(id, name, isDark, colors, themeId);
        }
    }
}
