/*
 * DiscourseApiDocumentationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for UserActionsJsonResponse type.
 */
public class UserActionsJsonResponse {
    private List<UserAction> userActions;

    /**
     * Default constructor.
     */
    public UserActionsJsonResponse() {
    }

    /**
     * Initialization constructor.
     * @param  userActions  List of UserAction value for userActions.
     */
    public UserActionsJsonResponse(
            List<UserAction> userActions) {
        this.userActions = userActions;
    }

    /**
     * Getter for UserActions.
     * @return Returns the List of UserAction
     */
    @JsonGetter("user_actions")
    public List<UserAction> getUserActions() {
        return userActions;
    }

    /**
     * Setter for UserActions.
     * @param userActions Value for List of UserAction
     */
    @JsonSetter("user_actions")
    public void setUserActions(List<UserAction> userActions) {
        this.userActions = userActions;
    }

    /**
     * Converts this UserActionsJsonResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UserActionsJsonResponse [" + "userActions=" + userActions + "]";
    }

    /**
     * Builds a new {@link UserActionsJsonResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UserActionsJsonResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(userActions);
        return builder;
    }

    /**
     * Class to build instances of {@link UserActionsJsonResponse}.
     */
    public static class Builder {
        private List<UserAction> userActions;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  userActions  List of UserAction value for userActions.
         */
        public Builder(List<UserAction> userActions) {
            this.userActions = userActions;
        }

        /**
         * Setter for userActions.
         * @param  userActions  List of UserAction value for userActions.
         * @return Builder
         */
        public Builder userActions(List<UserAction> userActions) {
            this.userActions = userActions;
            return this;
        }

        /**
         * Builds a new {@link UserActionsJsonResponse} object using the set fields.
         * @return {@link UserActionsJsonResponse}
         */
        public UserActionsJsonResponse build() {
            return new UserActionsJsonResponse(userActions);
        }
    }
}
