/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for User11 type.
 */
public class User11 {
    private int id;
    private String username;
    private String name;
    private String avatarTemplate;
    private String title;

    /**
     * Default constructor.
     */
    public User11() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  username  String value for username.
     * @param  name  String value for name.
     * @param  avatarTemplate  String value for avatarTemplate.
     * @param  title  String value for title.
     */
    public User11(
            int id,
            String username,
            String name,
            String avatarTemplate,
            String title) {
        this.id = id;
        this.username = username;
        this.name = name;
        this.avatarTemplate = avatarTemplate;
        this.title = title;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for Username.
     * @return Returns the String
     */
    @JsonGetter("username")
    public String getUsername() {
        return username;
    }

    /**
     * Setter for Username.
     * @param username Value for String
     */
    @JsonSetter("username")
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for AvatarTemplate.
     * @return Returns the String
     */
    @JsonGetter("avatar_template")
    public String getAvatarTemplate() {
        return avatarTemplate;
    }

    /**
     * Setter for AvatarTemplate.
     * @param avatarTemplate Value for String
     */
    @JsonSetter("avatar_template")
    public void setAvatarTemplate(String avatarTemplate) {
        this.avatarTemplate = avatarTemplate;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Converts this User11 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "User11 [" + "id=" + id + ", username=" + username + ", name=" + name
                + ", avatarTemplate=" + avatarTemplate + ", title=" + title + "]";
    }

    /**
     * Builds a new {@link User11.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link User11.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, username, name, avatarTemplate, title);
        return builder;
    }

    /**
     * Class to build instances of {@link User11}.
     */
    public static class Builder {
        private int id;
        private String username;
        private String name;
        private String avatarTemplate;
        private String title;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  username  String value for username.
         * @param  name  String value for name.
         * @param  avatarTemplate  String value for avatarTemplate.
         * @param  title  String value for title.
         */
        public Builder(int id, String username, String name, String avatarTemplate, String title) {
            this.id = id;
            this.username = username;
            this.name = name;
            this.avatarTemplate = avatarTemplate;
            this.title = title;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for username.
         * @param  username  String value for username.
         * @return Builder
         */
        public Builder username(String username) {
            this.username = username;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for avatarTemplate.
         * @param  avatarTemplate  String value for avatarTemplate.
         * @return Builder
         */
        public Builder avatarTemplate(String avatarTemplate) {
            this.avatarTemplate = avatarTemplate;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Builds a new {@link User11} object using the set fields.
         * @return {@link User11}
         */
        public User11 build() {
            return new User11(id, username, name, avatarTemplate, title);
        }
    }
}
