/*
 * Discourse
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.discourse.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for UsersJsonResponse type.
 */
public class UsersJsonResponse {
    private boolean success;
    private boolean active;
    private String message;
    private Integer userId;

    /**
     * Default constructor.
     */
    public UsersJsonResponse() {
    }

    /**
     * Initialization constructor.
     * @param  success  boolean value for success.
     * @param  active  boolean value for active.
     * @param  message  String value for message.
     * @param  userId  Integer value for userId.
     */
    public UsersJsonResponse(
            boolean success,
            boolean active,
            String message,
            Integer userId) {
        this.success = success;
        this.active = active;
        this.message = message;
        this.userId = userId;
    }

    /**
     * Getter for Success.
     * @return Returns the boolean
     */
    @JsonGetter("success")
    public boolean getSuccess() {
        return success;
    }

    /**
     * Setter for Success.
     * @param success Value for boolean
     */
    @JsonSetter("success")
    public void setSuccess(boolean success) {
        this.success = success;
    }

    /**
     * Getter for Active.
     * @return Returns the boolean
     */
    @JsonGetter("active")
    public boolean getActive() {
        return active;
    }

    /**
     * Setter for Active.
     * @param active Value for boolean
     */
    @JsonSetter("active")
    public void setActive(boolean active) {
        this.active = active;
    }

    /**
     * Getter for Message.
     * @return Returns the String
     */
    @JsonGetter("message")
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for UserId.
     * @return Returns the Integer
     */
    @JsonGetter("user_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getUserId() {
        return userId;
    }

    /**
     * Setter for UserId.
     * @param userId Value for Integer
     */
    @JsonSetter("user_id")
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Converts this UsersJsonResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UsersJsonResponse [" + "success=" + success + ", active=" + active + ", message="
                + message + ", userId=" + userId + "]";
    }

    /**
     * Builds a new {@link UsersJsonResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UsersJsonResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(success, active, message)
                .userId(getUserId());
        return builder;
    }

    /**
     * Class to build instances of {@link UsersJsonResponse}.
     */
    public static class Builder {
        private boolean success;
        private boolean active;
        private String message;
        private Integer userId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  success  boolean value for success.
         * @param  active  boolean value for active.
         * @param  message  String value for message.
         */
        public Builder(boolean success, boolean active, String message) {
            this.success = success;
            this.active = active;
            this.message = message;
        }

        /**
         * Setter for success.
         * @param  success  boolean value for success.
         * @return Builder
         */
        public Builder success(boolean success) {
            this.success = success;
            return this;
        }

        /**
         * Setter for active.
         * @param  active  boolean value for active.
         * @return Builder
         */
        public Builder active(boolean active) {
            this.active = active;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for userId.
         * @param  userId  Integer value for userId.
         * @return Builder
         */
        public Builder userId(Integer userId) {
            this.userId = userId;
            return this;
        }

        /**
         * Builds a new {@link UsersJsonResponse} object using the set fields.
         * @return {@link UsersJsonResponse}
         */
        public UsersJsonResponse build() {
            return new UsersJsonResponse(success, active, message, userId);
        }
    }
}
